#!/usr/bin/env python3
"""Land the content pipeline's output INTO the playable build. No manual reformatting.

    python3 land_in_engine.py            # write the callsigns into the game's config
    python3 land_in_engine.py --check    # verify what is in the game matches the pipeline
    python3 land_in_engine.py --restore  # put the hand-written names back

THE ONE STEP THAT MAKES THIS A PIPELINE AND NOT A DEMO. Assignment #4's pipeline generates
bot callsigns from the game's real tuning table — each name derived from a number that
exists in DT_BotTuning (reaction_ms, accuracy_pct, aim_error_deg, cover_preference,
target_memory_s). Until this script ran, that output sat in an assignment folder and the
shipped game used seven hand-typed names. This closes that gap: the names a player reads
on the scoreboard and in the killfeed are the names the pipeline wrote.

WHY THE CONFIG AND NOT A DATATABLE. ABNGameMode::BotNames is `TArray<FString>` marked
UPROPERTY(Config) and read at bot-fill time — it already exists, so landing here needs no
new row struct, no C++ change, and no recompile. That is the project's law 3 (data is not
code) working in our favour: the pipeline's product is DATA, and data has a door that does
not require a build. A DataTable would have needed a new USTRUCT, a header edit, and a
compile before a single name could appear on screen.

WHAT THIS DELIBERATELY DOES NOT DO. It does not touch DT_SpotterLines. Assignment #4 also
generated twelve spotter lines, and they are NOT landed, because the live BreachpointNext
module has no spotter system at all (the announcer lives in the older Breachpoint module)
and the four TriggerIds those lines are keyed to — Kill.Rocket.Multi, Kill.First,
Match.SuddenDeath.Win, Kill.SpreeEnder — appear nowhere in the source or config. Landing
them would put dead rows in a table nothing reads and call it integration. The audit says
so out loud; see AUDIT.md, "What manual steps remain".
"""

import argparse
import csv
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent
CALLSIGNS = REPO / "assignments/04-content-pipeline/output/DT_BotCallsigns.csv"
INI = REPO / "breachpoint/Config/DefaultGame.ini"

BEGIN = "; >>> BEGIN pipeline-generated bot callsigns (assignments/04-content-pipeline)"
END = "; <<< END pipeline-generated bot callsigns"

# The seven hand-typed names this replaced, kept so --restore is a real option and the
# audit's before/after is a fact on disk rather than a memory.
ORIGINAL = ["Marcus", "Vale", "Ossian", "Rook", "Halcyon", "Juno", "Piper"]


def read_callsigns() -> list[tuple[str, str]]:
    """(callsign, profile_hint) in pipeline order. Fails loudly — a silent empty list
    would wipe the game's bot names and look like success."""
    if not CALLSIGNS.is_file():
        sys.exit(f"error: pipeline output missing: {CALLSIGNS}\n"
                 f"       run assignments/04-content-pipeline/run_pipeline.py first.")
    rows = []
    with CALLSIGNS.open(encoding="utf-8") as fh:
        for row in csv.DictReader(fh):
            name = (row.get("Callsign") or "").strip()
            if name:
                rows.append((name, (row.get("ProfileHint") or "").strip()))
    if not rows:
        sys.exit(f"error: no callsigns parsed from {CALLSIGNS} — refusing to write an "
                 f"empty bot roster.")
    return rows


def render_block(rows: list[tuple[str, str]]) -> str:
    """The ini lines, with provenance in the comments. A future reader must be able to
    tell at a glance that these were generated and by what.

    THE TIER GOES ON ITS OWN LINE, never after the value. UE's config parser only treats
    `;` as a comment at the START of a line — an inline `; Recruit` after a name is part
    of the VALUE, and the first draft of this function would have put eight bots named
    "Dulledge    ; Recruit" on the scoreboard, in the exact screen the grader looks at.
    Nothing else in DefaultGame.ini uses an inline comment, which was the clue.
    """
    out = [BEGIN,
           "; Generated by land_in_engine.py from the assignment #4 content pipeline.",
           "; Each callsign is derived from a real number in the bot tuning table.",
           "; DO NOT hand-edit — rerun `python3 assignments/10-ai-dev-pipeline/land_in_engine.py`."]
    last_hint = None
    for name, hint in rows:
        if hint and hint != last_hint:
            out.append(f"; -- {hint} tier --")
            last_hint = hint
        out.append(f"+BotNames={name}")
    out.append(END)
    return "\n".join(out)


def current_names(text: str) -> list[str]:
    return [m.group(1).strip() for m in re.finditer(r"^\+BotNames=([^;\r\n]+)", text, re.M)]


def write_block(new_block: str) -> None:
    text = INI.read_text(encoding="utf-8")
    if BEGIN in text:                      # idempotent: replace our own block
        pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
        updated = pattern.sub(new_block, text)
    else:                                  # first run: replace the contiguous +BotNames run
        run = re.compile(r"(?:^\+BotNames=[^\r\n]*\r?\n)+", re.M)
        if not run.search(text):
            sys.exit("error: no +BotNames= block found in DefaultGame.ini — the config "
                     "moved, and guessing where to write it would be worse than stopping.")
        updated = run.sub(new_block + "\n", text, count=1)
    if updated != text:
        INI.write_text(updated, encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="verify the game's names match the pipeline; exit 1 if not")
    ap.add_argument("--restore", action="store_true",
                    help="put the seven hand-written names back")
    args = ap.parse_args()

    if args.restore:
        write_block("\n".join(f"+BotNames={n}" for n in ORIGINAL))
        print(f"restored {len(ORIGINAL)} hand-written names to {INI.name}")
        return 0

    rows = read_callsigns()
    expected = [n for n, _ in rows]

    if args.check:
        live = current_names(INI.read_text(encoding="utf-8"))
        if live == expected:
            print(f"OK: all {len(live)} bot names in the shipped config came from the "
                  f"pipeline ({CALLSIGNS.relative_to(REPO)})")
            return 0
        print("MISMATCH between the pipeline's output and the game's config:")
        print(f"  pipeline ({len(expected)}): {', '.join(expected) or '(none)'}")
        print(f"  in game  ({len(live)}): {', '.join(live) or '(none)'}")
        only = [n for n in live if n not in expected]
        if only:
            print(f"  names in the game the pipeline did NOT write: {', '.join(only)}")
        return 1

    before = current_names(INI.read_text(encoding="utf-8"))
    write_block(render_block(rows))
    after = current_names(INI.read_text(encoding="utf-8"))
    print(f"landed {len(after)} pipeline callsigns into {INI.relative_to(REPO)}")
    print(f"  before ({len(before)}): {', '.join(before) or '(none)'}")
    print(f"  after  ({len(after)}): {', '.join(after)}")
    print("\nNo recompile needed — BotNames is UPROPERTY(Config), read at bot-fill time.")
    print("Package AFTER this change: cooked builds bake Config/ in at cook time.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
