#!/usr/bin/env python3
# =====================================================================================
# BREACHPOINT - render_plan.py :: the committed declarative plan for the weapon silhouettes
#
# Serves:   docs/ui/WEAPON-RENDER-PLAN.md section 3 (the camera rig) and section 4 (the
#           committed plan file). R37.1 - "a committed plan specifies the asset before it
#           lands"; this file IS that plan.
# Law:      CLAUDE.md law 3 (asset refs in data are SOFT), law 7 (assets are generated by
#           committed scripts, never hand-placed).
# Doctrine: .claude/skills/ue-editor - the plan is the source of truth, the PNG and the
#           .uasset are its projection.
#
# THIS FILE IMPORTS NOTHING FROM UNREAL. Plain CPython 3.9+, stdlib only, so the whole plan
# can be validated and reviewed WITHOUT an editor:
#
#     python Tools/render_weapons/render_plan.py --verbose
#
# render_weapons.py (which does import unreal) imports this module and executes what it
# returns. Same split as Tools/gen_input and Tools/blockout: every decision is made here, in
# reviewable text; the editor half is a dumb executor plus the asserts only live assets can
# answer.
#
# DEPARTURE FROM THE PLAN DOCUMENT, RECORDED: section 4.1 called for the table to live in
# `weapon_render_profile.json` and deliberately skipped a `*_plan.py` split. It is inverted
# here - one Python file holding both the table and its validation - for one reason: the
# framing values below are UNVERIFIED GUESSES and JSON cannot carry the warning next to the
# number. When the spike has determined the real values and the warnings come off, moving
# the table back out to JSON is a mechanical change.
#
# Exit codes match the ladder convention (Tools/_BRLadderCommon.ps1):
#   0 PASS  plan is valid    1 FAIL  validation errors    3 BLOCKED  cannot read inputs
# =====================================================================================
"""The weapon-silhouette render plan: the table, its validation, and the framing math."""

import argparse
import csv
import hashlib
import json
import math
import os
import re
import sys

# -------------------------------------------------------------------------------------
# THE CONTRACT. These are acceptance law - WEAPON-RENDER-PLAN.md sections 2 and 3. They are
# constants HERE and are deliberately not per-row knobs: the table chooses among legal
# values, it cannot legalise an illegal one. (Same rule as input_plan.CONTRACT_*.)
#
# "The rig is identical for every weapon. This is the single most important rule in the
# document." - section 3. A per-weapon camera is how three individually flattering icons
# become one incoherent tray.
# -------------------------------------------------------------------------------------

CANVAS_W = 192          # section 2.1 - 2x master. Divisible by 4 so BC never mangles it.
CANVAS_H = 64
SAFE_W = 188            # the 2px transparent margin is load-bearing (edge-clamp artifacts)
SAFE_H = 62
SUPERSAMPLE = 4         # render 768x256, threshold there, box-downsample. NEVER TAA.
FILL_FRACTION = 0.96    # the LARGEST weapon's long axis fills this much of SAFE_W

CAMERA_FORWARD = (0.0, -1.0, 0.0)   # UE world axes: X forward, Y right, Z up
CAMERA_UP = (0.0, 0.0, 1.0)
CAMERA_ROLL_DEG = 0.0               # section 3.1: "Roll must be exactly 0."

SOURCE_TABLE = "Content/Data/DT_Weapons.csv"
OUTPUT_DIR = "Tools/render_weapons/out"
PACKAGE_DIR = "/Game/UI/Icons/Weapons"      # BP10's owner path (law 5)
OWNER_PACKAGE_ROOT = "/Game/UI"

# section 3.3 - the unlit flat-white override. UNVERIFIED: nobody has read this material's
# parameters, and it may not even be an unlit constant. See ASSUMPTION A3 in render_weapons.py.
UNLIT_MATERIAL = "/Game/LevelPrototyping/Materials/M_FlatCol.M_FlatCol"

MAX_HOLE_KEEP = 2       # section 7.3, measured from the reference set
OUT_NAME_RE = re.compile(r"^T_WeaponSil_[A-Za-z][A-Za-z0-9_]*$")
SOFT_PATH_RE = re.compile(r"^/Game/[A-Za-z0-9_/]+\.[A-Za-z0-9_]+$")

ERROR = "error"
WARN = "warn"
INFO = "info"


# =====================================================================================
# THE TABLE - one row per weapon, seeded from Content/Data/DT_Weapons.csv
#
# ##################################################################################
# #  EVERY yaw_deg / roll_deg / flip_x VALUE BELOW IS AN UNVERIFIED GUESS.          #
# #                                                                                 #
# #  The mesh authoring axes are NOT KNOWN (WEAPON-RENDER-PLAN.md section 9.1).     #
# #  Nobody has opened SM_Rifle, SM_Pistol or SM_GrenadeLauncher. Which local axis  #
# #  is the barrel, and where the pivot sits, cannot be read out of the repo - the  #
# #  .uasset needs an editor. All three rows are seeded with the IDENTITY guess     #
# #  (0, 0, false), which is the guess that is easiest to SEE being wrong: if the   #
# #  first render shows a weapon nose-on, or upside down, or off-canvas, the guess  #
# #  was wrong and the render says so immediately.                                  #
# #                                                                                 #
# #  DETERMINING THESE IS THE ENTIRE PURPOSE OF THE FIRST RUN. See the SPIKE        #
# #  CHECKLIST in docs/ui/WEAPON-RENDER-PLAN.md section 11, and feed the corrected  #
# #  values back here with the receipt that determined them cited in the comment.   #
# ##################################################################################
#
# Field meanings are section 4.2's schema, unchanged:
#   row            must equal a Name in DT_Weapons.csv
#   mesh           must BYTE-EQUAL that row's MeshSoftPath (section 4.3 - the assertion this
#                  whole document exists for). A soft path, law 3.
#   out            output basename, no extension. T_WeaponSil_<Row>.
#   out_w / out_h  output pixel size. IDENTICAL FOR EVERY ROW BY RULE - the family shares one
#                  canvas as it shares one camera. A row that differs is a departure and is
#                  reported as a finding, not silently honoured.
#   yaw_deg        rotation about world Z applied to the mesh before framing (UNVERIFIED)
#   roll_deg       rotation about the camera forward axis, world Y (UNVERIFIED)
#   flip_x         mirror so the whole family points the same way. WHICH way is a design call
#                  nobody has made (section 9.6) - false everywhere until someone owns it.
#   scale_override size multiplier for this row only. null = the family rule (section 3.2).
#                  Non-null is a deliberate departure and `justification` must say why.
#   hole_keep      which negative-space holes survive the reduction. Max 2 (section 7.3).
#                  NOT IMPLEMENTED IN THE SPIKE - the executor does no hole detection yet.
# =====================================================================================

WEAPONS = [
    {
        "row": "AR",
        "mesh": "/Game/Weapons/Rifle/Meshes/SM_Rifle.SM_Rifle",
        "out": "T_WeaponSil_AR",
        "out_w": CANVAS_W,
        "out_h": CANVAS_H,
        "yaw_deg": 0.0,          # UNVERIFIED GUESS - identity. See the banner above.
        "roll_deg": 0.0,         # UNVERIFIED GUESS - identity.
        "flip_x": False,         # UNVERIFIED - the family direction has no owner (9.6).
        "scale_override": None,
        "justification": "",
        "hole_keep": [],
    },
    {
        "row": "Magnum",
        "mesh": "/Game/Weapons/Pistol/Meshes/SM_Pistol.SM_Pistol",
        "out": "T_WeaponSil_Magnum",
        "out_w": CANVAS_W,
        "out_h": CANVAS_H,
        "yaw_deg": 0.0,          # UNVERIFIED GUESS - identity.
        "roll_deg": 0.0,         # UNVERIFIED GUESS - identity.
        "flip_x": False,
        # Expected to be the row that tempts someone into a scale_override: at true relative
        # scale a magnum is roughly a third of a launcher. Section 3.2 says that is
        # INFORMATION, not a defect. Do not fill this in without reading 3.2 first.
        "scale_override": None,
        "justification": "",
        "hole_keep": [],
    },
    {
        "row": "Rocket",
        "mesh": "/Game/Weapons/GrenadeLauncher/Meshes/SM_GrenadeLauncher.SM_GrenadeLauncher",
        "out": "T_WeaponSil_Rocket",
        "out_w": CANVAS_W,
        "out_h": CANVAS_H,
        "yaw_deg": 0.0,          # UNVERIFIED GUESS - identity.
        "roll_deg": 0.0,         # UNVERIFIED GUESS - identity.
        "flip_x": False,
        "scale_override": None,
        "justification": "",
        "hole_keep": [],
    },
]


# =====================================================================================
# findings
# =====================================================================================

class Finding(object):
    """One validator result. `code` is stable so a triager can grep for it."""

    def __init__(self, severity, code, message):
        self.severity = severity
        self.code = code
        self.message = message

    def as_dict(self):
        return {"severity": self.severity, "code": self.code, "message": self.message}

    def __str__(self):
        return "%-5s %-28s %s" % (self.severity.upper(), self.code, self.message)


class PlanError(Exception):
    """Raised when an input cannot be read at all (BLOCKED, not FAIL)."""


# =====================================================================================
# the framing math - section 3.2, and the reason the projection is orthographic
#
# "Under ortho, bounding-box-units -> pixels is a single scalar. Fitting is exact
# arithmetic, not an iterative solve, so the plan can compute and print the framing with no
# editor open - which is what makes section 4 reviewable."
#
# This is the half of the pipeline that CAN be checked without an editor, and
# selftest_no_editor.py checks it. What cannot be checked here is the INPUT: the mesh
# bounds come from the editor, and every number below is only as good as those.
# =====================================================================================

def project_extent(half_extent, yaw_deg, roll_deg):
    """Local half-extents (hx, hy, hz) -> (width_uu, height_uu) on the camera plane.

    Camera forward is (0,-1,0) and up is (0,0,1), so the image's horizontal axis is world X
    and its vertical axis is world Z. Yaw is about world Z (mixes X into Y and back); roll
    is about world Y, the camera forward axis (mixes X and Z).

    This is the axis-aligned bound of the ROTATED BOX, not of the mesh's silhouette. For any
    rotation that is not a multiple of 90 degrees it OVER-estimates - a diagonal box bounds
    more empty space than the shape inside it. Over-estimating is the safe direction: the
    weapon is drawn slightly smaller than it could be, never clipped. If a corrected yaw ends
    up far from a right angle, expect a visible margin and treat that as expected, not as a
    framing bug.
    """
    hx, hy, hz = (abs(float(v)) for v in half_extent)
    cy, sy = abs(math.cos(math.radians(yaw_deg))), abs(math.sin(math.radians(yaw_deg)))
    # yaw about Z: Z is untouched.
    ax = hx * cy + hy * sy
    az = hz
    cr, sr = abs(math.cos(math.radians(roll_deg))), abs(math.sin(math.radians(roll_deg)))
    # roll about Y: mixes the two axes we actually draw.
    return (2.0 * (ax * cr + az * sr), 2.0 * (ax * sr + az * cr))


def derive_uu_per_px(projected):
    """[(row, width_uu, height_uu)] -> the ONE uu_per_px the whole family shares.

    Section 3.2, step 3: the LARGEST weapon's projected long axis occupies FILL_FRACTION of
    the safe box's width. Every other weapon then uses that same scalar, which is why a
    magnum reads smaller than a launcher - relative size is information the mesh already
    carries and fitting each weapon to the box would throw it away.

    Returns (uu_per_px, driver_row). Raises PlanError on empty or degenerate input rather
    than dividing by zero and producing a plausible-looking number.
    """
    usable = [(r, w) for r, w, _h in projected if w > 0.0]
    if not usable:
        raise PlanError("no weapon has a positive projected width; every mesh bound is "
                        "degenerate or missing. Nothing can be framed.")
    driver_row, driver_w = max(usable, key=lambda t: t[1])
    return driver_w / (SAFE_W * FILL_FRACTION), driver_row


def row_uu_per_px(shared, scale_override):
    """Apply a per-row scale_override to the shared scalar.

    NAMING DEPARTURE, RECORDED: section 4.2 describes scale_override as "a multiplier on the
    shared uu_per_px". Taken literally that is inverted at the call site - you would type 0.8
    to make a weapon BIGGER, which is exactly the kind of knob somebody turns the wrong way at
    2am. It is implemented here as a size multiplier (2.0 = drawn twice as large), i.e. a
    DIVISOR on uu_per_px. All three rows are null today, so nothing depends on the choice yet.
    """
    if scale_override in (None, "", 0):
        return shared
    return shared / float(scale_override)


def frame_row(w, half_extent, shared_uu_per_px):
    """One row's framing numbers, in pixels, at the 1x master canvas."""
    uupp = row_uu_per_px(shared_uu_per_px, w.get("scale_override"))
    width_uu, height_uu = project_extent(half_extent, w["yaw_deg"], w["roll_deg"])
    return {
        "row": w["row"],
        "uu_per_px": uupp,
        "projected_uu": [width_uu, height_uu],
        "projected_px": [width_uu / uupp, height_uu / uupp],
        # OrthoWidth covers the FULL canvas, not the safe box, and is resolution-independent -
        # the supersampled render uses the same ortho width at 4x the pixels.
        "ortho_width_uu": CANVAS_W * uupp,
        "render_px": [CANVAS_W * SUPERSAMPLE, CANVAS_H * SUPERSAMPLE],
        "fill_fraction_w": (width_uu / uupp) / SAFE_W,
        "fill_fraction_h": (height_uu / uupp) / SAFE_H,
    }


# =====================================================================================
# validation - every refusal section 4.3 names, plus the ones this table can carry
# =====================================================================================

def read_source_table(path):
    """Content/Data/DT_Weapons.csv -> {Name: MeshSoftPath}. Raises PlanError if unreadable."""
    if not os.path.isfile(path):
        raise PlanError("source table not found: %s" % path)
    try:
        with open(path, "r", encoding="utf-8-sig", newline="") as fh:
            rows = list(csv.DictReader(fh))
    except (OSError, csv.Error) as exc:
        raise PlanError("source table could not be read (%s): %s" % (exc, path))
    if not rows:
        raise PlanError("source table has no rows: %s" % path)
    for required in ("Name", "MeshSoftPath"):
        if required not in rows[0]:
            raise PlanError("source table has no '%s' column: %s" % (required, path))
    return dict((r["Name"], (r.get("MeshSoftPath") or "").strip()) for r in rows if r.get("Name"))


def validate(weapons, table):
    """Returns a list of Finding. Nothing stops at the first problem - one run, the whole list."""
    f = []
    seen_rows = {}
    seen_out = {}

    for i, w in enumerate(weapons):
        row = w.get("row")
        if not row:
            f.append(Finding(ERROR, "ROW_NO_NAME", "weapons[%d] has no row name." % i))
            continue
        if row in seen_rows:
            f.append(Finding(ERROR, "ROW_DUPLICATE",
                             "row '%s' is declared twice (weapons[%d] and [%d])."
                             % (row, seen_rows[row], i)))
        seen_rows[row] = i

        # ---- section 4.3: THE assertion. The icon must come from the mesh the game equips.
        if row not in table:
            f.append(Finding(ERROR, "ROW_UNKNOWN",
                             "row '%s' is not a Name in %s. An icon for a weapon that does not "
                             "exist is an icon nothing can ever show." % (row, SOURCE_TABLE)))
        elif w.get("mesh") != table[row]:
            f.append(Finding(ERROR, "MESH_PATH_DRIFT",
                             "row '%s' names mesh '%s' but %s says '%s'. THIS IS THE REFUSAL THE "
                             "WHOLE PIPELINE EXISTS FOR: if the icon can be rendered from a mesh "
                             "other than the one the game equips, the icon can drift from the "
                             "weapon - which is the failure mode of a hand-drawing, reintroduced "
                             "with more steps. Fix the table or fix this row; do not 'fix' the "
                             "assertion." % (row, w.get("mesh"), SOURCE_TABLE, table[row])))

        mesh = w.get("mesh") or ""
        if not SOFT_PATH_RE.match(mesh):
            f.append(Finding(ERROR, "MESH_PATH_SHAPE",
                             "row '%s' mesh '%s' is not a well-formed /Game/... object path "
                             "(/Game/Dir/SM_X.SM_X). Whether the asset EXISTS is an editor "
                             "question; this is only the shape check." % (row, mesh)))

        out = w.get("out") or ""
        if not OUT_NAME_RE.match(out):
            f.append(Finding(ERROR, "OUT_NAME_SHAPE",
                             "row '%s' output name '%s' is not T_WeaponSil_<Row> (section 2.3)."
                             % (row, out)))
        elif out != "T_WeaponSil_%s" % row:
            f.append(Finding(ERROR, "OUT_NAME_ROW_MISMATCH",
                             "row '%s' outputs '%s'. The name keys on the DT_Weapons row name, "
                             "because the row name is what the HUD already has in hand."
                             % (row, out)))
        if out in seen_out:
            f.append(Finding(ERROR, "OUT_NAME_DUPLICATE",
                             "output name '%s' is used by both '%s' and '%s'. The second render "
                             "would silently overwrite the first."
                             % (out, seen_out[out], row)))
        seen_out[out] = row

        if (w.get("out_w"), w.get("out_h")) != (CANVAS_W, CANVAS_H):
            f.append(Finding(ERROR, "OUT_SIZE_DEPARTURE",
                             "row '%s' asks for %sx%s; the family canvas is %dx%d (section 2.1). "
                             "One master, one canvas, one camera - a per-row size is the same "
                             "defect as a per-row camera and is invisible one icon at a time."
                             % (row, w.get("out_w"), w.get("out_h"), CANVAS_W, CANVAS_H)))

        for k in ("yaw_deg", "roll_deg"):
            v = w.get(k)
            if not isinstance(v, (int, float)):
                f.append(Finding(ERROR, "ANGLE_TYPE",
                                 "row '%s' %s is %r; expected a number." % (row, k, v)))
            elif v != 0.0:
                # Not an error - these fields EXIST to be non-zero once the spike has run.
                # But section 4.2: "Every non-zero value must be justified in the receipt."
                f.append(Finding(WARN, "ORIENTATION_CORRECTION",
                                 "row '%s' carries %s=%s. Justify it in the receipt: which axis "
                                 "the mesh authored the barrel on, and the run that determined "
                                 "it. A framing knob nobody can explain is a guess with a "
                                 "decimal point." % (row, k, v)))

        if not isinstance(w.get("flip_x"), bool):
            f.append(Finding(ERROR, "FLIP_TYPE",
                             "row '%s' flip_x is %r; expected a bool." % (row, w.get("flip_x"))))

        so = w.get("scale_override")
        if so is not None:
            if not isinstance(so, (int, float)) or so <= 0:
                f.append(Finding(ERROR, "SCALE_OVERRIDE_SHAPE",
                                 "row '%s' scale_override is %r; expected a positive number or "
                                 "None." % (row, so)))
            if not (w.get("justification") or "").strip():
                f.append(Finding(ERROR, "SCALE_OVERRIDE_UNJUSTIFIED",
                                 "row '%s' departs from the shared-scale rule (section 3.2) with "
                                 "no justification. Relative size is information the player uses; "
                                 "discarding it for one weapon needs a stated reason." % row))

        holes = w.get("hole_keep") or []
        if len(holes) > MAX_HOLE_KEEP:
            f.append(Finding(ERROR, "HOLE_KEEP_TOO_MANY",
                             "row '%s' keeps %d holes; the measured reduction rule allows at most "
                             "%d (section 7.3)." % (row, len(holes), MAX_HOLE_KEEP)))
        if holes:
            f.append(Finding(WARN, "HOLE_KEEP_NOT_IMPLEMENTED",
                             "row '%s' names hole_keep %s, but the spike executor does NO hole "
                             "detection or reduction. The field is honoured by nothing today."
                             % (row, holes)))

    # ---- every row in the table must have an icon (section 4.3, ROW_MISSING) ---------
    for name in table:
        if name not in seen_rows:
            f.append(Finding(ERROR, "ROW_MISSING",
                             "%s carries row '%s' and this plan has no entry for it. Adding a "
                             "fourth weapon without an icon must fail the run, not ship a blank "
                             "slot." % (SOURCE_TABLE, name)))

    # ---- law 5 / section 2.3 ---------------------------------------------------------
    if not PACKAGE_DIR.startswith(OWNER_PACKAGE_ROOT + "/"):
        f.append(Finding(ERROR, "PACKAGE_OUT_OF_OWNER_PATH",
                         "package_dir is '%s', outside %s. Content/UI is BP10's owner path; "
                         "writing elsewhere is a law-5 violation the guard hook cannot see "
                         "(it does not watch the editor)." % (PACKAGE_DIR, OWNER_PACKAGE_ROOT)))

    # ---- rig sanity: constants nobody should have edited ------------------------------
    if CAMERA_ROLL_DEG != 0.0:
        f.append(Finding(ERROR, "CAMERA_ROLL",
                         "camera roll is %s. Section 3.1: it must be exactly 0 - a tilted weapon "
                         "reads as a different design language, and that decision belongs in the "
                         "icon spec, not in a camera." % CAMERA_ROLL_DEG))
    if not (0.0 < FILL_FRACTION <= 1.0):
        f.append(Finding(ERROR, "FILL_FRACTION",
                         "fill_fraction is %s; must be in (0, 1]." % FILL_FRACTION))
    if SUPERSAMPLE < 2:
        f.append(Finding(ERROR, "SUPERSAMPLE",
                         "supersample is %d. The threshold-then-downsample order in section 7.1 "
                         "is what produces a clean edge WITHOUT TAA; at 1x there is nothing to "
                         "downsample and the edge is jagged." % SUPERSAMPLE))
    return f


# =====================================================================================
# plan construction
# =====================================================================================

def build_plan(weapons=None, table_path=None):
    """Validate and return the plan dict. Framing is absent until the editor supplies bounds."""
    weapons = WEAPONS if weapons is None else weapons
    tpath = table_path or os.path.join(repo_root(), *SOURCE_TABLE.split("/"))
    table = read_source_table(tpath)
    findings = validate(weapons, table)
    plan = {
        "schema": "breachpoint.weaponrender.plan/1",
        "status": "SPIKE - every yaw_deg/roll_deg/flip_x below is an UNVERIFIED GUESS",
        "source_table": SOURCE_TABLE,
        "source_table_path": os.path.abspath(tpath),
        "source_table_sha256": digest_file(tpath),
        "output_dir": OUTPUT_DIR,
        "package_dir": PACKAGE_DIR,
        "canvas": {"w": CANVAS_W, "h": CANVAS_H, "safe_w": SAFE_W, "safe_h": SAFE_H,
                   "supersample": SUPERSAMPLE},
        "rig": {"projection": "orthographic",
                "camera_forward": list(CAMERA_FORWARD),
                "camera_up": list(CAMERA_UP),
                "camera_roll_deg": CAMERA_ROLL_DEG,
                "fill_fraction": FILL_FRACTION,
                "unlit_material": UNLIT_MATERIAL,
                # null: derived from the largest weapon at run time and recorded in the
                # receipt. Pin it to a number once the set is stable, so adding a fourth
                # weapon cannot silently rescale the other three.
                "uu_per_px": None},
        "weapons": [dict(w) for w in weapons],
        "findings": [x.as_dict() for x in findings],
        "errors": len([x for x in findings if x.severity == ERROR]),
        "warnings": len([x for x in findings if x.severity == WARN]),
    }
    plan["digest"] = plan_digest(plan)
    return plan


def plan_digest(plan):
    """sha256 over the parts a re-run must reproduce exactly - the determinism handle.

    Covers the table and the rig. It deliberately does NOT cover findings text (advisory) or
    the .uasset bytes: Unreal reserialises package metadata on every save, so binary equality
    is not a property this toolchain claims. The PNG sha256 in the receipt is the artifact
    that IS expected to be stable (section 8.4).
    """
    body = {"weapons": plan["weapons"], "rig": plan["rig"], "canvas": plan["canvas"],
            "package_dir": plan["package_dir"]}
    return hashlib.sha256(
        json.dumps(body, sort_keys=True, separators=(",", ":")).encode("utf-8")).hexdigest()


def digest_file(path):
    with open(path, "rb") as fh:
        return hashlib.sha256(fh.read()).hexdigest()


def repo_root():
    return os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


# =====================================================================================
# cli
# =====================================================================================

def print_report(plan, verbose=False):
    out = sys.stdout
    out.write("=" * 88 + "\n")
    out.write("BREACHPOINT weapon silhouette render plan\n")
    out.write("=" * 88 + "\n")
    out.write("STATUS        : %s\n" % plan["status"])
    out.write("source table  : %s\n" % plan["source_table_path"])
    out.write("table sha     : %s\n" % plan["source_table_sha256"])
    out.write("plan digest   : %s\n" % plan["digest"])
    out.write("canvas        : %dx%d (safe %dx%d), supersampled x%d -> %dx%d render\n"
              % (CANVAS_W, CANVAS_H, SAFE_W, SAFE_H, SUPERSAMPLE,
                 CANVAS_W * SUPERSAMPLE, CANVAS_H * SUPERSAMPLE))
    out.write("rig           : orthographic, forward %s, up %s, roll %.1f, fill %.2f\n"
              % (CAMERA_FORWARD, CAMERA_UP, CAMERA_ROLL_DEG, FILL_FRACTION))
    out.write("uu_per_px     : DERIVED AT RUN TIME from the largest weapon's bounds - the "
              "editor is the only source of those\n")

    out.write("\n---- weapons ----\n")
    for w in plan["weapons"]:
        out.write("  %-8s %-16s yaw=%-6s roll=%-6s flip_x=%-5s scale=%-5s -> %s\n"
                  % (w["row"], w["mesh"].rsplit("/", 1)[-1], w["yaw_deg"], w["roll_deg"],
                     w["flip_x"], w["scale_override"], w["out"]))
        if verbose:
            out.write("           mesh: %s\n" % w["mesh"])

    out.write("\n---- findings (%d error, %d warn) ----\n" % (plan["errors"], plan["warnings"]))
    order = {ERROR: 0, WARN: 1, INFO: 2}
    if not plan["findings"]:
        out.write("  (none)\n")
    for fd in sorted(plan["findings"], key=lambda d: order.get(d["severity"], 3)):
        out.write("  %-5s %-28s %s\n" % (fd["severity"].upper(), fd["code"], fd["message"]))

    out.write("\n")
    if plan["errors"]:
        out.write("VERDICT: FAIL - %d error(s). Nothing will be rendered.\n" % plan["errors"])
    else:
        out.write(
            "VERDICT: PASS - the table is internally consistent and agrees with DT_Weapons.csv.\n"
            "         That is ALL it means. It does not mean the meshes load, that the framing\n"
            "         values are right (they are guesses - see the banner in render_plan.py), or\n"
            "         that anything has ever been rendered. The first editor run is a SPIKE\n"
            "         expected to correct section 3.3 and the orientation columns.\n")


def main(argv=None):
    ap = argparse.ArgumentParser(
        description="Validate the weapon render plan and print it. Plain CPython - no editor, "
                    "no unreal module, safe while someone else holds the project lock.")
    ap.add_argument("--table", default=None, help="path to DT_Weapons.csv")
    ap.add_argument("--json", default=None, help="write the full plan JSON to this path")
    ap.add_argument("--verbose", action="store_true")
    args = ap.parse_args(argv)

    try:
        plan = build_plan(table_path=args.table)
    except PlanError as exc:
        sys.stderr.write("BLOCKED: %s\n" % exc)
        return 3

    print_report(plan, verbose=args.verbose)
    if args.json:
        with open(args.json, "w", encoding="utf-8") as fh:
            json.dump(plan, fh, indent=2, sort_keys=True)
        sys.stdout.write("plan written: %s\n" % os.path.abspath(args.json))
    return 1 if plan["errors"] else 0


if __name__ == "__main__":
    sys.exit(main())
