#!/usr/bin/env python3
# =====================================================================================
# BREACHPOINT - render_weapons.py :: render the weapon silhouettes from the meshes
#
# Serves:   docs/ui/WEAPON-RENDER-PLAN.md (Tier 4 of ASSET-METHODS.md). Runs INSIDE Unreal
#           (it imports `unreal`).
# Law:      CLAUDE.md law 3 (soft refs), law 5 (owner paths - /Game/UI is BP10's),
#           law 7 (assets are generated by committed scripts, never hand-placed).
# Rulings:  R37 (a committed plan specifies the asset; a receipt is committed with it),
#           R21/R29/R36 (an open editor and anything that takes the project lock must not
#           overlap - and this commandlet TAKES THE LOCK without being a build).
#
# ############################### THIS IS A SPIKE #####################################
# #                                                                                   #
# #  NOTHING IN THIS FILE HAS EVER BEEN RUN. No editor was opened to write it. Every  #
# #  `unreal` API name below was taken from the 5.8 docs and IS UNVERIFIED. The first #
# #  run is expected to FAIL and to correct section 3.3 of the plan document - that   #
# #  is the intended shape, not a defect (WEAPON-RENDER-PLAN.md section 9.5).         #
# #                                                                                   #
# #  Consequently it is written to FAIL LOUDLY AND EARLY rather than half-produce an  #
# #  icon: every binding it cannot resolve is a named refusal, every assumption is    #
# #  numbered below and cited at the line that depends on it, and the receipt records #
# #  the refusals as carefully as the successes. A receipt showing only the calls     #
# #  that worked is an advertisement, not a record (section 6.2).                     #
# #####################################################################################
#
# THE ASSUMPTIONS. Each is a thing the first run will confirm or destroy. They are cited
# as "A<n>" at the code that rests on them.
#
#   A1  A `-run=pythonscript` commandlet has an editor world we may spawn actors into.
#       If it does not, everything below the mesh load is unreachable and the fix is a
#       different capture strategy (an offscreen world, or UMG/thumbnail rendering).
#   A2  `unreal.SceneCaptureComponent2D` with ORTHO projection + ShowOnlyActors renders a
#       single actor cleanly, and `capture_scene()` is synchronous enough that the render
#       target holds the frame on the next line.
#   A3  `/Game/LevelPrototyping/Materials/M_FlatCol` is an UNLIT constant-colour material
#       whose colour can be forced white. NOBODY HAS READ ITS PARAMETERS. If it is lit, or
#       has no colour parameter, the render is not a flat mask and section 3.3 is wrong.
#   A4  ShowFlags on a capture component are settable from Python by the names used below
#       (`lighting`, `temporal_aa`, `anti_aliasing`, `post_processing`). Several of these
#       are properties on `ShowFlags`-like structs in C++ and may not be exposed at all.
#   A5  `flip_x` can be done with a negative actor scale. Winding/normals invert, which is
#       harmless for a flat unlit mask and would NOT be harmless for a lit render.
#   A6  A PNG decoder is importable inside the editor's Python (PIL, else numpy + the
#       engine's own readback). If neither exists, the supersampled render is preserved
#       on disk and the run fails with POSTPROCESS_UNAVAILABLE - it does not pretend.
#   A7  The mesh bounds returned by `get_bounds()` are LOCAL and in unreal units, and the
#       pivot may be anywhere (muzzle, grip, origin). The framing math only uses extents,
#       so a strange pivot shifts the weapon off-centre WITHOUT changing its size - which
#       is exactly what the first render will show if A7's second half is wrong.
#
# Headless (the crew's default):
#   UnrealEditor-Cmd.exe <repo>\Breachpoint.uproject ^
#       -run=pythonscript -script="<repo>\Tools\render_weapons\render_weapons.py" ^
#       -stdout -unattended -nosplash -nop4 -NoLiveCoding
# The wrapper Tools/render_weapons/render-weapons.ps1 does exactly this, plus engine
# resolution, the plugin check, the R21 editor guard and logging. USE THE WRAPPER: the raw
# form bypasses the guard.
#
# Exit codes: 0 rendered · 1 refused / failed / contract violation · 3 blocked (bad env).
# =====================================================================================
"""Execute the weapon silhouette render plan. SPIKE - unverified against a real editor."""

import argparse
import datetime
import json
import os
import shlex
import sys
import traceback

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import render_plan  # noqa: E402  (same directory; see sys.path line above)

try:
    import unreal
except ImportError:  # pragma: no cover - the whole point of the message
    sys.stderr.write(
        "BLOCKED: render_weapons.py must run inside Unreal (it imports `unreal`).\n"
        "  Headless: UnrealEditor-Cmd Breachpoint.uproject -run=pythonscript "
        "-script=\"Tools/render_weapons/render_weapons.py\" -stdout -unattended -nosplash\n"
        "  Or use the wrapper: Tools\\render_weapons\\render-weapons.ps1\n"
        "  To check the PLAN without an editor, run render_plan.py - it is plain CPython and\n"
        "  needs nothing installed:  python Tools/render_weapons/render_plan.py --verbose\n"
        "  To exercise the framing math without an editor: selftest_no_editor.py\n")
    sys.exit(3)


TAG = "[BR-rendwpn]"


def log(msg):
    unreal.log("%s %s" % (TAG, msg))


def warn(msg):
    unreal.log_warning("%s %s" % (TAG, msg))


def err(msg):
    unreal.log_error("%s %s" % (TAG, msg))


class Refused(Exception):
    """A condition that must stop the run. Written to be read by someone who was not here."""


# =====================================================================================
# arguments
# =====================================================================================

def parse_args():
    """Args reach a -run=pythonscript script inconsistently across launch shapes, so we
    accept them from sys.argv AND from BR_RENDERWPN_ARGS (what the PS wrapper sets) - the
    same idiom as BR_GENINPUT_ARGS and BR_BLOCKOUT_ARGS."""
    ap = argparse.ArgumentParser(prog="render_weapons.py")
    ap.add_argument("--dry-run", action="store_true",
                    help="load, frame and print; render nothing, write no PNG")
    ap.add_argument("--allow-interactive", action="store_true",
                    help="run inside an interactive editor anyway (R21 - say why in the Log)")
    ap.add_argument("--out-dir", default=None)
    ap.add_argument("--receipt-dir", default=None)
    argv = [a for a in sys.argv[1:] if not a.startswith("-run=")]
    env_args = os.environ.get("BR_RENDERWPN_ARGS", "").strip()
    if env_args:
        argv.extend(shlex.split(env_args))
    args, unknown = ap.parse_known_args(argv)
    if unknown:
        log("ignoring unrecognised args (engine flags): %s" % " ".join(unknown))
    return args


def repo_root():
    return os.path.normpath(unreal.Paths.convert_relative_path_to_full(unreal.Paths.project_dir()))


# =====================================================================================
# R21 / R29.3 / R36 - the editor guard
#
# THE AUTHORITATIVE GUARD IS Get-BRLiveEditorProcesses IN Tools/_BRLadderCommon.ps1, called
# by render-weapons.ps1 exactly as build-input.ps1:180 and rename-r26.ps1:88 call it. R36
# exists precisely because a locally-rewritten, narrower guard is how this goes wrong, so
# this half deliberately does NOT reimplement a process scan.
#
# What it CAN see from the inside, and the ps1 cannot: that this very process is an
# INTERACTIVE editor rather than a commandlet - i.e. somebody pasted the script into the
# Python console of an open editor, which is the one shape the outside guard cannot catch
# because the editor it would refuse to run beside is itself.
# =====================================================================================

def guard_r21(args, receipt):
    is_commandlet = any(a.startswith("-run=") for a in sys.argv)
    receipt.note("R21 guard: argv %s -> %s"
                 % (sys.argv[:4], "commandlet" if is_commandlet else "INTERACTIVE"))
    if is_commandlet or args.allow_interactive:
        if not is_commandlet:
            warn("R21: running inside an interactive editor with --allow-interactive. "
                 "Justify it in the ticket Log.")
        return
    raise Refused(
        "this looks like an INTERACTIVE editor session, not a `-run=pythonscript` commandlet "
        "(no -run= in argv). R29.1 is one editor per project ever, and R36 widened R29.3 to "
        "'an editor session must not overlap anything that takes the project lock' - this "
        "script is exactly that. It writes into Content/UI. Close the editor and run "
        "Tools\\render_weapons\\render-weapons.ps1, which carries the shared process guard. "
        "If you genuinely mean to spike inside a live editor, pass --allow-interactive and "
        "say so in the ticket Log.")


# =====================================================================================
# the receipt (section 6) - written AS THE RUN PROCEEDS, appended per call
#
# "A receipt reconstructed from memory afterwards is not a receipt." Every write is flushed,
# so a run killed halfway leaves a receipt that says where it died.
# =====================================================================================

class Receipt(object):

    def __init__(self, md_path, json_path, plan):
        self.md_path = md_path
        self.json_path = json_path
        self.calls = []
        self.findings = []
        self.weapons = {}
        self.plan = plan
        self.started = datetime.datetime.utcnow().isoformat() + "Z"
        for d in (os.path.dirname(md_path), os.path.dirname(json_path)):
            if d and not os.path.isdir(d):
                os.makedirs(d)
        self.fh = open(md_path, "w", encoding="utf-8")
        self._w("# Weapon silhouette render receipt\n")
        self._w("\n**SPIKE RUN.** The first runs of this pipeline are expected to fail and to "
                "correct section 3.3 / 9.1 of `docs/ui/WEAPON-RENDER-PLAN.md`. Read the "
                "verdict, then read the SPIKE CHECKLIST (section 11) before changing anything.\n")
        self._w("\n- UTC start: `%s`\n" % self.started)
        self._w("- command line: `%s`\n" % " ".join(sys.argv))
        self._w("- BR_RENDERWPN_ARGS: `%s`\n" % os.environ.get("BR_RENDERWPN_ARGS", ""))
        self._w("- plan digest: `%s`\n" % plan["digest"])
        self._w("- `%s` sha256: `%s`\n" % (plan["source_table"], plan["source_table_sha256"]))
        self._w("- plan status: %s\n" % plan["status"])
        self._w("\n## Calls\n\n")

    def _w(self, text):
        self.fh.write(text)
        self.fh.flush()

    def call(self, name, args, result, ok=True):
        """Record one unreal API call - name, arguments, return value. Including failures."""
        rec = {"call": name, "args": args, "result": _short(result), "ok": bool(ok)}
        self.calls.append(rec)
        self._w("- `%s(%s)` -> %s%s\n"
                % (name, args, _short(result), "" if ok else "   **FAILED**"))
        return result

    def note(self, text):
        self.calls.append({"note": text})
        self._w("- _%s_\n" % text)

    def finding(self, severity, code, message):
        self.findings.append({"severity": severity, "code": code, "message": message})
        self._w("- **%s %s** %s\n" % (severity.upper(), code, message))
        (err if severity == "error" else warn)("%s: %s" % (code, message))

    def weapon(self, row, data):
        self.weapons[row] = data
        self._w("\n### %s\n\n" % row)
        for k in sorted(data):
            self._w("- %s: `%s`\n" % (k, data[k]))

    def close(self, verdict, summary):
        self._w("\n## Verdict: %s\n\n%s\n" % (verdict, summary))
        self._w("\n## Rung honesty\n\n"
                "A PASS here means the PNGs exist and match the plan, and the meshes they came "
                "from are the meshes `DT_Weapons.csv` equips. It does **not** mean an icon "
                "appears in the HUD - there is no consumer (plan section 9.3). It does not mean "
                "the framing is *right*; only a human looking at the output can say that.\n")
        self.fh.close()
        body = {
            "schema": "breachpoint.weaponrender.receipt/1",
            "spike": True,
            "started_utc": self.started,
            "ended_utc": datetime.datetime.utcnow().isoformat() + "Z",
            "command_line": sys.argv,
            "verdict": verdict,
            "summary": summary,
            "plan": self.plan,
            "calls": self.calls,
            "findings": self.findings,
            "weapons": self.weapons,
        }
        with open(self.json_path, "w", encoding="utf-8") as fh:
            json.dump(body, fh, indent=2, sort_keys=True)


def _short(value, limit=160):
    text = repr(value)
    return text if len(text) <= limit else text[:limit] + "..."


# =====================================================================================
# editor helpers - every one defensive, because none of these names is verified (A1-A6)
# =====================================================================================

def need(attr_path, why):
    """Resolve `unreal.X.Y` or refuse by name. An unresolvable binding is a REFUSAL, never a
    shrug: a half-configured capture writes a plausible-looking wrong picture."""
    obj = unreal
    for part in attr_path.split("."):
        obj = getattr(obj, part, None)
        if obj is None:
            raise Refused(
                "this editor has no `unreal.%s`, which is needed to %s. The API name was taken "
                "from the UE 5.8 docs and never verified against a running editor (see THIS IS "
                "A SPIKE at the top of this file). Find the real binding, fix it here, and note "
                "the correction in the receipt and in WEAPON-RENDER-PLAN.md section 3.3."
                % (attr_path, why))
    return obj


def load_mesh(soft_path, receipt):
    asset = receipt.call("EditorAssetLibrary.load_asset", soft_path,
                         unreal.EditorAssetLibrary.load_asset(soft_path))
    if asset is None:
        raise Refused("MESH_NOT_FOUND: %s could not be loaded. The plan validated its SHAPE "
                      "with no editor; existence is an editor fact and this is it." % soft_path)
    return asset


def local_half_extent(mesh, receipt):
    """A7: bounds are local and in unreal units. Only the extents are used for framing."""
    bounds = receipt.call("StaticMesh.get_bounds", mesh.get_name(), mesh.get_bounds())
    box = bounds.box_extent  # half-extents
    return (float(box.x), float(box.y), float(box.z)), bounds


def white_unlit_material(receipt):
    """A3: M_FlatCol is assumed to be an unlit constant. NOBODY HAS READ ITS PARAMETERS."""
    base = unreal.EditorAssetLibrary.load_asset(render_plan.UNLIT_MATERIAL)
    receipt.call("EditorAssetLibrary.load_asset", render_plan.UNLIT_MATERIAL, base,
                 ok=base is not None)
    if base is None:
        raise Refused(
            "the unlit override material %s did not load. Section 3.3 named it as the OBVIOUS "
            "CANDIDATE and explicitly marked it unverified. Without a flat unlit white the "
            "render is a shaded picture, not a coverage mask, and the whole output contract "
            "(section 2.2: every pixel #FFFFFF, shape carried by alpha) is void. Find or author "
            "an unlit constant-white material and correct section 3.3."
            % render_plan.UNLIT_MATERIAL)
    mid = unreal.MaterialEditingLibrary.create_material_instance_dynamic(base) \
        if hasattr(unreal.MaterialEditingLibrary, "create_material_instance_dynamic") else None
    if mid is None:
        # Falling back to the base material is honest but weaker: whatever colour the asset
        # carries is what renders. Recorded, not hidden.
        receipt.finding("warn", "MATERIAL_NOT_PARAMETERISED",
                        "could not create a dynamic instance of %s, so its authored colour is "
                        "used as-is. If the render is not pure white, THIS is why."
                        % render_plan.UNLIT_MATERIAL)
        return base
    for param in ("Color", "BaseColor", "Colour", "Tint"):
        try:
            mid.set_vector_parameter_value(param, unreal.LinearColor(1.0, 1.0, 1.0, 1.0))
            receipt.call("MID.set_vector_parameter_value", param, "white")
            break
        except Exception as exc:  # noqa: BLE001 - the parameter name is a guess, A3
            receipt.note("param '%s' not settable (%s)" % (param, exc))
    return mid


# =====================================================================================
# the render - A1, A2, A4, A5
# =====================================================================================

def render_one(w, half_extent, uu_per_px, material, out_dir, args, receipt):
    """Spawn, override, frame, capture, export. Returns the supersampled PNG path."""
    frame = render_plan.frame_row(w, half_extent, uu_per_px)
    ss = render_plan.SUPERSAMPLE
    width_px, height_px = render_plan.CANVAS_W * ss, render_plan.CANVAS_H * ss

    get_subsystem = need("get_editor_subsystem", "spawn the mesh to be photographed")
    actor_ss = get_subsystem(need("EditorActorSubsystem", "spawn actors"))  # A1
    if actor_ss is None:
        raise Refused("no EditorActorSubsystem in this session (A1). A `-run=pythonscript` "
                      "commandlet may have no editor world at all - if so this capture strategy "
                      "is wrong and section 3.3 needs replacing, not tweaking.")

    mesh_actor = receipt.call(
        "EditorActorSubsystem.spawn_actor_from_object", w["mesh"],
        actor_ss.spawn_actor_from_object(
            unreal.EditorAssetLibrary.load_asset(w["mesh"]), unreal.Vector(0, 0, 0),
            unreal.Rotator(w["roll_deg"], 0.0, w["yaw_deg"])))
    # UE Rotator is (pitch=Y, yaw=Z, roll=X) in the python constructor's (roll, pitch, yaw)
    # ordering - ANOTHER unverified detail (A7). If the first render is rotated about the
    # wrong axis, suspect this line before you suspect the plan's numbers.
    capture = None
    try:
        mesh_actor.set_actor_label("RenderWeapons_%s" % w["row"])
        if w["flip_x"]:  # A5
            mesh_actor.set_actor_scale3d(unreal.Vector(-1.0, 1.0, 1.0))
        for i, _slot in enumerate(mesh_actor.static_mesh_component.get_materials()):
            mesh_actor.static_mesh_component.set_material(i, material)  # section 3.3
        receipt.call("StaticMeshComponent.set_material", "all slots -> unlit white", True)

        # ---- the camera. IDENTICAL FOR EVERY WEAPON except the plan's per-row corrections.
        capture = actor_ss.spawn_actor_from_class(
            unreal.SceneCapture2D, unreal.Vector(0, -5000.0, 0),
            unreal.Rotator(0.0, 0.0, 90.0))  # looking +Y, i.e. camera forward (0,-1,0) inverted
        comp = capture.capture_component2d
        need("RenderingLibrary", "allocate the render target and export it")  # A2
        rt = unreal.RenderingLibrary.create_render_target2d(width_px, height_px) \
            if hasattr(unreal.RenderingLibrary, "create_render_target2d") else None
        if rt is None:
            raise Refused("could not create a %dx%d render target (A2). Without one there is "
                          "nowhere for the frame to land." % (width_px, height_px))
        receipt.call("RenderingLibrary.create_render_target2d", (width_px, height_px), rt)

        comp.set_editor_property("projection_type", unreal.CameraProjectionMode.ORTHOGRAPHIC)
        comp.set_editor_property("ortho_width", frame["ortho_width_uu"])
        comp.set_editor_property("texture_target", rt)
        comp.set_editor_property("capture_source",
                                 unreal.SceneCaptureSource.SCS_FINAL_COLOR_LDR)
        comp.set_editor_property("show_only_actors", [mesh_actor])
        comp.set_editor_property("primitive_render_mode",
                                 unreal.SceneCapturePrimitiveRenderMode.PRM_USE_SHOW_ONLY_LIST)
        receipt.call("SceneCaptureComponent2D config",
                     {"ortho_width": frame["ortho_width_uu"], "res": [width_px, height_px]}, "set")

        # ---- A4: no lights, no post, and TAA explicitly OFF. TAA is temporal and
        # non-deterministic on a single frame; it would produce different bytes on identical
        # re-runs, which destroys the receipt's only diffable artifact (section 8.4).
        for flag, value in (("lighting", False), ("temporal_aa", False),
                            ("anti_aliasing", False), ("post_processing", False),
                            ("atmosphere", False), ("fog", False), ("motion_blur", False)):
            try:
                comp.show_flag_settings = comp.show_flag_settings  # touch, keeps 5.x happy
                setattr(comp.show_flags, flag, value)
                receipt.call("ShowFlags.%s" % flag, value, "set")
            except Exception as exc:  # noqa: BLE001 - A4, these names are guesses
                receipt.finding("warn", "SHOWFLAG_UNSETTABLE",
                                "could not set ShowFlags.%s (%s). If the render is lit, or "
                                "smeared by TAA, THIS is why - and section 3.3's flag list is "
                                "wrong." % (flag, exc))
        unreal.SystemLibrary.execute_console_command(None, "r.DefaultFeature.AntiAliasing 0")
        receipt.call("execute_console_command", "r.DefaultFeature.AntiAliasing 0", "issued")

        if args.dry_run:
            receipt.note("--dry-run: framed but not captured, nothing written")
            return None

        receipt.call("SceneCaptureComponent2D.capture_scene", w["row"], comp.capture_scene())
        raw_name = "%s_ss%dx.png" % (w["out"], render_plan.SUPERSAMPLE)
        receipt.call("RenderingLibrary.export_render_target", (out_dir, raw_name),
                     unreal.RenderingLibrary.export_render_target(
                         capture.get_world(), rt, out_dir, raw_name))
        return os.path.join(out_dir, raw_name)
    finally:
        # Idempotency and hygiene: the level must not accumulate a pile of photographed guns.
        for a in (capture, mesh_actor):
            if a is not None:
                try:
                    actor_ss.destroy_actor(a)
                except Exception as exc:  # noqa: BLE001
                    receipt.finding("warn", "ACTOR_NOT_DESTROYED",
                                    "left %r in the level (%s). Do NOT save the level." % (a, exc))


# =====================================================================================
# post-processing - section 7.1, threshold THEN downsample
# =====================================================================================

def postprocess(raw_png, out_png, receipt):
    """768x256 white-on-black -> 192x64 RGBA, RGB forced #FFFFFF everywhere, shape in alpha.

    Order matters and is not a preference: thresholding AFTER the downsample gives a jagged
    edge; downsampling AFTER the threshold gives a hard silhouette with clean coverage
    anti-aliasing, which is what "solid silhouette" means in ICON-CONSTRUCTION-SPEC.md.
    """
    try:  # A6
        from PIL import Image
    except ImportError:
        receipt.finding("error", "POSTPROCESS_UNAVAILABLE",
                        "no PIL in this editor's Python, so the supersampled render at %s was "
                        "left as-is and NO icon was produced. The raw frame is preserved on "
                        "purpose - look at it, it answers most of the SPIKE CHECKLIST on its "
                        "own." % raw_png)
        return None

    img = Image.open(raw_png).convert("L")
    ss = render_plan.SUPERSAMPLE
    mask = img.point(lambda v: 255 if v > 127 else 0)          # threshold at supersampled res
    alpha = mask.resize((render_plan.CANVAS_W, render_plan.CANVAS_H), Image.BOX)  # box downsample
    white = Image.new("L", alpha.size, 255)
    # RGB is white even under zero alpha: a PNG with black RGB under transparent pixels bleeds
    # dark fringes when a bilinear sampler averages across the edge (section 2.2).
    Image.merge("RGBA", (white, white, white, alpha)).save(out_png, "PNG")
    receipt.call("postprocess", {"src": raw_png, "supersample": ss}, out_png)
    return out_png


# =====================================================================================
# main
# =====================================================================================

def main():
    args = parse_args()
    root = repo_root()
    stamp = datetime.datetime.utcnow().strftime("%Y%m%dT%H%M%SZ")
    out_dir = args.out_dir or os.path.join(root, "Tools", "render_weapons", "out")
    receipt_dir = args.receipt_dir or os.path.join(root, "Tools", "render_weapons", "receipts")
    json_dir = os.path.join(root, "Saved", "WeaponRender")

    try:
        plan = render_plan.build_plan(table_path=os.path.join(root, "Content", "Data",
                                                             "DT_Weapons.csv"))
    except render_plan.PlanError as exc:
        err("BLOCKED: %s" % exc)
        return 3

    receipt = Receipt(os.path.join(receipt_dir, "render-%s.md" % stamp),
                      os.path.join(json_dir, "render-%s-running.json" % stamp), plan)
    verdict, summary = "FAIL", "the run did not reach a verdict"
    try:
        guard_r21(args, receipt)

        for fd in plan["findings"]:
            receipt.finding(fd["severity"], fd["code"], fd["message"])
        if plan["errors"]:
            raise Refused("the plan does not validate (%d error(s) above). Nothing is rendered, "
                          "nothing is written. Fix Tools/render_weapons/render_plan.py."
                          % plan["errors"])

        if not os.path.isdir(out_dir):
            os.makedirs(out_dir)

        # ---- phase 1: load every mesh and read its bounds BEFORE rendering anything.
        # The shared uu_per_px is derived from the largest weapon, so no weapon can be framed
        # until all of them have been measured. A partial set would silently rescale the
        # family (section 3.2) - which is the defect that is invisible one icon at a time.
        measured = []
        for w in plan["weapons"]:
            mesh = load_mesh(w["mesh"], receipt)
            half, bounds = local_half_extent(mesh, receipt)
            width_uu, height_uu = render_plan.project_extent(half, w["yaw_deg"], w["roll_deg"])
            measured.append((w, half, width_uu, height_uu))
            receipt.note("%s local half-extent %s -> projected %.1f x %.1f uu"
                         % (w["row"], half, width_uu, height_uu))

        shared, driver = render_plan.derive_uu_per_px(
            [(w["row"], wu, hu) for w, _h, wu, hu in measured])
        receipt.note("SHARED uu_per_px = %.6f, derived from '%s' (the largest projected long "
                     "axis, filling %.0f%% of the %dpx safe box). Every weapon uses this same "
                     "scalar: a magnum reads smaller than a launcher ON PURPOSE."
                     % (shared, driver, render_plan.FILL_FRACTION * 100, render_plan.SAFE_W))

        material = white_unlit_material(receipt)

        # ---- phase 2: render, in table order, with the one shared scalar.
        produced = []
        for w, half, width_uu, height_uu in measured:
            frame = render_plan.frame_row(w, half, shared)
            if frame["fill_fraction_h"] > 1.0:
                receipt.finding("error", "VERTICAL_OVERFLOW",
                                "%s is %.1f px tall at the shared scale but the safe box is %d. "
                                "The family scale is set by WIDTH (section 3.2) and this weapon "
                                "does not fit vertically - either the orientation guess is wrong "
                                "(most likely) or the rule needs a height term."
                                % (w["row"], frame["projected_px"][1], render_plan.SAFE_H))
            raw = render_one(w, half, shared, material, out_dir, args, receipt)
            final = None
            if raw and os.path.isfile(raw):
                final = postprocess(raw, os.path.join(out_dir, "%s.png" % w["out"]), receipt)
            elif not args.dry_run:
                receipt.finding("error", "RENDER_NO_OUTPUT",
                                "%s: export_render_target produced no file at %s."
                                % (w["row"], raw))
            data = dict(frame)
            data.update({"mesh": w["mesh"], "mesh_soft_path_asserted_against": plan["source_table"],
                         "local_half_extent_uu": list(half), "yaw_deg": w["yaw_deg"],
                         "roll_deg": w["roll_deg"], "flip_x": w["flip_x"],
                         "scale_override": w["scale_override"],
                         "raw_png": raw, "png": final,
                         "png_sha256": render_plan.digest_file(final) if final else None,
                         "png_bytes": os.path.getsize(final) if final else None,
                         "min_feature_check": "NOT IMPLEMENTED IN THE SPIKE (section 7.2)",
                         "hole_count": "NOT IMPLEMENTED IN THE SPIKE (section 7.3)"})
            receipt.weapon(w["row"], data)
            if final:
                produced.append(final)

        errors = [f for f in receipt.findings if f["severity"] == "error"]
        if args.dry_run:
            verdict, summary = "BLOCKED", ("--dry-run: framed under the editor, wrote nothing. "
                                           "The framing numbers above are the reviewable part.")
        elif errors or len(produced) != len(plan["weapons"]):
            verdict, summary = "FAIL", (
                "%d/%d PNGs produced, %d error finding(s). A partial run is FAIL, not PASS with "
                "notes (section 6.2). EXPECTED on the first runs - work the SPIKE CHECKLIST "
                "(WEAPON-RENDER-PLAN.md section 11) and correct section 3.3."
                % (len(produced), len(plan["weapons"]), len(errors)))
        else:
            verdict, summary = "PASS", (
                "%d PNGs written to %s at the shared scale %.6f uu/px (driver: %s). NOT YET "
                "CHECKED BY ANYTHING: whether the orientation guesses were right, whether the "
                "override actually read as flat white, the 2px minimum-feature test (section "
                "7.2) and the hole count (7.3) - the spike implements none of those. A human "
                "must look at the output before any of it is committed."
                % (len(produced), out_dir, shared, driver))
    except Refused as exc:
        err("REFUSED: %s" % exc)
        verdict, summary = "BLOCKED", "REFUSED: %s" % exc
    except Exception as exc:  # noqa: BLE001 - a half-written icon must not be reported clean
        err("FAILED: %s" % exc)
        err(traceback.format_exc())
        verdict, summary = "FAIL", "unhandled error: %s\n\n```\n%s\n```" % (exc, traceback.format_exc())

    receipt.json_path = os.path.join(json_dir, "render-%s-%s.json" % (stamp, verdict.lower()))
    receipt.close(verdict, summary)
    log("verdict %s - receipt %s" % (verdict, receipt.md_path))
    log(summary)
    return {"PASS": 0, "FAIL": 1, "BLOCKED": 3}[verdict]


if __name__ == "__main__":
    sys.exit(main())
