using UnrealBuildTool;

public class BreachpointNext : ModuleRules
{
	public BreachpointNext(ReadOnlyTargetRules Target) : base(Target)
	{
		PCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs;

		PublicDependencyModuleNames.AddRange(new string[]
		{
			"Core",
			"CoreUObject",
			"Engine",
			"InputCore",
			"EnhancedInput",
			"GameplayAbilities",
			"GameplayTags",
			"GameplayTasks",
			"NetCore",
			// ABNBotController: AAIController + perception live in AIModule; the StateTree pair
			// carries UStateTreeAIComponent (GameplayStateTree) atop the runtime (StateTreeModule).
			"AIModule",
			// The bot move tasks diagnose their own failures against the navmesh
			// (UNavigationSystemV1::ProjectPointToNavigation), which lives in its own module.
			"NavigationSystem",
			"StateTreeModule",
			"GameplayStateTreeModule",
			// FBNImpactEffectRow carries a TEnumAsByte<EPhysicalSurface>; the enum's reflection
			// constructor lives here, and the editor target links modularly.
			"PhysicsCore",
			// UBNAssetSettings derives UDeveloperSettings, which lives in its own module.
			"DeveloperSettings"
		});

		// PRIVATE: AbilitySystem/BNGameplayCues.cpp spawns cue FX through
		// UNiagaraFunctionLibrary, but its header types the assets as TSoftObjectPtr<UFXSystemAsset>
		// — the Engine-module base of both FX systems — so no public header names a Niagara type.
		PrivateDependencyModuleNames.Add("Niagara");

		// Every .cpp in this module includes its own header module-root-relative
		// ("Match/BNPlayerController.h"). The module has no Public/Private split, so
		// without this the root is not on the include path and NOTHING here compiles.
		// Same line the old module carries; it was missing since the module was created.
		PublicIncludePaths.Add("BreachpointNext");

		// EDITOR ONLY — AI/BNBotAuthoring.cpp, whole file behind #if WITH_EDITOR. It BUILDS
		// /Game/BN/AI/ST_BNBot and /Game/BN/Data/DT_BNBotAmbitions in code rather than by hand,
		// because a StateTree's graph has no scripting surface at all (UStateTreeEditorData's
		// SubTrees and UStateTreeState's Children are bare Instanced UPROPERTYs — neither Python
		// nor the MCP ObjectTools can read or write them, and UStateTreeEditingSubsystem::
		// CompileStateTree is a plain static C++ function, not a UFUNCTION). C++ is the ONLY
		// path, so this is the project's "generated by a committed script" rule kept, in the one
		// language that can. Never in Game or Server: bBuildEditor gates the whole dependency.
		if (Target.bBuildEditor)
		{
			PrivateDependencyModuleNames.AddRange(new string[]
			{
				"UnrealEd",
				"AssetTools",
				"StateTreeEditorModule",
				// FStateTreeCompilerLog's message struct embeds an
				// FPropertyBindingBindableStructDescriptor, whose virtual destructor is exported
				// from here. Without this the module compiles clean and fails at LINK — the
				// destructor is instantiated in OUR translation unit by TArray teardown.
				"PropertyBindingUtils"
			});
		}
	}
}
