#include "OSLogCategories.h"

DEFINE_LOG_CATEGORY(LogOSAttack);
DEFINE_LOG_CATEGORY(LogOSCombat);
DEFINE_LOG_CATEGORY(LogOSChooser);
DEFINE_LOG_CATEGORY(LogOSDebug);
DEFINE_LOG_CATEGORY(LogOSGASAttackTrace);
DEFINE_LOG_CATEGORY(LogOSGASGrab);
DEFINE_LOG_CATEGORY(LogOSGASGrabReaction);
DEFINE_LOG_CATEGORY(LogOSGASHitReact);
DEFINE_LOG_CATEGORY(LogOSMantle);
DEFINE_LOG_CATEGORY(LogOSMovement);
DEFINE_LOG_CATEGORY(LogOSTrackMotionWarpTarget);
DEFINE_LOG_CATEGORY(LogOSDomination);
DEFINE_LOG_CATEGORY(LogOSSpawn);
DEFINE_LOG_CATEGORY(HookMapSelect);
