"""
BP82 — reparent BP_FPST_BaseWeapon onto ABPWeaponBase.

WHY THIS SCRIPT EXISTS RATHER THAN A HAND EDIT
    Law 7: asset changes are generated by committed scripts, never hand-placed. The reparent is
    one property, but doing it by hand leaves no record of what was changed or what it was checked
    against. This does, and it re-runs clean.

WHAT WENT WRONG WITHOUT IT
    AMyCharacter::CreateWeapons resolves StartupWeaponClasses with
    TryLoadClass<ABPWeaponBase>() (MyCharacter.cpp:346). That returns null for any class which is
    not a child of ABPWeaponBase, and MyCharacter logs the null as "failed to load" — which reads
    like a missing asset and is not one. The engine says the real thing one line earlier:

        LogUObjectGlobals: Warning: BlueprintGeneratedClass ...BP_FPST_Weapon_Pistol_C
        is not a child class of Class /Script/Breachpoint.BPWeaponBase

    ABPWeaponBase.h:9-10 names the intended shape: BP_FPST_BaseWeapon reparents onto it and the
    four children inherit. That reparent was never performed; the base still derives from AActor.

RUN IT (editor MUST be closed — a running editor holds these assets and will clobber the write):
    "<UE>/Engine/Binaries/Win64/UnrealEditor-Cmd.exe" <project>.uproject \
        -run=pythonscript -script="mcp-bp/reparent_weapon_base.py" -unattended -nosplash

Exit code 0 = every assertion below held. Non-zero = nothing is claimed.
"""

import sys

import unreal

BASE_PATH = "/Game/FPSTemplate/Blueprints/Weapons/BP_FPST_BaseWeapon"
NEW_PARENT_PATH = "/Script/Breachpoint.BPWeaponBase"

CHILD_PATHS = [
    "/Game/FPSTemplate/Blueprints/Weapons/BP_FPST_Weapon_Pistol",
    "/Game/FPSTemplate/Blueprints/Weapons/BP_FPST_Weapon_Rifle",
    "/Game/FPSTemplate/Blueprints/Weapons/BP_FPST_Weapon_Shotgun",
    "/Game/FPSTemplate/Blueprints/Weapons/BP_FPST_Weapon_Knife",
]

failures = []


def log(msg):
    unreal.log("[reparent_weapon_base] {}".format(msg))


def fail(msg):
    unreal.log_error("[reparent_weapon_base] FAIL: {}".format(msg))
    failures.append(msg)


def class_name(cls):
    return cls.get_path_name() if cls else "<none>"


def derives_from(blueprint, parent_class):
    """Two Python-API dead ends got us here, both worth recording so nobody retries them:

        UBlueprint.get_editor_property('parent_class')  -> "Failed to find property 'parent_class'"
        BlueprintGeneratedClass.is_child_of(...)        -> AttributeError, not bound in Python

    So ask the class-default object instead. isinstance against the generated `unreal.BPWeaponBase`
    binding answers the same question TryLoadClass<ABPWeaponBase>() asks at runtime — an
    is-a test against the real C++ type — rather than a proxy for it.
    """
    gen = blueprint.generated_class()
    if gen is None:
        return False
    try:
        cdo = unreal.get_default_object(gen)
    except Exception as exc:  # noqa: BLE001 - reported, never swallowed
        fail("could not get CDO for {}: {}".format(class_name(gen), exc))
        return False
    return isinstance(cdo, unreal.BPWeaponBase)


def main():
    # If the module did not compile, every check below would report a confusing false rather
    # than the real cause. Say it plainly instead.
    if not hasattr(unreal, "BPWeaponBase"):
        fail("unreal.BPWeaponBase binding is absent — the Breachpoint module did not load")
        return

    new_parent = unreal.load_object(None, NEW_PARENT_PATH)
    if new_parent is None:
        fail("could not load {} — is the module compiled?".format(NEW_PARENT_PATH))
        return

    base_bp = unreal.load_asset(BASE_PATH)
    if base_bp is None:
        fail("could not load {}".format(BASE_PATH))
        return

    log("BP_FPST_BaseWeapon generated class : {}".format(class_name(base_bp.generated_class())))
    log("derives from ABPWeaponBase BEFORE  : {}".format(derives_from(base_bp, new_parent)))

    if derives_from(base_bp, new_parent):
        log("already parented to ABPWeaponBase — nothing to change")
    else:
        unreal.BlueprintEditorLibrary.reparent_blueprint(base_bp, new_parent)
        unreal.BlueprintEditorLibrary.compile_blueprint(base_bp)
        if not unreal.EditorAssetLibrary.save_asset(BASE_PATH, only_if_is_dirty=False):
            fail("save_asset returned False for {}".format(BASE_PATH))

    log("derives from ABPWeaponBase AFTER   : {}".format(derives_from(base_bp, new_parent)))
    if not derives_from(base_bp, new_parent):
        fail("reparent did not stick on BP_FPST_BaseWeapon")
        return

    # The children inherit, but each generated class must be recompiled and re-saved before
    # TryLoadClass sees the new ancestry on a cold load. Assert it per child rather than assume.
    for path in CHILD_PATHS:
        child_bp = unreal.load_asset(path)
        if child_bp is None:
            fail("could not load child {}".format(path))
            continue

        unreal.BlueprintEditorLibrary.compile_blueprint(child_bp)
        if not unreal.EditorAssetLibrary.save_asset(path, only_if_is_dirty=False):
            fail("save_asset returned False for {}".format(path))

        if child_bp.generated_class() is None:
            fail("{} has no generated class after compile".format(path))
            continue

        # This is the exact question TryLoadClass<ABPWeaponBase>() asks at runtime.
        if derives_from(child_bp, new_parent):
            log("OK  {} -> is child of ABPWeaponBase".format(path.rsplit("/", 1)[-1]))
        else:
            fail("{} is STILL not a child of ABPWeaponBase".format(path))


main()

if failures:
    unreal.log_error("[reparent_weapon_base] {} FAILURE(S) — nothing is claimed".format(len(failures)))
    sys.exit(1)

log("all assertions held: base reparented, 4 children verified as children of ABPWeaponBase")
sys.exit(0)
