"""
BP82 — make BP_FPSCharacter's component tree 1:1 with BP_FPST_Character.

WHY THIS SCRIPT EXISTS RATHER THAN A HAND EDIT
    Law 7: asset changes are generated by committed scripts, never hand-placed. Same reason as
    reparent_weapon_base.py — a hand edit leaves no record of what was changed or what it was
    checked against. This does, it re-runs clean, and it is idempotent.

WHY IT COPIES INSTEAD OF HARDCODING
    Every value below is READ OFF BP_FPST_Character at run time and written to BP_FPSCharacter.
    Nothing is a literal in this file, so the script cannot drift from the reference: if the
    template asset changes, a re-run re-syncs. That is what "1:1" means here.

WHAT WAS ACTUALLY WRONG (measured 11 Aug 2026, not assumed)
    The ticket recorded "the mesh is unassigned and it needs a human". THAT IS STALE. The mesh
    (SKM_Manny_Y) and Anim Class (ABP_Mannequin_Base_C) are already set on BP_FPSCharacter. What
    is actually wrong is the camera stack and four transforms:

      component              BP_FPSCharacter had            BP_FPST_Character has
      Mesh                   loc(0,0,-90) yaw -90           loc(0,0,-89) yaw 270
      FPSCamera              loc(0,0,170) yaw 90            loc(10,5,0) yaw 90 roll -90
      SpringArm  -> rename   loc(0,0,0) arm 300 offset 0    CameraBoom loc(0,0,8.492264) arm 340
                                                            socket offset (0,60,60), pawn-ctrl rot
      Camera     -> rename   loc(0,0,80), no pawn-ctrl rot  FollowCamera loc(0,0,0)
      Arrow_MeleeTraceStart  loc(0,0,0)                     loc(0,0,50.370297)

    The two renames matter beyond cosmetics. AMyCharacter resolves its cached component pointers
    BY NAME first (MyCharacter.cpp, PostInitializeComponents): it looks for "CameraBoom" and
    "FollowCamera". With them named "SpringArm" and "Camera", the name lookup missed and only the
    class fallback saved the spring arm; FollowCamera was never found at all. Those names were
    forced in the first place because a Blueprint cannot name an SCS component after a property
    its parent C++ class declares — which is why the C++ side now prefixes its own Cached*.

    The hierarchy needs NO reparenting: Camera is already under SpringArm, so renaming the pair
    to FollowCamera/CameraBoom produces the reference shape as-is.

RUN IT (editor MUST be closed — a running editor holds these assets and will clobber the write):
    "<UE>/Engine/Binaries/Win64/UnrealEditor-Cmd.exe" <project>.uproject \
        -run=pythonscript -script="mcp-bp/sync_character_components.py" -unattended -nosplash

    Then read the SYNC| lines out of Saved/Logs/Breachpoint.log.

Exit code 0 = every assertion below held. Non-zero = nothing is claimed.

NOTE ON sys.exit: do NOT call it. Raising SystemExit out of a -run=pythonscript commandlet
crashes UE inside FPythonScriptPlugin::ShutdownPython (EXCEPTION_ACCESS_VIOLATION) AFTER the
commandlet has already reported success — a fatal error that means nothing. Set FAILURES instead.
"""

import unreal

L = unreal.SubobjectDataBlueprintFunctionLibrary

SOURCE = '/Game/FPSTemplate/Blueprints/Characters/BP_FPST_Character'
TARGET = '/Game/Characters/BP_FPSCharacter'

# target's current name -> the reference name it must take
RENAMES = {
    'SpringArm': 'CameraBoom',
    'Camera': 'FollowCamera',
}

# Which properties to copy, per component class. Scene transform for everything that has one,
# plus the class-specific settings that make the camera stack behave like the template's.
SCENE_PROPS = ['relative_location', 'relative_rotation', 'relative_scale3d']
CLASS_PROPS = [
    (unreal.SpringArmComponent, ['target_arm_length', 'socket_offset', 'target_offset',
                                 'use_pawn_control_rotation', 'b_enable_camera_lag',
                                 'b_enable_camera_rotation_lag', 'b_do_collision_test']),
    (unreal.CameraComponent, ['field_of_view', 'use_pawn_control_rotation']),
    (unreal.SkeletalMeshComponent, ['skeletal_mesh_asset', 'anim_class', 'owner_no_see',
                                    'visible_in_scene_capture_only', 'cast_shadow']),
]

FAILURES = []
CHANGES = []


def log(msg):
    unreal.log("SYNC| " + str(msg))


def fail(msg):
    FAILURES.append(str(msg))
    unreal.log_error("SYNC| FAIL: " + str(msg))


def components_by_name(blueprint):
    """name -> (handle, template object) for every subobject on a Blueprint."""
    subsystem = unreal.get_engine_subsystem(unreal.SubobjectDataSubsystem)
    out = {}
    for handle in subsystem.k2_gather_subobject_data_for_blueprint(blueprint):
        data = L.get_data(handle)
        try:
            name = str(L.get_variable_name(data))
        except Exception:
            continue
        if not name or name == 'None':
            continue
        obj = L.get_associated_object(data)
        if obj is None:
            continue
        out.setdefault(name, (handle, obj))
    return out


def same(a, b):
    """
    Value equality that works for UE structs.

    DO NOT compare with str(). A struct's repr embeds its memory ADDRESS —
    "<Struct 'Vector' (0x000002C4B142C980) {x: 0.0, y: 0.0, z: -89.0}>" — so two structs holding
    identical values never compare equal as text. The first version of this script did exactly
    that and reported 44 write failures against writes that had all succeeded.
    """
    try:
        return bool(a == b)
    except Exception:
        return str(a) == str(b)


def describe(value):
    """Struct repr without the address, so the change log is readable and diffable."""
    text = str(value)
    if '{' in text and '}' in text:
        return text[text.index('{'):text.rindex('}') + 1]
    return text


def copy_prop(src_obj, dst_obj, prop, label):
    """Copy one property, reporting only when the value actually moved."""
    try:
        want = src_obj.get_editor_property(prop)
    except Exception:
        return  # reference does not expose it; nothing to copy
    try:
        have = dst_obj.get_editor_property(prop)
    except Exception as exc:
        fail("%s: cannot READ '%s' on target (%s)" % (label, prop, exc))
        return
    if same(have, want):
        return
    try:
        dst_obj.set_editor_property(prop, want)
    except Exception as exc:
        fail("%s: cannot WRITE '%s' (%s)" % (label, prop, exc))
        return
    got = dst_obj.get_editor_property(prop)
    if not same(got, want):
        fail("%s: wrote '%s' but it did not take (want %s, got %s)"
             % (label, prop, describe(want), describe(got)))
        return
    CHANGES.append("%s.%s: %s -> %s" % (label, prop, describe(have), describe(want)))
    log("  set %s.%s  %s -> %s" % (label, prop, describe(have), describe(want)))


def main():
    source_bp = unreal.load_asset(SOURCE)
    target_bp = unreal.load_asset(TARGET)
    if not source_bp:
        fail("reference Blueprint %s did not load" % SOURCE)
        return
    if not target_bp:
        fail("target Blueprint %s did not load" % TARGET)
        return

    # Guard: only ever touch a Blueprint that really is an AMyCharacter child. Note that
    # 'parent_class' is NOT a Python-exposed property on Blueprint (it raises), so the check
    # goes through the generated class's default object instead.
    try:
        target_cdo = unreal.get_default_object(target_bp.generated_class())
    except Exception as exc:
        fail("cannot reach the target's CDO to verify its parent (%s)" % exc)
        return
    log("target CDO = %s" % (target_cdo.get_class().get_name() if target_cdo else None))
    if not isinstance(target_cdo, unreal.MyCharacter):
        fail("target is not an AMyCharacter child (CDO is %s) — refusing to touch it"
             % (target_cdo.get_class().get_name() if target_cdo else None))
        return

    subsystem = unreal.get_engine_subsystem(unreal.SubobjectDataSubsystem)

    # --- 1. renames, so name-based resolution in C++ finds these at all -------------------
    target_components = components_by_name(target_bp)
    for old_name, new_name in RENAMES.items():
        if new_name in target_components:
            log("rename skipped: '%s' already exists" % new_name)
            continue
        if old_name not in target_components:
            log("rename skipped: no '%s' on target" % old_name)
            continue
        handle = target_components[old_name][0]
        try:
            subsystem.rename_subobject(handle, unreal.Text(new_name))
        except Exception as exc:
            fail("rename %s -> %s failed (%s)" % (old_name, new_name, exc))
            continue
        CHANGES.append("rename %s -> %s" % (old_name, new_name))
        log("renamed %s -> %s" % (old_name, new_name))

    # re-gather: handles and names are stale after a rename
    target_components = components_by_name(target_bp)
    source_components = components_by_name(source_bp)

    # --- 2. copy transforms and class settings from the reference -------------------------
    for name, (_handle, src_obj) in sorted(source_components.items()):
        if name not in target_components:
            log("NOT ON TARGET, skipped: %s (%s)" % (name, src_obj.get_class().get_name()))
            continue
        dst_obj = target_components[name][1]
        if src_obj.get_class() != dst_obj.get_class():
            log("class differs, skipped: %s (%s vs %s)"
                % (name, src_obj.get_class().get_name(), dst_obj.get_class().get_name()))
            continue

        if isinstance(src_obj, unreal.SceneComponent):
            for prop in SCENE_PROPS:
                copy_prop(src_obj, dst_obj, prop, name)
        for cls, props in CLASS_PROPS:
            if isinstance(src_obj, cls):
                for prop in props:
                    copy_prop(src_obj, dst_obj, prop, name)

    # --- 3. compile + save ----------------------------------------------------------------
    try:
        unreal.BlueprintEditorLibrary.compile_blueprint(target_bp)
        log("compiled")
    except Exception as exc:
        fail("compile failed (%s)" % exc)
    if not unreal.EditorAssetLibrary.save_loaded_asset(target_bp):
        fail("save_loaded_asset returned False for %s" % TARGET)
    else:
        log("saved %s" % TARGET)

    # --- 4. assert the result, by re-reading ----------------------------------------------
    final = components_by_name(target_bp)
    for required in ('Mesh', 'FPSCamera', 'CameraBoom', 'FollowCamera', 'Arrow_MeleeTraceStart'):
        if required not in final:
            fail("after sync, target still has no component named '%s'" % required)
    for name, (_h, src_obj) in sorted(source_components.items()):
        if name not in final or not isinstance(src_obj, unreal.SceneComponent):
            continue
        dst_obj = final[name][1]
        for prop in SCENE_PROPS:
            try:
                if not same(src_obj.get_editor_property(prop), dst_obj.get_editor_property(prop)):
                    fail("post-check: %s.%s still differs from the reference (want %s, got %s)"
                         % (name, prop, describe(src_obj.get_editor_property(prop)),
                            describe(dst_obj.get_editor_property(prop))))
            except Exception:
                pass


main()

log("--- %d change(s) ---" % len(CHANGES))
for change in CHANGES:
    log("  " + change)

if FAILURES:
    log("RESULT: FAILED, %d problem(s) — nothing above is claimed" % len(FAILURES))
    for failure in FAILURES:
        log("  " + failure)
    raise RuntimeError("sync_character_components: %d failure(s)" % len(FAILURES))

log("RESULT: OK")
