// Copyright 2022 Zollpa LLC.

#pragma once

#include "CoreMinimal.h"
#include "ImpaleActorBase.h"
#include "GameFramework/Actor.h"
#include "ZoransResistance/InventorySystem/Weapons/ZoransWeaponActor.h"
#include "ZoransProjectileBase.generated.h"

class UGameplayEffect;

DECLARE_DELEGATE(FProjectileUpdateDelegate);
DECLARE_DELEGATE_OneParam(FProjectileExpiredDelegate, int32);

UENUM(BlueprintType)
enum class EZoransProjectileSourceType : uint8
{
	World				UMETA(DisplayName = "World"),
	Weapon				UMETA(DisplayName = "Weapon"),
	Character			UMETA(DisplayName = "Character")
};

USTRUCT(BlueprintType)
struct FBaseProjectileSpawnParams
{
	GENERATED_USTRUCT_BODY()

	// This is the local spawn point of the shooter, typically the Muzzle socket of the equipped weapon.
	UPROPERTY(BlueprintReadWrite, Category = "Projectile Launch Parameters")
	FVector SpawnPoint = FVector::ZeroVector;

	// This is the direction the projectile was fired in.
	UPROPERTY(BlueprintReadWrite, Category = "Projectile Launch Parameters")
	FVector LaunchDirection = FVector::ZeroVector;

	// The time the projectile was launched on the local shooter, or the server if there was no local shooter.
	UPROPERTY(BlueprintReadWrite, Category = "Projectile Launch Parameters")
	float SpawnTime = -1.f;

	// This is the local index generated by the shooter, so the server has a way to reference a projectile indirectly, because the shooter does not get a replicated version of the projectile.
	UPROPERTY(BlueprintReadWrite, Category = "Projectile Launch Parameters")
	int32 LocalIndex = -1;

	UPROPERTY(BlueprintReadWrite, Category = "Projectile Launch Parameters")
	FName SpawnSocketOverride = NAME_None;

	bool NetSerialize(FArchive& Ar, class UPackageMap* Map, bool& bOutSuccess);
};

inline bool FBaseProjectileSpawnParams::NetSerialize(FArchive& Ar, class UPackageMap* Map, bool& bOutSuccess)
{
	SpawnPoint.NetSerialize(Ar, Map, bOutSuccess);
	LaunchDirection.NetSerialize(Ar, Map, bOutSuccess);

	Ar << SpawnTime;
	Ar << LocalIndex;
	Ar << SpawnSocketOverride;

	bOutSuccess = true;
	return true;
}

UCLASS(Abstract)
class ZORANSRESISTANCE_API AZoransProjectileBase : public AActor
{
	GENERATED_BODY()
public:
	AZoransProjectileBase();

	FProjectileExpiredDelegate ProjectileExpiredDelegate;

	virtual void GetLifetimeReplicatedProps(TArray< FLifetimeProperty > & OutLifetimeProps) const override;

	// This event only runs on the server and should be implemented inside the projectile in blueprint. This is where damage should be applied.
	UFUNCTION(BlueprintNativeEvent, Category = "Projectile Hit Events")
	void ServerHitReceived(const FHitResult& InHitResult);

	void Internal_ClientHitReceived(const FHitResult& InHitResult);

	// This event only runs on clients and should be implemented inside the projectile in blueprint. Purely for cosmetic effects like explosion particles and sound effects.
	UFUNCTION(BlueprintNativeEvent, BlueprintCosmetic, Category = "Projectile Hit Events")
	void ClientHitReceived(const FHitResult& InHitResult);

	UFUNCTION(NetMulticast, Reliable)
	void SendHitResultToClients(const FHitResult& InHitResult);

	void SendHitResultToAbilitySystemComponent(const int32 InProjectileIndex, const FHitResult& InHitResult);

	UFUNCTION(BlueprintCallable, BlueprintPure, Category = "Weapon")
	AZoransWeaponActor* GetOwningWeapon() { return OwningWeaponActor.Get(); }

	UFUNCTION(BlueprintCallable, Category = "Damage")
	FDamageMetricValue ApplyDamageToTarget(AActor* SourceActor, AActor* TargetActor, const FHitResult& HitResult, TSubclassOf<UGameplayEffect> DamageEffectClass, const float DamageAmount, const float AppliedImpactForce, const FGameplayTag DamageTag, bool& bValidHit);

	UFUNCTION(BlueprintCallable, BlueprintPure, Category = "Damage")
	float CalculateImpactForce(const float Modifier = 1.f) const;

protected:
	// BeginPlay is where we enabled the "tick" function for server/client independently.
	virtual void BeginPlay() override;

	virtual void EndPlay(const EEndPlayReason::Type EndPlayReason) override;

	// We override this because the Owner does not need a replicated projectile, they will have their own local version spawned.
	virtual bool IsNetRelevantFor(const AActor* RealViewer, const AActor* ViewTarget, const FVector& SrcLocation) const override;

	virtual bool PerformProjectileTrace(FHitResult& InHit, const FVector& NewLocation);

	// This is the custom Tick on the server.
	UFUNCTION()
	virtual void UpdateProjectile_Server();
	// This is the custom Tick on the client.
	virtual void UpdateProjectile_Client();
	// This disables the projectile on the server, but keeps it alive for 2 seconds so clients can receive the server hit before it is destroyed.
	void DeactivateProjectile();
	// This destroys the projectile.
	void DestroyProjectile();
	
	UFUNCTION(BlueprintNativeEvent, Category = "Projectile Hit Events")
	void ServerProjectileExpired();

	UFUNCTION(BlueprintNativeEvent, Category = "Projectile Hit Events")
	void ClientProjectileExpired();
		
	// These are the parameters sent from client to server for spawning the projectile.
	UPROPERTY(BlueprintReadWrite, Replicated, Meta = (ExposeOnSpawn = true), Category = "Projectile Launch Parameters")
	FVector SpawnPoint = FVector::ZeroVector;

	// This is the direction the projectile was fired in.
	UPROPERTY(BlueprintReadWrite, Replicated, Meta = (ExposeOnSpawn = true), Category = "Projectile Launch Parameters")
	FVector LaunchDirection = FVector::ZeroVector;

	// This is the local spawn time of the projectile. This is used to sync the server with the local shooter projectile and all other clients sync their version to this time.
	UPROPERTY(BlueprintReadWrite, Replicated, Meta = (ExposeOnSpawn = true), Category = "Projectile Launch Parameters")
	float SpawnTime = -1.f;

	// This is the local index generated by the shooter, so the server has a way to reference a projectile indirectly, because the shooter does not get a replicated version of the projectile.
	UPROPERTY(BlueprintReadWrite, Meta = (ExposeOnSpawn = true), Category = "Projectile Launch Parameters")
	int32 LocalIndex = -1;

	UPROPERTY(BlueprintReadWrite, Meta = (ExposeOnSpawn = true), Category = "Projectile Launch Parameters")
	UZoransGameplayAbility* OwningAbility = nullptr;

	// This value is only replicated if it is changed from the default. It only effects Character based spawn locations.
	UPROPERTY(BlueprintReadWrite, Replicated, Meta = (ExposeOnSpawn = true), Category = "Projectile Launch Parameters")
	FName SpawnSocketOverride = NAME_None;

	// This is the general speed of the projectile. Ballistic projectiles can adjust this with a curve over lifetime.
	UPROPERTY(BlueprintReadOnly, EditDefaultsOnly, meta = (EditCondition = "bCanModify"), Category = "Projectile Attributes")
	float ProjectileSpeed = 2000.f;

	// This is how long the projectile should exist for. We use this instead of the built in lifespan system to prevent the projectile from being destroyed during an impact before the clients receive the event.
	UPROPERTY(BlueprintReadOnly, EditDefaultsOnly, meta = (EditCondition = "bCanModify"), Category = "Projectile Attributes")
	float ProjectileLifespan = 5.f;

	// This is the radius that the projectile traces as it moves.
	UPROPERTY(BlueprintReadOnly, EditDefaultsOnly, meta = (EditCondition = "bCanModify"), Category = "Projectile Attributes")
	float ProjectileRadius = 8.f;

	// This is the impulse forced used if this projectile kills something.
	UPROPERTY(BlueprintReadOnly, EditDefaultsOnly, meta = (EditCondition = "bCanModify"), Category = "Projectile Attributes")
	float ImpactForce = 2000.f;

	// This is the actor that will be spawned IF the projectile has a damage type of "Impale".
	UPROPERTY(BlueprintReadOnly, EditDefaultsOnly, meta = (EditCondition = "bCanModify"), Category = "Projectile Attributes")
	AImpaleActorBase* ImpaleActor = nullptr;

	// If true, the projectile will spawn locally from the SpawnSocketName on the weapon, or the weapons origin if left to "None". If false, the SpawnSocketName will be searched for on the Character mesh.
	UPROPERTY(BlueprintReadOnly, EditDefaultsOnly, meta = (EditCondition = "bCanModify"), Category = "Projectile Attributes")
	EZoransProjectileSourceType SpawnSourceType = EZoransProjectileSourceType::Weapon;

	// If we spawn from a weapon, this would typically be "Muzzle". If not spawned from a weapon, it will assume it is from the character mesh and find that socket/bone location.
	UPROPERTY(BlueprintReadOnly, EditDefaultsOnly, Category = "Projectile Attributes")
	FName SpawnSocketName = FName("Muzzle");
	
	UPROPERTY(BlueprintReadOnly, EditDefaultsOnly, Category = "Projectile Attributes|Tracing")
	bool bTraceEnvironment = true;

	UPROPERTY(BlueprintReadOnly, EditDefaultsOnly, Category = "Projectile Attributes|Tracing")
	bool bTraceEnemy = true;

	UPROPERTY(BlueprintReadOnly, EditDefaultsOnly, Category = "Projectile Attributes|Tracing")
	bool bTraceFriendly = false;

	UFUNCTION(BlueprintCallable, BlueprintPure, Category = "Projectile Tracing")
	FName GetClosestBoneToHit(const FHitResult& InHit) const;

	UFUNCTION(BlueprintCallable, Category = "Projectile Tracing", meta = (HidePin = "Target", DefaultToSelf = "Target"))
	bool IsValidTarget(AActor* InActor);

	// This function will calculate the location of the projectile at any given point in its lifespan, based on the spawn parameters.
	virtual FVector GetProjectileLocationAtTime(const float InTime, const bool bServer);

	// This determines if the projectile will continue to "tick". Defaults to true, is disabled when the projectile receives a hit event.
	bool bIsActive = true;

	float GetServerProjectileLifetime() const;
	float GetLocalProjectileLifetime() const;

	float LocalSpawnTime = -1.f;
	FVector LocalSpawnLocation = FVector::ZeroVector;

	// We store the previous location so we can trace and get the correct rotation for the projectile.
	FVector PreviousLocation = FVector::ZeroVector;

	static inline float GravityConstant = 981.f;

	FCollisionObjectQueryParams ObjectQueryParams;
	FCollisionQueryParams CollisionQueryParams;

	bool bHasValidHit = false;

	bool bSynced = false;
	float SyncTime = -1.f;
	static inline float MaximumSyncTime = 0.25f;

	virtual void InitializeProjectileTraceParameters();

	TWeakObjectPtr<AZoransWeaponActor> OwningWeaponActor;

	UPROPERTY(BlueprintReadOnly, EditDefaultsOnly, Category = "Projectile Settings")
	bool bCanModify = true;
	
private:
	FTimerHandle DestroyProjectileTimer;
	FProjectileUpdateDelegate ProjectileUpdateDelegate;

	UPROPERTY()
	USceneComponent* ProjectileRoot = nullptr;
};