// Copyright 2022 Zollpa LLC.

#pragma once

#include "CoreMinimal.h"
#include "ZoransResistance/Projectiles/ZoransProjectileBase.h"
#include "ZoransProjectileBouncing.generated.h"

USTRUCT(BlueprintType)
struct FBouncingProjectilePathSegment
{
	GENERATED_USTRUCT_BODY()

	UPROPERTY(BlueprintReadWrite, Category = "Projectile Launch Parameters|Bouncing")
	float EndTime = 9999.f;
	
	UPROPERTY(BlueprintReadWrite, Category = "Projectile Launch Parameters|Bouncing")
	FVector SegmentStartLocation = FVector::ZeroVector;

	UPROPERTY(BlueprintReadWrite, Category = "Projectile Launch Parameters|Bouncing")
	FVector SegmentLaunchDirection = FVector::ZeroVector;

	UPROPERTY(BlueprintReadWrite, Category = "Projectile Launch Parameters|Bouncing")
	int32 SegmentBounceCount = -1;

	UPROPERTY(NotReplicated)
	float SegmentStartTime = -1.f;
	
	UPROPERTY(NotReplicated)
	bool bSelected = false;

	UPROPERTY(NotReplicated)
	bool bBounceTriggered = false;
	
	bool NetSerialize(FArchive& Ar, class UPackageMap* Map, bool& bOutSuccess);
};

inline bool FBouncingProjectilePathSegment::NetSerialize(FArchive& Ar, class UPackageMap* Map, bool& bOutSuccess)
{
	SegmentStartLocation.NetSerialize(Ar, Map, bOutSuccess);
	SegmentLaunchDirection.NetSerialize(Ar, Map, bOutSuccess);

	Ar << EndTime;
	Ar << SegmentBounceCount;
	
	bOutSuccess = true;
	return true;
}

USTRUCT(BlueprintType)
struct FBouncingProjectileSpawnParams
{
	GENERATED_USTRUCT_BODY()

	// This is the local spawn point of the shooter, typically the Muzzle socket of the equipped weapon.
	UPROPERTY(BlueprintReadWrite, Category = "Projectile Launch Parameters")
	FVector SpawnPoint = FVector::ZeroVector;

	// This is the direction the projectile was fired in.
	UPROPERTY(BlueprintReadWrite, Category = "Projectile Launch Parameters")
	FVector LaunchDirection = FVector::ZeroVector;

	// The time the projectile was launched on the local shooter, or the server if there was no local shooter.
	UPROPERTY(BlueprintReadWrite, Category = "Projectile Launch Parameters")
	float SpawnTime = -1.f;

	// This is the local index generated by the shooter, so the server has a way to reference a projectile indirectly, because the shooter does not get a replicated version of the projectile.
	UPROPERTY(BlueprintReadWrite, Category = "Projectile Launch Parameters")
	int32 LocalIndex = -1;

	UPROPERTY(BlueprintReadWrite, Category = "Projectile Launch Parameters")
	TArray<FBouncingProjectilePathSegment> BouncePath;

	UPROPERTY(BlueprintReadWrite, Category = "Projectile Launch Parameters")
	FName SpawnSocketOverride = NAME_None;
	
	bool NetSerialize(FArchive& Ar, class UPackageMap* Map, bool& bOutSuccess);
};

inline bool FBouncingProjectileSpawnParams::NetSerialize(FArchive& Ar, class UPackageMap* Map, bool& bOutSuccess)
{
	SpawnPoint.NetSerialize(Ar, Map, bOutSuccess);
	LaunchDirection.NetSerialize(Ar, Map, bOutSuccess);
	
	Ar << SpawnTime;
	Ar << LocalIndex;
	Ar << SpawnSocketOverride;

	bOutSuccess = true;
	return true;
}

UCLASS()
class ZORANSRESISTANCE_API AZoransProjectileBouncing : public AZoransProjectileBase
{
	GENERATED_BODY()
public:
	UPROPERTY(BlueprintReadWrite, ReplicatedUsing = OnRep_BouncePath, Meta = (ExposeOnSpawn = true), Category = "Projectile Spawn Params|Bouncing")
	//UPROPERTY(BlueprintReadWrite, Replicated, Meta = (ExposeOnSpawn = true), Category = "Projectile Spawn Params|Bouncing")
	TArray<FBouncingProjectilePathSegment> BouncePath;

	UFUNCTION()
	void OnRep_BouncePath();

	UPROPERTY(BlueprintReadOnly, EditDefaultsOnly, meta=(ClampMin = "1", ClampMax = "8", UIMin = "1", UIMax = "8"), Category = "Projectile Attributes|Bouncing")
	int32 NumberOfBounces = 2;

	UPROPERTY(BlueprintReadOnly, EditDefaultsOnly, Category = "Projectile Attributes|Bouncing")
	float EnergyLossPerBounce = 0.2f;

	UPROPERTY(BlueprintReadOnly, EditDefaultsOnly, Category = "Projectile Attributes|Bouncing")
	float MinimumSpeedModifier = 0.25f;
	
	UPROPERTY(BlueprintReadOnly, EditDefaultsOnly, Category = "Projectile Attributes|Bouncing")
	float MaximumSpeedModifier = 1.f;
	
	UPROPERTY(BlueprintReadOnly, EditDefaultsOnly, Category = "Projectile Attributes|Bouncing")
	float GravityModifier = 1.f;

	void ReceiveServerAdjustedBounce(TArray<FBouncingProjectilePathSegment> InNewBouncePath);

protected:
	void BeginPlay() override;
	
	void UpdateProjectile_Server() override;
	
	void UpdateProjectile_Client() override;

	bool PerformProjectileTrace(FHitResult& InHit, const FVector& NewLocation) override;
	
	FVector GetProjectileLocationAtTime(const float InTime, const bool bServer) override;
		
	float GetGravityEffectAtTime(const float InTime) const;

	float GetSpeedFromBounce(const int32 InBounce) const;
	
	TArray<FBouncingProjectilePathSegment> GenerateBouncePath();
	FBouncingProjectilePathSegment GenerateBounceSegment(const FVector InStartLocation, const FVector InLaunchDirection, const float InDuration, const float InPreviousTime,  FVector &EndLocation, FVector &BounceDirection, float &EndTime, const int32 InBounce);

	TArray<FBouncingProjectilePathSegment> RegenerateBouncePath(const FVector NewLocation, const FVector NewDirection, const int32 RemainingBounces);

	float RemainingLifespan = -1.f;
	int32 CurrentBounce = 0;
	float CurrentSpeed = 0.f;
	FBouncingProjectilePathSegment CurrentPathSegment = FBouncingProjectilePathSegment();

	bool ShouldBounce() const;

	UFUNCTION(BlueprintImplementableEvent, Category = "Projectile Hit Events")
	void ServerBounce(const FVector BounceLocation, const FVector BounceDirection);

	UFUNCTION(BlueprintImplementableEvent, Category = "Projectile Hit Events")
	void ClientBounce(const FVector BounceLocation, const FVector BounceDirection);

	bool SetNextPathSegment();

	FCollisionQueryParams BounceQueryParams;
	FCollisionObjectQueryParams BounceObjectParams;
	void InitializeProjectileTraceParameters() override;

	UPROPERTY()
	TArray<UPrimitiveComponent*> IgnoredDynamicComponents;

	UPROPERTY()
	TArray<UPrimitiveComponent*> IgnoredStaticComponents;

	void SendServerBounceAdjustmentToAbilitySystemComponent(const int32 InProjectileIndex, const TArray<FBouncingProjectilePathSegment> &InBouncePath);

	float TimeAdjustment = 0.f;

private:
	bool bProjectileInitialized = false;

	static inline float IntersectionTraceTolerance = 0.25f;
};
