#include "ABPMannequinBase.h"

// GENERATED by `Source/Breachpoint/anim/gen_abp_mannequin_base.py`. See the header.

UABPMannequinBase::UABPMannequinBase()
{
	// Inherited from UAnimInstance, so re-applied here rather than redeclared --
	// redeclaring a stock UPROPERTY shadows the engine's and misbehaves silently.
	RootMotionMode = ERootMotionMode::RootMotionFromMontagesOnly;  // the Blueprint set this; the engine default is RootMotionFromEverything
	bPropagateNotifiesToLinkedInstances = false;
	bReceiveNotifiesFromLinkedInstances = false;
	bUseMainInstanceMontageEvaluationData = false;

	// Every other property carries its Blueprint default as a member initialiser
	// in the header, where it stays visible next to the declaration.
}

void UABPMannequinBase::NativeInitializeAnimation()
{
	Super::NativeInitializeAnimation();
}

void UABPMannequinBase::NativeUpdateAnimation(float DeltaSeconds)
{
	Super::NativeUpdateAnimation(DeltaSeconds);
}
