#pragma once

#include "Animation/AnimInstance.h"
#include "CoreMinimal.h"
#include "Kismet/KismetMathLibrary.h"

#include "ABPMannequinBase.generated.h"

/**
 * 1:1 C++ port of the property surface of
 * `/Game/FPSTemplate/Demo/Characters/Heroes/Mannequin/Animations/ABP_Mannequin_Base`.
 *
 * GENERATED by `Source/Breachpoint/anim/gen_abp_mannequin_base.py` from two committed sources of truth:
 * `mcp-bp/bp_inventory.json` (the live-editor property read) and
 * `animations/reports/ABP_Mannequin_Base.json` (the asset's own name-table spelling). Re-run
 * the generator to check this file rather than trusting it -- a clean diff is the test.
 *
 * 1:1, AND WHAT THAT COSTS. Names are the Blueprint's, not this project's conventions. That
 * includes `isCrouching`, alone among its siblings in starting lowercase, and
 * `UpperbodyDynamicAdditiveWeight` with its lowercase `b`. Both are preserved: a name is how
 * the engine matches a property across a reparent, so "tidying" one is not a cosmetic change,
 * it is a silent data loss at the moment the Blueprint is reparented onto this class.
 *
 * NOT A REPLACEMENT FOR `UBRAnimInstance`. That class re-implemented this state model against
 * BREACHPOINT's laws -- worker-thread split, GAS tags, config-driven tuning -- and deliberately
 * did NOT carry the template's names or its 96-property shape. This is the other thing: a
 * faithful transcription of what the purchased asset declares, for diffing against the
 * re-implementation and for reparenting the template's own Blueprints onto C++ unchanged.
 * Picking one over the other is `docs/ANIM-PORT-LEDGER.md`'s call, not this file's.
 *
 * THE GRAPH IS NOT HERE. Node topology cannot be read from the package offline
 * (`animations/README.md` explains why), so the update passes are declared and left
 * unimplemented. An invented `NativeUpdateAnimation` would be the one part of a port nobody
 * could review against the source, so there isn't one.
 */

/** Cardinal direction, from `AnimEnum_CardinalDirection` (a user-defined enum: 4 enumerators). */
UENUM(BlueprintType)
enum class EAnimEnum_CardinalDirection : uint8
{
	Forward,
	Backward,
	Left,
	Right
};

/** From `AnimEnum_RootYawOffsetMode` (a user-defined enum: 3 enumerators). */
UENUM(BlueprintType)
enum class EAnimEnum_RootYawOffsetMode : uint8
{
	BlendOut,
	Hold,
	Accumulate
};

// The enumerator COUNTS above are read from the enum assets' name tables (NewEnumerator0..3 and
// NewEnumerator0..2). The enumerator NAMES are not: a user-defined enum stores its display
// names in a localised text map that the offline reader does not decode. `Forward` and
// `BlendOut` are confirmed -- they are the defaults this Blueprint serialises -- and the rest
// follow the Lyra strip these assets came from. Confirm the ORDER in the editor before relying
// on a cast to or from the underlying byte.

/** Mirrors `S_Procedural_AimSpineInfoItem_UE4`; members read from the struct asset. */
USTRUCT(BlueprintType)
struct FS_Procedural_AimSpineInfoItem_UE4
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spine")
	float head = 0.15f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spine")
	float neck_01 = 0.2f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spine")
	float spine_01 = 0.25f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spine")
	float spine_02 = 0.2f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spine")
	float spine_03 = 0.2f;
};

/** Mirrors `S_Procedural_AimSpineInfoItem_UE5`. */
USTRUCT(BlueprintType)
struct FS_Procedural_AimSpineInfoItem_UE5
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spine")
	float head = 0.1f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spine")
	float neck_01 = 0.15f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spine")
	float neck_02 = 0.2f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spine")
	float spine_01 = 0.15f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spine")
	float spine_02 = 0.1f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spine")
	float spine_03 = 0.1f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spine")
	float spine_04 = 0.1f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spine")
	float spine_05 = 0.1f;
};

/**
 * Mirrors `S_Procedural_LeanSpineInfoItem_UE4`.
 *
 * The first member is `head(Opposite Angle Weight)` in the editor; the asset stores it as
 * `headOppositeAngleWeight`, which is what a C++ identifier can be. The display name is
 * restored with `DisplayName` meta so the details panel still reads the way the pack intended.
 */
USTRUCT(BlueprintType)
struct FS_Procedural_LeanSpineInfoItem_UE4
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spine",
			  meta = (DisplayName = "head(Opposite Angle Weight)"))
	float headOppositeAngleWeight = 0.25f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spine")
	float neck_01 = 0.2f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spine")
	float spine_01 = 0.3f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spine")
	float spine_02 = 0.3f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spine")
	float spine_03 = 0.3f;
};

/** Mirrors `S_Procedural_LeanSpineInfoItem_UE5`. */
USTRUCT(BlueprintType)
struct FS_Procedural_LeanSpineInfoItem_UE5
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spine",
			  meta = (DisplayName = "head(Opposite Angle Weight)"))
	float headOppositeAngleWeight = 0.25f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spine")
	float neck_01 = 0.1f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spine")
	float neck_02 = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spine")
	float spine_01 = 0.2f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spine")
	float spine_02 = 0.2f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spine")
	float spine_03 = 0.2f;
};

UCLASS(Blueprintable, BlueprintType)
class BREACHPOINT_API UABPMannequinBase : public UAnimInstance
{
	GENERATED_BODY()

public:

	UABPMannequinBase();

protected:

	// Declared, not implemented -- see the class comment. The graph these would carry is not
	// readable offline, and a plausible-looking body would be invention wearing a port's name.
	virtual void NativeInitializeAnimation() override;
	virtual void NativeUpdateAnimation(float DeltaSeconds) override;

public:

	// ---------------------------------------------------------------- locomotion
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Locomotion")
	FVector LocalVelocity2D = FVector::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Locomotion")
	FVector LocalAcceleration2D = FVector::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Locomotion")
	FVector WorldVelocity = FVector::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Locomotion")
	FVector WorldLocation = FVector::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Locomotion")
	FRotator WorldRotation = FRotator::ZeroRotator;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Locomotion")
	EAnimEnum_CardinalDirection LocalVelocityDirection = EAnimEnum_CardinalDirection::Forward;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Locomotion")
	EAnimEnum_CardinalDirection LocalVelocityDirectionNoOffset = EAnimEnum_CardinalDirection::Forward;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Locomotion")
	float LocalVelocityDirectionAngle = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Locomotion")
	float LocalVelocityDirectionAngleWithOffset = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Locomotion")
	EAnimEnum_CardinalDirection CardinalDirectionFromAcceleration = EAnimEnum_CardinalDirection::Forward;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Locomotion")
	float CardinalDirectionDeadZone = 10.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Locomotion")
	EAnimEnum_CardinalDirection StartDirection = EAnimEnum_CardinalDirection::Forward;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Locomotion")
	bool HasVelocity = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Locomotion")
	bool HasAcceleration = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Locomotion")
	float DisplacementSinceLastUpdate = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Locomotion")
	float DisplacementSpeed = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Locomotion")
	float GroundDistance = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Locomotion")
	bool IsRunningIntoWall = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Locomotion")
	bool IsFirstUpdate = true;

	// ---------------------------------------------------------------- air
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Air")
	bool IsOnGround = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Air")
	bool IsFalling = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Air")
	bool IsJumping = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Air")
	float TimeToJumpApex = 0.f;

	// ---------------------------------------------------------------- crouch
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Crouch")
	bool isCrouching = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Crouch")
	bool CrouchStateChange = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Crouch")
	float ApplyCrouchAlpha = 0.f;

	// ---------------------------------------------------------------- pivot
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Pivot")
	FVector PivotDirection2D = FVector::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Pivot")
	EAnimEnum_CardinalDirection PivotInitialDirection = EAnimEnum_CardinalDirection::Forward;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Pivot")
	float LastPivotTime = 0.f;

	// ---------------------------------------------------------------- aim
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Aim")
	float AimPitch = -2.788732f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Aim")
	float AimYaw = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Aim")
	float Pitch = -0.417859f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Aim")
	FRotator PitchRotator = FRotator::ZeroRotator;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Aim")
	float YawDeltaSinceLastUpdate = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Aim")
	float YawDeltaSpeed = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Aim")
	float TurnYawCurveValue = 0.f;

	// ---------------------------------------------------------------- rootyawoffset
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|RootYawOffset")
	float RootYawOffset = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|RootYawOffset")
	FVector2D RootYawOffsetAngleClamp = FVector2D(-120.f, 100.f);
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|RootYawOffset")
	FVector2D RootYawOffsetAngleClampCrouched = FVector2D(-90.f, 80.f);
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|RootYawOffset")
	EAnimEnum_RootYawOffsetMode RootYawOffsetMode = EAnimEnum_RootYawOffsetMode::BlendOut;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|RootYawOffset")
	FFloatSpringState RootYawOffsetSpringState;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|RootYawOffset")
	bool bEnableRootYawOffset = true;

	// ---------------------------------------------------------------- lean
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Lean")
	FRotator LeanRotation = FRotator::ZeroRotator;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Lean")
	FRotator LeanOppRotation = FRotator::ZeroRotator;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Lean")
	float LeanAdditiveAlpha = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Lean")
	float AdditiveLeanAngle = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Lean")
	FS_Procedural_LeanSpineInfoItem_UE4 LeanSpineWeights_UE4;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Lean")
	FS_Procedural_LeanSpineInfoItem_UE5 LeanSpineWeights_UE5;

	// ---------------------------------------------------------------- spine
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Spine")
	FS_Procedural_AimSpineInfoItem_UE4 AimSpineWeights_UE4;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Spine")
	FS_Procedural_AimSpineInfoItem_UE5 AimSpineWeights_UE5;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Spine")
	float ApplyPelvisWeight = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Spine")
	float FPSPelvisWeight = 0.2f;

	// ---------------------------------------------------------------- camera
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Camera")
	FRotator CamRotCurrent = FRotator::ZeroRotator;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Camera")
	FRotator CamRotPrev = FRotator::ZeroRotator;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Camera")
	FRotator CamRotRate = FRotator::ZeroRotator;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Camera")
	FVector CamRotOffset = FVector::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Camera")
	float Head_CameraShake_Alpha = 1.f;

	// ---------------------------------------------------------------- poseoffset
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|PoseOffset")
	FVector BasePoseLocation = FVector::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|PoseOffset")
	FRotator BasePoseRotation = FRotator::ZeroRotator;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|PoseOffset")
	FVector CurrPoseLocation = FVector::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|PoseOffset")
	FRotator CurrPoseRotation = FRotator::ZeroRotator;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|PoseOffset")
	FVector MontagePoseOffsetLocation = FVector::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|PoseOffset")
	FRotator MontagePoseOffsetRotation = FRotator::ZeroRotator;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|PoseOffset")
	FVector ProcApplyLocation = FVector::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|PoseOffset")
	FRotator ProcApplyRotation = FRotator::ZeroRotator;

	// ---------------------------------------------------------------- footplacement
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|FootPlacement")
	FVector LeftJointTargetLocation = FVector::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|FootPlacement")
	FVector RightJointTargetLocation = FVector::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|FootPlacement")
	bool UseFootPlacement = true;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|FootPlacement")
	bool EnableControlRig = false;

	// ---------------------------------------------------------------- state
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|State")
	bool GameplayTag_IsADS = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|State")
	bool GameplayTag_IsDashing = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|State")
	bool GameplayTag_IsFiring = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|State")
	bool GameplayTag_IsMelee = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|State")
	bool GameplayTag_IsReloading = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|State")
	bool IsADS_Upper = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|State")
	bool WasADSLastUpdate = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|State")
	bool ADSStateChanged = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|State")
	bool bSprinting = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|State")
	bool bUnarmed = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|State")
	bool bFPSMode = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|State")
	bool bFPSWalkMode = false;

	// ---------------------------------------------------------------- weapon
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Weapon")
	float TimeSinceFiredWeapon = 9999.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Weapon")
	float ApplySwayAlpha = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|Weapon")
	float UpperbodyDynamicAdditiveWeight = 0.f;

	// ---------------------------------------------------------------- linkedlayer
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|LinkedLayer")
	TSubclassOf<UAnimInstance> LastLinkedLayer = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ABP Mannequin Base|LinkedLayer")
	bool LinkedLayerChanged = false;
};
