#pragma once

#include "CoreMinimal.h"
#include "Kismet/BlueprintFunctionLibrary.h"
#include "BNBotAuthoring.generated.h"

/**
 * The bot's two authored assets, BUILT IN CODE — /Game/BN/AI/ST_BNBot and
 * /Game/BN/Data/DT_BNBotAmbitions.
 *
 * WHY THIS IS C++ AND NOT A PYTHON SCRIPT. The project's rule is that assets are generated by a
 * committed script, never hand-placed. For a StateTree that is impossible in Python: the graph
 * lives in UStateTreeEditorData::SubTrees and UStateTreeState::Children, bare Instanced
 * UPROPERTYs carrying neither CPF_Edit nor CPF_BlueprintVisible, so PropertyAccessUtil refuses
 * them to Python and to the MCP ObjectTools alike; there is no StateTree factory exposed to
 * script; and UStateTreeEditingSubsystem::CompileStateTree is a plain static C++ function, not a
 * UFUNCTION — an uncompiled tree runs nothing. Every one of those doors is open to C++. So the
 * rule is kept, in the only language that can keep it, and the tree stops being a manual step
 * that has to be re-done by hand every time the node vocabulary changes.
 *
 * BlueprintCallable so the editor's Python console and the MCP bridge can invoke it; the bodies
 * are WITH_EDITOR only and the Game and Server targets get honest stubs.
 */
UCLASS()
class BREACHPOINTNEXT_API UBNBotAuthoring : public UBlueprintFunctionLibrary
{
	GENERATED_BODY()

public:
	/** Builds (or rebuilds, idempotently) /Game/BN/AI/ST_BNBot, compiles it, saves it. */
	UFUNCTION(BlueprintCallable, Category = "BN|Authoring")
	static FString BuildBotStateTree();

	/** Builds (or rebuilds) /Game/BN/Data/DT_BNBotAmbitions from UBNBotBrain::DefaultRow. */
	UFUNCTION(BlueprintCallable, Category = "BN|Authoring")
	static FString BuildBotAmbitionsTable();

	/** R10 — DT_BNBotTuning: the four difficulty tiers, mirrored from
	 *  ABNBotController::DefaultTuning for the same reason the ambitions table mirrors
	 *  UBNBotBrain::DefaultRow — one source of truth, and the table exists to be RETUNED, not to
	 *  re-declare numbers C++ already ships. */
	static FString BuildBotTuningTable();

	/** Both of the above, then the read-back. The one call the terminal makes. */
	UFUNCTION(BlueprintCallable, Category = "BN|Authoring")
	static FString BuildBotAssets();

	/** Read-back only, from a fresh load: what is actually in the two assets on disk. */
	UFUNCTION(BlueprintCallable, Category = "BN|Authoring")
	static FString AuditBotAssets();
};
