#!/usr/bin/env python3
# =====================================================================================
# BREACHPOINT - arena_plan.py :: manifest -> validated, deterministic BUILD PLAN
#
# Serves:   TICKET BP07 step 2 (blockout BR_Arena01 from Content/Data/arena_manifest.json).
# Law:      CLAUDE.md law 7 - "Blockouts ... are generated by committed scripts, never
#           hand-placed." The manifest is the source of truth; the .umap is its projection.
# Contract: docs/contracts/data-and-assets.md (the manifest is a data artifact).
#
# THIS FILE IMPORTS NOTHING FROM UNREAL. It is plain CPython 3.9+ with only the stdlib, so
# the manifest can be validated and the whole plan can be reviewed WITHOUT an editor:
#
#     python Tools/blockout/arena_plan.py --manifest Content/Data/arena_manifest.json
#
# build_arena.py (which does import unreal) imports this module and executes the plan it
# returns. The split is deliberate: every decision - what gets built, where, why - is made
# and diffable outside the editor, and the editor half is a dumb executor.
#
# Exit codes match the ladder convention (Tools/_BRLadderCommon.ps1):
#   0 PASS  plan is valid and complete   1 FAIL  validation errors   3 BLOCKED  cannot read input
# =====================================================================================
"""Validate arena_manifest.json and derive a deterministic blockout build plan."""

import argparse
import hashlib
import json
import math
import os
import re
import sys

M_TO_CM = 100.0  # the ONE metre->centimetre conversion in this toolchain (units law)

# -------------------------------------------------------------------------------------
# KICKOFF THRESHOLDS - the machine-checkable arena bounds.
# These are acceptance law, not tuning. They are constants here and are deliberately NOT
# readable from blockout_profile.json: a gate that a profile file can weaken is not a gate.
# -------------------------------------------------------------------------------------
KICKOFF_MIN_SPAWNS = 8
KICKOFF_MIN_SPAWN_SPACING_M = 8.0
KICKOFF_MAX_SIGHTLINE_M = 35.0
KICKOFF_ROCKET_LANDMARK_REQUIRED = True

ROCKET_RE = re.compile(r"rocket", re.IGNORECASE)

# "x[16,24] y[16,24], z[0,9]" - the only machine-readable geometry the manifest carries.
FOOTPRINT_RE = re.compile(
    r"x\[\s*(-?\d+(?:\.\d+)?)\s*,\s*(-?\d+(?:\.\d+)?)\s*\]\s*"
    r"y\[\s*(-?\d+(?:\.\d+)?)\s*,\s*(-?\d+(?:\.\d+)?)\s*\]"
    r"(?:\s*,?\s*z\[\s*(-?\d+(?:\.\d+)?)\s*,\s*(-?\d+(?:\.\d+)?)\s*\])?",
    re.IGNORECASE)
AT_Z_RE = re.compile(r"\bat\s+z\s*=\s*(-?\d+(?:\.\d+)?)", re.IGNORECASE)
FULL_HEIGHT_RE = re.compile(r"full[-\s]?height", re.IGNORECASE)
# An explicit rocket node point, should a future manifest revision carry one in prose.
NODE_POINT_RE = re.compile(
    r"node\s*[:=]?\s*\(\s*(-?\d+(?:\.\d+)?)\s*,\s*(-?\d+(?:\.\d+)?)\s*,\s*(-?\d+(?:\.\d+)?)\s*\)",
    re.IGNORECASE)
STAIR_CTX_RE = re.compile(r"stair|connector|ramp", re.IGNORECASE)
COUNT_CLAIM_RE = {
    "spawn_points": re.compile(r"all\s+(\d+)\s+spawn", re.IGNORECASE),
    "landmarks": re.compile(r"(\d+)\s+landmark\s+footprints", re.IGNORECASE),
    "cover": re.compile(r"(\d+)\s+cover\s+placements", re.IGNORECASE),
}

ERROR = "error"
WARN = "warn"


# =====================================================================================
# findings
# =====================================================================================

class Finding(object):
    """One validator result. `code` is stable so a triager can grep for it."""

    def __init__(self, severity, code, message):
        self.severity = severity
        self.code = code
        self.message = message

    def as_dict(self):
        return {"severity": self.severity, "code": self.code, "message": self.message}

    def __str__(self):
        return "%-5s %-26s %s" % (self.severity.upper(), self.code, self.message)


class ManifestError(Exception):
    """Raised when the manifest cannot be read/parsed at all (BLOCKED, not FAIL)."""


# =====================================================================================
# small geometry helpers (all metres, all pure)
# =====================================================================================

def _r(v, places=3):
    """Round for digest stability - float text must not vary by platform."""
    return round(float(v) + 0.0, places)


def dist3(a, b):
    return math.sqrt((a[0] - b[0]) ** 2 + (a[1] - b[1]) ** 2 + (a[2] - b[2]) ** 2)


def aabb(x_range, y_range, z_range):
    return {"x": [min(x_range), max(x_range)],
            "y": [min(y_range), max(y_range)],
            "z": [min(z_range), max(z_range)]}


def aabb_center(box):
    return [(box["x"][0] + box["x"][1]) / 2.0,
            (box["y"][0] + box["y"][1]) / 2.0,
            (box["z"][0] + box["z"][1]) / 2.0]


def aabb_size(box):
    return [box["x"][1] - box["x"][0],
            box["y"][1] - box["y"][0],
            box["z"][1] - box["z"][0]]


def segment_hits_aabb(p0, p1, box, eps=1e-6):
    """Slab test: does the segment p0->p1 intersect the axis-aligned box?

    Used for the static (rung-1, algebraic) sightline occlusion check. It proves nothing
    about the built level - see the manifest's own doubts[] and landing_note.
    """
    t0, t1 = 0.0, 1.0
    for i, axis in enumerate(("x", "y", "z")):
        lo, hi = box[axis][0], box[axis][1]
        d = p1[i] - p0[i]
        if abs(d) < eps:
            if p0[i] < lo - eps or p0[i] > hi + eps:
                return False
            continue
        ta = (lo - p0[i]) / d
        tb = (hi - p0[i]) / d
        if ta > tb:
            ta, tb = tb, ta
        t0 = max(t0, ta)
        t1 = min(t1, tb)
        if t0 > t1:
            return False
    return True


def boxes_touch(a, b, tol):
    """Do two AABBs overlap or abut on all three axes (within tol)?"""
    for axis in ("x", "y", "z"):
        if a[axis][0] - tol > b[axis][1] or b[axis][0] - tol > a[axis][1]:
            return False
    return True


def ground_connected(solids, tol):
    """Labels of the solids walkably reachable from ground level by touching geometry.

    A coarse, static connectivity flood-fill: anything whose underside is at/below ground
    seeds the set, and anything abutting a member joins it. It does NOT model step height,
    slope, or grapple - it only answers 'is this deck attached to anything at all?', which
    is enough to catch a platform left floating by a manifest edit.
    """
    reached = set()
    frontier = []
    for i, s in enumerate(solids):
        if s["box"]["z"][0] <= tol:
            reached.add(i)
            frontier.append(i)
    while frontier:
        i = frontier.pop()
        for j, s in enumerate(solids):
            if j in reached:
                continue
            if boxes_touch(solids[i]["box"], s["box"], tol):
                reached.add(j)
                frontier.append(j)
    return reached


def slug(text):
    """Deterministic, filesystem-and-label-safe identifier from a manifest name."""
    out = re.sub(r"[^A-Za-z0-9]+", "_", str(text)).strip("_")
    return out if out else "Unnamed"


# =====================================================================================
# manifest parsing
# =====================================================================================

def parse_footprints(text):
    """Every `x[..] y[..] (z[..])` in a landmark's prose, in text order.

    The manifest keeps landmark geometry in the free-text `purpose` field. Parsing it is
    the only way to build the arena WITHOUT re-typing (and thereby forking) those numbers -
    see contract_gap BP07-CG-1: manifest v3 should carry structured footprints.
    """
    found = []
    for m in FOOTPRINT_RE.finditer(text):
        g = m.groups()
        item = {
            "x": [float(g[0]), float(g[1])],
            "y": [float(g[2]), float(g[3])],
            "z": [float(g[4]), float(g[5])] if g[4] is not None else None,
            "span": [m.start(), m.end()],
            "raw": m.group(0),
            "context_before": text[max(0, m.start() - 90):m.start()],
        }
        found.append(item)
    return found


def resolve_footprint_z(footprint, landmark, all_landmark_z, profile):
    """Resolve a footprint's z-range and say, in words, how it was resolved.

    Returns (z_range, derivation_text, inferred_bool). `inferred` is True whenever the
    z came from prose rather than an explicit z[..], so --strict can refuse to build
    anything whose height was guessed.
    """
    if footprint["z"] is not None:
        return (list(footprint["z"]),
                "explicit z[%g,%g] in purpose text" % (footprint["z"][0], footprint["z"][1]),
                False)

    text = landmark.get("purpose", "")
    at_z = AT_Z_RE.search(text)
    is_stair = bool(STAIR_CTX_RE.search(footprint["context_before"]))

    if is_stair:
        # "two stair connectors ... linking ground floor to the Gantry" - span from ground
        # to the landmark the prose LINKS TO. Prefer the name that follows a "to (the) X"
        # phrase over merely-mentioned names: this landmark's text also mentions the Core
        # (as a face it runs along), and taking the tallest mention would silently build
        # 9 m stairs to the wrong structure.
        target_z, target_name = None, None
        for m in re.finditer(r"\bto\s+(?:the\s+)?([A-Z][A-Za-z]*(?:\s+[A-Z][A-Za-z]*)*)", text):
            phrase = m.group(1)
            for name, z in all_landmark_z.items():
                if z is None or name == landmark.get("name"):
                    continue
                short = re.sub(r"^the\s+", "", name, flags=re.IGNORECASE)
                if re.search(r"\b%s\b" % re.escape(short), phrase, re.IGNORECASE):
                    target_z, target_name = z, name
                    break
            if target_z is not None:
                break
        if target_z is None:
            for name, z in all_landmark_z.items():
                if z is None or name == landmark.get("name"):
                    continue
                if re.search(re.escape(name), text, re.IGNORECASE):
                    if target_z is None or z > target_z:
                        target_z, target_name = z, name
        if target_z is None and at_z:
            target_z, target_name = float(at_z.group(1)), landmark.get("name")
        if target_z is None:
            return (None, "stair connector with no resolvable target elevation", True)
        return ([0.0, target_z],
                "stair/connector inferred to span ground(0) -> z=%g (named target: %s)"
                % (target_z, target_name), True)

    if at_z:
        z = float(at_z.group(1))
        t = float(profile["deck_thickness_m"])
        return ([z - t, z], "deck slab inferred from 'at z=%g', thickness %g m from profile" % (z, t), True)

    if FULL_HEIGHT_RE.search(text):
        h = float(profile["cover_dims_m"]["full"]["z"])
        return ([0.0, h], "full-height block inferred from 'full-height', height %g m from profile" % h, True)

    h = float(profile["landmark_default_height_m"])
    return ([0.0, h], "no z in text - profile landmark_default_height_m %g m" % h, True)


def landmark_z_hints(landmarks):
    """name -> the 'at z=N' / top-of-z[..] elevation the prose gives it (or None)."""
    out = {}
    for lm in landmarks:
        text = lm.get("purpose", "")
        m = AT_Z_RE.search(text)
        if m:
            out[lm.get("name", "")] = float(m.group(1))
            continue
        fps = parse_footprints(text)
        z = None
        for fp in fps:
            if fp["z"] is not None:
                z = fp["z"][1] if z is None else max(z, fp["z"][1])
        out[lm.get("name", "")] = z
    return out


# =====================================================================================
# validation
# =====================================================================================

def validate(manifest, profile, solids):
    """Every check the ticket's Kickoff block names, plus structural sanity.

    Returns a list of Finding. ERROR blocks the build; WARN is recorded and printed.
    Nothing here stops at the first problem - a builder gets the whole list at once.
    """
    f = []
    spawns = manifest.get("spawn_points", []) or []
    landmarks = manifest.get("landmarks", []) or []
    cover = manifest.get("cover", []) or []
    bounds = manifest.get("bounds", {}) or {}

    # ---- Kickoff 1: >= 8 spawns -----------------------------------------------------
    if len(spawns) < KICKOFF_MIN_SPAWNS:
        f.append(Finding(ERROR, "SPAWN_COUNT",
                         "%d spawn_points; ticket BP07 Kickoff requires >= %d."
                         % (len(spawns), KICKOFF_MIN_SPAWNS)))

    # ---- structural: ids, bounds containment ----------------------------------------
    seen = {}
    for i, sp in enumerate(spawns):
        sid = sp.get("id")
        if not sid:
            f.append(Finding(ERROR, "SPAWN_NO_ID", "spawn_points[%d] has no id." % i))
            continue
        if sid in seen:
            f.append(Finding(ERROR, "SPAWN_DUP_ID",
                             "spawn id '%s' used by spawn_points[%d] and [%d]." % (sid, seen[sid], i)))
        seen[sid] = i
        loc = sp.get("location") or {}
        for axis in ("x", "y", "z"):
            if axis not in loc:
                f.append(Finding(ERROR, "SPAWN_NO_LOC",
                                 "spawn '%s' location is missing '%s'." % (sid, axis)))
        if bounds:
            for axis in ("x", "y", "z"):
                v, lim = loc.get(axis), bounds.get(axis)
                if v is None or lim is None:
                    continue
                if v < 0 or v > lim:
                    f.append(Finding(ERROR, "SPAWN_OUT_OF_BOUNDS",
                                     "spawn '%s' %s=%g is outside bounds 0..%g." % (sid, axis, v, lim)))
        facing = sp.get("facing")
        if facing is None:
            f.append(Finding(WARN, "SPAWN_NO_FACING", "spawn '%s' has no facing; yaw 0 assumed." % sid))
        hints = sp.get("scoring_hints") or {}
        if not hints:
            f.append(Finding(WARN, "SPAWN_NO_HINTS",
                             "spawn '%s' carries no scoring_hints; the respawn scorer gets nothing." % sid))

    # ---- Kickoff 2: min pairwise spacing >= 8 m --------------------------------------
    pts = []
    ids_seen = [sp.get("id") for sp in spawns]
    for i, sp in enumerate(spawns):
        loc = sp.get("location") or {}
        if not all(a in loc for a in ("x", "y", "z")):
            continue
        sid = sp.get("id", "?")
        # disambiguate when the manifest reuses an id (itself an error above) so no
        # finding can ever read "SP3-SP3" and leave the reader guessing which one
        label = sid if ids_seen.count(sid) == 1 else "%s#%d" % (sid, i)
        pts.append((label, [float(loc["x"]), float(loc["y"]), float(loc["z"])]))
    worst = None
    for i in range(len(pts)):
        for j in range(i + 1, len(pts)):
            d = dist3(pts[i][1], pts[j][1])
            if worst is None or d < worst[0]:
                worst = (d, pts[i][0], pts[j][0])
            if d < KICKOFF_MIN_SPAWN_SPACING_M:
                f.append(Finding(ERROR, "SPAWN_SPACING",
                                 "%s-%s are %.2f m apart; Kickoff requires >= %.1f m."
                                 % (pts[i][0], pts[j][0], d, KICKOFF_MIN_SPAWN_SPACING_M)))
    if worst:
        f.append(Finding("info", "SPAWN_SPACING_MIN",
                         "closest spawn pair: %s-%s at %.2f m (limit %.1f m)."
                         % (worst[1], worst[2], worst[0], KICKOFF_MIN_SPAWN_SPACING_M)))

    # ---- Kickoff 3: max sightline <= 35 m --------------------------------------------
    declared = (manifest.get("sightlines") or {}).get("max_length_m")
    if declared is None:
        f.append(Finding(ERROR, "SIGHTLINE_UNDECLARED", "manifest declares no sightlines.max_length_m."))
    elif float(declared) > KICKOFF_MAX_SIGHTLINE_M:
        f.append(Finding(ERROR, "SIGHTLINE_CAP",
                         "declared sightlines.max_length_m=%g exceeds the %g m Kickoff cap."
                         % (float(declared), KICKOFF_MAX_SIGHTLINE_M)))
    eye = float(profile["eye_height_m"])
    longest_open = None
    for i in range(len(pts)):
        for j in range(i + 1, len(pts)):
            a = [pts[i][1][0], pts[i][1][1], pts[i][1][2] + eye]
            b = [pts[j][1][0], pts[j][1][1], pts[j][1][2] + eye]
            if any(segment_hits_aabb(a, b, s["box"]) for s in solids):
                continue
            d = dist3(a, b)
            if longest_open is None or d > longest_open[0]:
                longest_open = (d, pts[i][0], pts[j][0])
            if d > KICKOFF_MAX_SIGHTLINE_M:
                f.append(Finding(ERROR, "SIGHTLINE_OPEN_PAIR",
                                 "%s-%s: %.2f m with no solid on the line at %.1f m eye height; cap is %g m."
                                 % (pts[i][0], pts[j][0], d, eye, KICKOFF_MAX_SIGHTLINE_M)))
    if longest_open:
        f.append(Finding("info", "SIGHTLINE_LONGEST_OPEN",
                         "longest unoccluded spawn-to-spawn line: %s-%s at %.2f m (static AABB test only)."
                         % (longest_open[1], longest_open[2], longest_open[0])))

    # ---- Kickoff 4: a NAMED rocket landmark, with a buildable node point --------------
    if KICKOFF_ROCKET_LANDMARK_REQUIRED:
        hits = [lm for lm in landmarks
                if ROCKET_RE.search(lm.get("name", "") or "") or ROCKET_RE.search(lm.get("purpose", "") or "")]
        if not hits:
            f.append(Finding(ERROR, "ROCKET_LANDMARK_MISSING",
                             "no landmark names the rocket; Kickoff requires a named rocket landmark."))
        else:
            if not any(ROCKET_RE.search(lm.get("name", "") or "") for lm in hits):
                f.append(Finding(WARN, "ROCKET_NAME_INDIRECT",
                                 "the rocket is named only in prose (landmark '%s'), not in a landmark name."
                                 % hits[0].get("name")))
            if resolve_rocket_node(manifest) is None:
                f.append(Finding(
                    ERROR, "ROCKET_NODE_UNBUILDABLE",
                    "landmark '%s' names the rocket but the manifest gives no buildable node point: it "
                    "declares the volume SOLID over its whole footprint and z-range, so there is no "
                    "standable pad inside it, and no `rocket_node` field / `node:(x,y,z)` token exists. "
                    "A blockout cannot place ABRPowerWeaponSpawner without inventing a coordinate, and "
                    "the manifest's own landing_note forbids that ('zero deviation ... must instead go "
                    "back through review as a new revision'). Manifest owner (BP13): add a structured "
                    "`rocket_node: {x, y, z}` and reconcile it with the volume's solidity."
                    % hits[0].get("name")))

    # ---- structural: landmark footprints must parse ----------------------------------
    for i, lm in enumerate(landmarks):
        name = lm.get("name") or ("landmarks[%d]" % i)
        if not parse_footprints(lm.get("purpose", "") or ""):
            f.append(Finding(ERROR, "LANDMARK_NO_FOOTPRINT",
                             "landmark '%s' carries no parseable x[..] y[..] footprint in its purpose text; "
                             "nothing can be generated for it." % name))

    # ---- structural: cover ------------------------------------------------------------
    classes = profile["cover_dims_m"]
    for i, cv in enumerate(cover):
        hc = cv.get("height_class")
        if hc not in classes:
            f.append(Finding(ERROR, "COVER_HEIGHT_CLASS",
                             "cover[%d] height_class '%s' is not one of %s (profile blockout_profile.json)."
                             % (i, hc, sorted(classes.keys()))))
        loc = cv.get("location") or {}
        if not all(a in loc for a in ("x", "y", "z")):
            f.append(Finding(ERROR, "COVER_NO_LOC", "cover[%d] has an incomplete location." % i))

    # ---- self-consistency: the landing_note's own counts vs the arrays ----------------
    note = manifest.get("landing_note", "") or ""
    actual = {"spawn_points": len(spawns), "landmarks": len(landmarks), "cover": len(cover)}
    for key, rx in COUNT_CLAIM_RE.items():
        m = rx.search(note)
        if not m:
            continue
        claimed = int(m.group(1))
        if claimed != actual[key]:
            f.append(Finding(WARN, "LANDING_NOTE_COUNT",
                             "landing_note says '%s' but %s[] holds %d entries. The reviewed text and the "
                             "data disagree - one of them is stale (manifest owner: BP13)."
                             % (m.group(0), key, actual[key])))

    # ---- structural: elevated decks that nothing connects to -------------------------
    tol = float(profile["adjacency_tolerance_m"])
    reached = ground_connected(solids, tol)
    for i, s in enumerate(solids):
        if i in reached or s["box"]["z"][0] <= tol:
            continue
        carried = [sid for sid, p in pts
                   if s["box"]["x"][0] - tol <= p[0] <= s["box"]["x"][1] + tol
                   and s["box"]["y"][0] - tol <= p[1] <= s["box"]["y"][1] + tol
                   and abs(p[2] - s["box"]["z"][1]) <= tol + 0.5]
        who = (" It carries spawn(s) %s." % ", ".join(carried)) if carried else ""
        f.append(Finding(
            WARN, "DECK_UNCONNECTED",
            "'%s' %s piece x[%g,%g] y[%g,%g] z[%g,%g] abuts no other structure and no ground - by "
            "static geometry it is a "
            "floating island.%s The upper level is grapple-primary by design, so this may be intended; "
            "it is NOT provable from coordinates either way and must be confirmed at the rung-3 "
            "walkthrough / reachability sweep (BP07 step 4)."
            % (s["name"], s["source"],
               s["box"]["x"][0], s["box"]["x"][1], s["box"]["y"][0], s["box"]["y"][1],
               s["box"]["z"][0], s["box"]["z"][1], who)))

    # ---- grapple markup: the ticket asks for it, the manifest does not carry it -------
    if "grapple_points" not in manifest:
        f.append(Finding(WARN, "GRAPPLE_POINTS_ABSENT",
                         "manifest has no grapple_points[]; TICKET_BP07 step 1 requires '>= 2 grapple points "
                         "per upper position' and step 2 asks for grapple-point markup. This generator will "
                         "NOT invent them - it emits no grapple actors. Manifest owner (BP13) must add them."))

    return f


def resolve_rocket_node(manifest):
    """Return [x, y, z] for the power-weapon node, or None if the manifest doesn't say.

    Accepted, in order: a structured top-level `rocket_node` {x,y,z}; a `node:(x,y,z)`
    token in the rocket landmark's prose. Deliberately NO centroid fallback: guessing a
    coordinate inside a volume the manifest calls SOLID is exactly the silent drift the
    landing_note forbids.
    """
    rn = manifest.get("rocket_node")
    if isinstance(rn, dict) and all(a in rn for a in ("x", "y", "z")):
        return [float(rn["x"]), float(rn["y"]), float(rn["z"])]
    for lm in manifest.get("landmarks", []) or []:
        text = "%s %s" % (lm.get("name", ""), lm.get("purpose", ""))
        if not ROCKET_RE.search(text):
            continue
        m = NODE_POINT_RE.search(lm.get("purpose", "") or "")
        if m:
            return [float(m.group(1)), float(m.group(2)), float(m.group(3))]
    return None


# =====================================================================================
# plan construction
# =====================================================================================

def _element(kind, label, source, derivation, tags, inferred=False, **kw):
    """One planned actor.

    `inferred` marks geometry that came from prose parsing or the construction profile
    rather than explicit manifest numbers. It is an explicit flag, never sniffed out of
    the derivation string, so the --strict audit cannot drift from what it audits.
    """
    e = {"kind": kind, "label": label, "source": source, "derivation": derivation,
         "tags": list(tags), "inferred": bool(inferred)}
    e.update(kw)
    return e


def _box_element(kind, label, source, derivation, tags, box, asset, inferred=False):
    c = aabb_center(box)
    s = aabb_size(box)
    return _element(kind, label, source, derivation, tags, inferred=inferred,
                    asset=asset,
                    box_m={"x": [_r(box["x"][0]), _r(box["x"][1])],
                           "y": [_r(box["y"][0]), _r(box["y"][1])],
                           "z": [_r(box["z"][0]), _r(box["z"][1])]},
                    location_cm=[_r(c[0] * M_TO_CM), _r(c[1] * M_TO_CM), _r(c[2] * M_TO_CM)],
                    size_cm=[_r(s[0] * M_TO_CM), _r(s[1] * M_TO_CM), _r(s[2] * M_TO_CM)],
                    rotation=[0.0, 0.0, 0.0])



# ---- BN21: a stair volume is a FLIGHT OF STEPS, not a block --------------------------
# The manifest calls stair_west/stair_east "ground-to-mid stair volume", but a volume
# emitted as one AABB is a solid 4 m wall. MaxStepHeight is 45 uu and the character's jump
# apex is 90 uu, so a 400 uu face is unclimbable by a factor of 4.4 - and with the Gantry
# grapple-only by design and no grappleshot implemented, that made the whole arena one-way
# downward for players as much as bots. The manifest's own `doubts` list already suspected
# it ("real ramp geometry may occlude them").
#
# Steps are generated, never hand-placed (law 7). Each riser stays at or under
# STAIR_MAX_RISE_M so the character WALKS up with no jump at all and the navmesh covers the
# flight natively - no navlink, no promise the body cannot keep.
STAIR_MAX_RISE_M = 0.45          # UCharacterMovementComponent::MaxStepHeight = 45 uu
STAIR_CLIMB_AXIS_MIN_RUN_M = 0.20  # refuse to emit treads thinner than a boot


def stair_steps(box):
    """One stair AABB -> a list of tread AABBs climbing its LONGER horizontal axis.

    Ascends along whichever of x/y is longer (the run), each tread spanning the full
    shorter axis (the width) and rising from z-floor to its own top, so consecutive treads
    present a <=STAIR_MAX_RISE_M face and every tread is solid to the ground beneath it.
    Returns [] when the rise already walks in one step - the caller then keeps the volume.
    """
    z0, z1 = float(box["z"][0]), float(box["z"][1])
    rise = z1 - z0
    if rise <= STAIR_MAX_RISE_M:
        return []

    n = int(math.ceil(rise / STAIR_MAX_RISE_M))
    xr = float(box["x"][1]) - float(box["x"][0])
    yr = float(box["y"][1]) - float(box["y"][0])
    run_axis = "x" if xr >= yr else "y"
    run = xr if run_axis == "x" else yr
    if run / n < STAIR_CLIMB_AXIS_MIN_RUN_M:
        return []

    a0 = float(box[run_axis][0])
    tread = run / n
    other = "y" if run_axis == "x" else "x"
    steps = []
    for i in range(n):
        top = z0 + rise * (i + 1) / n
        b = {other: [float(box[other][0]), float(box[other][1])],
             "z": [z0, _r(top)]}
        b[run_axis] = [_r(a0 + tread * i), _r(a0 + tread * (i + 1))]
        steps.append(b)
    return steps


def collect_solids(manifest, profile):
    """Every occluding volume the manifest names, as AABBs (metres).

    Built before validation because the sightline check needs it. Also the geometry the
    plan's landmark/cover elements are derived from, so the two can never disagree.
    """
    solids = []
    landmarks = manifest.get("landmarks", []) or []
    z_hints = landmark_z_hints(landmarks)

    for li, lm in enumerate(landmarks):
        name = lm.get("name") or ("landmarks[%d]" % li)
        text = lm.get("purpose", "") or ""
        for fi, fp in enumerate(parse_footprints(text)):
            z, derivation, inferred = resolve_footprint_z(fp, lm, z_hints, profile)
            if z is None:
                continue
            is_stair = bool(STAIR_CTX_RE.search(fp["context_before"]))
            is_deck = (not is_stair) and fp["z"] is None and bool(AT_Z_RE.search(text))
            solids.append({
                "kind": "landmark_stair" if is_stair else ("landmark_deck" if is_deck else "landmark_solid"),
                "name": name,
                "index": fi,
                "source": "landmarks[%d]" % li,
                "box": aabb(fp["x"], fp["y"], z),
                "derivation": "footprint %s; %s" % (fp["raw"], derivation),
                "inferred": inferred,
            })

    for ci, cv in enumerate(manifest.get("cover", []) or []):
        loc = cv.get("location") or {}
        hc = cv.get("height_class")
        dims = profile["cover_dims_m"].get(hc)
        if dims is None or not all(a in loc for a in ("x", "y", "z")):
            continue
        x, y, z = float(loc["x"]), float(loc["y"]), float(loc["z"])
        solids.append({
            "kind": "cover",
            "name": "Cover_%s_%02d" % (hc, ci + 1),
            "index": ci,
            "source": "cover[%d]" % ci,
            "box": aabb([x - dims["x"] / 2.0, x + dims["x"] / 2.0],
                        [y - dims["y"] / 2.0, y + dims["y"] / 2.0],
                        [z, z + dims["z"]]),
            "derivation": "cover[%d] point (%g,%g,%g), height_class '%s' -> %gx%gx%g m from profile"
                          % (ci, x, y, z, hc, dims["x"], dims["y"], dims["z"]),
            "inferred": True,  # extents are profile-supplied; the manifest gives a point only
        })
    return solids


def _colocated(box_a, box_b, tol):
    ca, cb = aabb_center(box_a), aabb_center(box_b)
    return (abs(ca[0] - cb[0]) <= tol and abs(ca[1] - cb[1]) <= tol)


def build_plan(manifest, profile, strict=False):
    """Validate, then derive the ordered element list. Returns a plan dict.

    Determinism contract (see README):
      * elements are emitted in a fixed section order, and within a section in manifest
        array order (json.load preserves document order), then footprint text order;
      * every label is derived from manifest ids/names via slug() + a zero-padded index -
        no counters that depend on editor state, no timestamps, no uuids, no randomness;
      * every float is rounded via _r() before it enters the plan;
      * the plan digest is sha256 over the canonical JSON of the element list.
    Same manifest + same profile => same digest => same actors, forever.
    """
    tag = profile["map"]["generated_tag"]
    assets = profile["assets"]
    classes = profile["classes"]
    cube = assets["cube"]

    solids = collect_solids(manifest, profile)
    findings = validate(manifest, profile, solids)

    elements = []
    bounds = manifest.get("bounds") or {}
    bx = float(bounds.get("x", 0.0))
    by = float(bounds.get("y", 0.0))
    bz = float(bounds.get("z", 0.0))

    # ---- 1. ground floor + perimeter walls, straight off `bounds` ---------------------
    if bx > 0 and by > 0:
        ft = float(profile["floor_thickness_m"])
        elements.append(_box_element(
            "floor", "BR_Floor_Ground", "bounds",
            "bounds x=%g y=%g; slab thickness %g m from profile" % (bx, by, ft),
            [tag, "BRBlockout", "BRFloor"],
            aabb([0.0, bx], [0.0, by], [-ft, 0.0]), cube))

        wt = float(profile["perimeter_wall_thickness_m"])
        walls = [
            ("South", aabb([-wt, bx + wt], [-wt, 0.0], [0.0, bz])),
            ("North", aabb([-wt, bx + wt], [by, by + wt], [0.0, bz])),
            ("West", aabb([-wt, 0.0], [0.0, by], [0.0, bz])),
            ("East", aabb([bx, bx + wt], [0.0, by], [0.0, bz])),
        ]
        for wname, wbox in walls:
            elements.append(_box_element(
                "wall", "BR_Wall_%s" % wname, "bounds",
                "perimeter wall from bounds (height %g m), thickness %g m from profile" % (bz, wt),
                [tag, "BRBlockout", "BRWall"], wbox, cube))

    # ---- 2. landmarks: geometry + a named marker per landmark ------------------------
    per_landmark = {}
    for s in solids:
        if s["kind"] == "cover":
            continue
        per_landmark.setdefault(s["source"], []).append(s)

    for source in sorted(per_landmark.keys(), key=lambda k: int(k[k.index("[") + 1:k.index("]")])):
        segs = per_landmark[source]
        name = segs[0]["name"]
        for n, s in enumerate(segs, start=1):
            # BN21: a stair volume becomes a walkable flight; everything else stays a solid.
            steps = stair_steps(s["box"]) if s["kind"] == "landmark_stair" else []
            if steps:
                for si, sbox in enumerate(steps, start=1):
                    elements.append(_box_element(
                        s["kind"], "BR_LM_%s_%02d_step%02d" % (slug(name), n, si), source,
                        "%s; BN21 tread %d/%d, rise <=%.2f m so the character WALKS it"
                        % (s["derivation"], si, len(steps), STAIR_MAX_RISE_M),
                        [tag, "BRBlockout", "BRLandmark", "BRStair", "Landmark=%s" % name],
                        sbox, cube, inferred=s["inferred"]))
                continue
            elements.append(_box_element(
                s["kind"], "BR_LM_%s_%02d" % (slug(name), n), source, s["derivation"],
                [tag, "BRBlockout", "BRLandmark", "Landmark=%s" % name], s["box"], cube,
                inferred=s["inferred"]))
        # one marker at the landmark's combined centroid: the callout name bots' EQS and
        # players' comms both use. Labels ARE callouts.
        allx = [v for s in segs for v in s["box"]["x"]]
        ally = [v for s in segs for v in s["box"]["y"]]
        allz = [v for s in segs for v in s["box"]["z"]]
        centroid = aabb_center(aabb(allx, ally, allz))
        elements.append(_element(
            "landmark_marker", "BR_LMK_%s" % slug(name), source,
            "centroid of %d parsed footprint(s) for landmark '%s'" % (len(segs), name),
            [tag, "BRBlockout", "BRLandmarkMarker", "Landmark=%s" % name],
            actor_class=classes["marker"],
            # marker sits on TOP of the landmark's tallest piece, so a callout marker is
            # never buried inside the volume it names.
            location_cm=[_r(centroid[0] * M_TO_CM), _r(centroid[1] * M_TO_CM), _r(max(allz) * M_TO_CM)],
            rotation=[0.0, 0.0, 0.0],
            landmark_name=name))

    # ---- 3. cover, minus anything a landmark footprint already builds ----------------
    tol = float(profile["colocation_tolerance_m"])
    landmark_boxes = [s for s in solids if s["kind"] != "cover"]
    for s in [s for s in solids if s["kind"] == "cover"]:
        dup = None
        for lb in landmark_boxes:
            if _colocated(s["box"], lb["box"], tol):
                dup = lb
                break
        if dup is not None:
            findings.append(Finding(
                WARN, "COVER_DUPLICATES_LANDMARK",
                "%s sits on landmark '%s' (%s) - the landmark footprint is authoritative (it carries "
                "real extents), so no second box is generated. Nothing is lost; the manifest simply "
                "describes this block twice." % (s["source"], dup["name"], dup["source"])))
            continue
        elements.append(_box_element(
            "cover", "BR_Cover_%02d_%s" % (s["index"] + 1, slug(s["name"].split("_")[1])),
            s["source"], s["derivation"], [tag, "BRBlockout", "BRCover"], s["box"], cube,
            inferred=True))  # the manifest gives a point; the extents come from the profile

    # ---- 4. spawns, with the scoring hints carried as actor tags ---------------------
    lift = float(profile["spawn_lift_m"])
    for i, sp in enumerate(manifest.get("spawn_points", []) or []):
        loc = sp.get("location") or {}
        if not all(a in loc for a in ("x", "y", "z")):
            continue
        sid = sp.get("id") or ("SP%02d" % (i + 1))
        hints = sp.get("scoring_hints") or {}
        tags = [tag, "BRBlockout", "BRSpawn", "SpawnId=%s" % sid]
        for k in sorted(hints.keys()):
            tags.append("%s=%s" % (k, hints[k]))
        elements.append(_element(
            "spawn", "BR_Spawn_%s" % slug(sid), "spawn_points[%d]" % i,
            "spawn point '%s'; yaw from facing; lifted %g m off the deck (profile)" % (sid, lift),
            tags,
            actor_class=classes["spawn"],
            location_cm=[_r(float(loc["x"]) * M_TO_CM),
                         _r(float(loc["y"]) * M_TO_CM),
                         _r((float(loc["z"]) + lift) * M_TO_CM)],
            rotation=[0.0, _r(float(sp.get("facing") or 0.0)), 0.0],
            scoring_hints=dict(hints),
            spawn_id=sid))

    # ---- 5. power-weapon node (only if the manifest actually gives a point) ----------
    node = resolve_rocket_node(manifest)
    if node is not None:
        elements.append(_element(
            "power_weapon_node", "BR_PowerWeapon_Rocket", "rocket_node",
            "manifest-supplied rocket node point",
            [tag, "BRBlockout", "BRPowerWeaponNode", "PowerWeapon=Rocket"],
            actor_class=classes["power_weapon_spawner"],
            fallback_class=classes["power_weapon_spawner_fallback"],
            location_cm=[_r(node[0] * M_TO_CM), _r(node[1] * M_TO_CM), _r(node[2] * M_TO_CM)],
            rotation=[0.0, 0.0, 0.0]))

    # ---- 6. nav bounds + test lighting ----------------------------------------------
    if bx > 0 and by > 0:
        margin = float(profile["nav_margin_m"])
        navbox = aabb([-margin, bx + margin], [-margin, by + margin], [-margin, bz + margin])
        c, s = aabb_center(navbox), aabb_size(navbox)
        base = float(assets["nav_brush_base_uu"])
        elements.append(_element(
            "nav_bounds", "BR_NavBounds", "bounds",
            "bounds + %g m margin; scaled off the %g uu default brush" % (margin, base),
            [tag, "BRBlockout", "BRNav"],
            actor_class=classes["nav_bounds"],
            location_cm=[_r(c[0] * M_TO_CM), _r(c[1] * M_TO_CM), _r(c[2] * M_TO_CM)],
            rotation=[0.0, 0.0, 0.0],
            scale=[_r(s[0] * M_TO_CM / base), _r(s[1] * M_TO_CM / base), _r(s[2] * M_TO_CM / base)]))

    lighting = profile["lighting"]
    elements.append(_element(
        "light", "BR_Sun", "profile.lighting",
        "test lighting - blockout readability only, not an art pass",
        [tag, "BRBlockout", "BRLight"],
        actor_class=classes["directional_light"],
        location_cm=[_r(bx * M_TO_CM / 2.0), _r(by * M_TO_CM / 2.0), _r((bz + 5.0) * M_TO_CM)],
        rotation=[_r(lighting["directional_pitch_deg"]), _r(lighting["directional_yaw_deg"]), 0.0],
        intensity=_r(lighting["directional_intensity_lux"])))
    elements.append(_element(
        "light", "BR_SkyLight", "profile.lighting",
        "test lighting - blockout readability only, not an art pass",
        [tag, "BRBlockout", "BRLight"],
        actor_class=classes["sky_light"],
        location_cm=[_r(bx * M_TO_CM / 2.0), _r(by * M_TO_CM / 2.0), _r((bz + 5.0) * M_TO_CM)],
        rotation=[0.0, 0.0, 0.0],
        intensity=_r(lighting["sky_light_intensity"])))

    # ---- inference audit -------------------------------------------------------------
    # Structural furniture (floor, walls, nav, lights, spawns) is a straight projection of
    # named manifest values and is not audited here. This flags only the elements whose
    # PLAYABLE extents the manifest does not fully determine.
    inferred = [e for e in elements if e.get("inferred")]
    if inferred:
        findings.append(Finding(
            ERROR if strict else WARN, "INFERRED_GEOMETRY",
            "%d element(s) got playable extents from prose parsing or the construction profile rather "
            "than explicit manifest numbers: %s. Each one's `derivation` says exactly how. Re-run with "
            "--strict to refuse to build them."
            % (len(inferred), ", ".join(sorted(e["label"] for e in inferred)))))

    plan = {
        "schema": "breachpoint.blockout.plan/1",
        "arena_id": manifest.get("arena_id"),
        "map_package": profile["map"]["package"],
        "generated_tag": tag,
        "profile_id": profile["profile_id"],
        "bounds_m": {"x": _r(bx), "y": _r(by), "z": _r(bz)},
        "elements": elements,
        "findings": [x.as_dict() for x in findings],
        "counts": {
            "elements": len(elements),
            "spawns": len([e for e in elements if e["kind"] == "spawn"]),
            "landmark_pieces": len([e for e in elements if e["kind"].startswith("landmark_")
                                    and e["kind"] != "landmark_marker"]),
            "landmark_markers": len([e for e in elements if e["kind"] == "landmark_marker"]),
            "cover": len([e for e in elements if e["kind"] == "cover"]),
        },
        "errors": len([x for x in findings if x.severity == ERROR]),
        "warnings": len([x for x in findings if x.severity == WARN]),
    }
    plan["digest"] = plan_digest(plan)
    return plan


def plan_digest(plan):
    """sha256 over the canonical element list - the determinism handle.

    Two runs of this generator agree iff their digests agree. It covers labels, tags,
    transforms and sizes; it deliberately does NOT cover findings text (advisory) or the
    .umap bytes (UE reserialises GUIDs on every save - see README, 'What determinism means').
    """
    payload = json.dumps(plan["elements"], sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def digest_manifest_file(path):
    with open(path, "rb") as fh:
        return hashlib.sha256(fh.read()).hexdigest()


# =====================================================================================
# io / cli
# =====================================================================================

def load_json(path, what):
    if not os.path.isfile(path):
        raise ManifestError("%s not found: %s" % (what, path))
    try:
        with open(path, "r", encoding="utf-8") as fh:
            return json.load(fh)  # object_pairs order preserved (py3.7+)
    except ValueError as exc:
        raise ManifestError("%s is not valid JSON (%s): %s" % (what, exc, path))


def repo_root():
    return os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def default_manifest():
    return os.path.join(repo_root(), "Content", "Data", "arena_manifest.json")


def default_profile():
    return os.path.join(os.path.dirname(os.path.abspath(__file__)), "blockout_profile.json")


def load_all(manifest_path=None, profile_path=None, strict=False):
    """The entry point build_arena.py uses. Returns (plan, manifest, profile, paths)."""
    mpath = os.path.abspath(manifest_path or default_manifest())
    ppath = os.path.abspath(profile_path or default_profile())
    manifest = load_json(mpath, "arena manifest")
    profile = load_json(ppath, "blockout profile")
    plan = build_plan(manifest, profile, strict=strict)
    plan["manifest_path"] = mpath
    plan["manifest_sha256"] = digest_manifest_file(mpath)
    plan["profile_path"] = ppath
    plan["profile_sha256"] = digest_manifest_file(ppath)
    return plan, manifest, profile


def print_report(plan, verbose=False):
    out = sys.stdout
    out.write("=" * 86 + "\n")
    out.write("BREACHPOINT blockout plan :: %s -> %s\n" % (plan.get("arena_id"), plan["map_package"]))
    out.write("=" * 86 + "\n")
    out.write("manifest      : %s\n" % plan.get("manifest_path"))
    out.write("manifest sha  : %s\n" % plan.get("manifest_sha256"))
    out.write("profile       : %s (%s)\n" % (plan.get("profile_id"), plan.get("profile_path")))
    out.write("plan digest   : %s\n" % plan["digest"])
    c = plan["counts"]
    out.write("elements      : %d total - %d spawn, %d landmark piece, %d landmark marker, %d cover\n"
              % (c["elements"], c["spawns"], c["landmark_pieces"], c["landmark_markers"], c["cover"]))
    out.write("\n---- findings (%d error, %d warn) ----\n" % (plan["errors"], plan["warnings"]))
    order = {ERROR: 0, WARN: 1, "info": 2}
    for fd in sorted(plan["findings"], key=lambda d: order.get(d["severity"], 3)):
        out.write("  %-5s %-26s %s\n" % (fd["severity"].upper(), fd["code"], fd["message"]))
    if verbose:
        out.write("\n---- elements (build order) ----\n")
        for e in plan["elements"]:
            out.write("  %-18s %-28s @ %s\n" % (e["kind"], e["label"], e.get("location_cm")))
            out.write("  %-18s   from %-18s : %s\n" % ("", e.get("source"), e.get("derivation")))
    out.write("\n")
    if plan["errors"]:
        out.write("VERDICT: FAIL - %d validation error(s). The blockout will NOT be built.\n"
                  "         Fix the MANIFEST (owner: BP13 / arena-architect), never the generator.\n"
                  % plan["errors"])
    else:
        out.write("VERDICT: PASS - manifest is buildable. This is a static (rung 1) check of the\n"
                  "         manifest and the plan, NOT a claim about a built level.\n")


def main(argv=None):
    ap = argparse.ArgumentParser(
        description="Validate arena_manifest.json and print/emit the blockout build plan. "
                    "Runs in plain CPython - no editor, no unreal module.")
    ap.add_argument("--manifest", default=None, help="path to arena_manifest.json")
    ap.add_argument("--profile", default=None, help="path to blockout_profile.json")
    ap.add_argument("--json", default=None, help="write the full plan JSON to this path")
    ap.add_argument("--strict", action="store_true",
                    help="promote inferred-geometry warnings to errors")
    ap.add_argument("--verbose", action="store_true", help="list every planned element")
    args = ap.parse_args(argv)

    try:
        plan, _manifest, _profile = load_all(args.manifest, args.profile, strict=args.strict)
    except ManifestError as exc:
        sys.stderr.write("BLOCKED: %s\n" % exc)
        return 3

    print_report(plan, verbose=args.verbose)
    if args.json:
        with open(args.json, "w", encoding="utf-8") as fh:
            json.dump(plan, fh, indent=2, sort_keys=True)
        sys.stdout.write("plan written: %s\n" % os.path.abspath(args.json))
    return 1 if plan["errors"] else 0


if __name__ == "__main__":
    sys.exit(main())
