#!/usr/bin/env python3
# =====================================================================================
# BREACHPOINT - build_arena.py :: execute a blockout plan into /Game/Maps/BR_Arena01
#
# Serves:   TICKET BP07 step 2. Runs INSIDE Unreal (it imports `unreal`).
# Law:      CLAUDE.md law 7 - blockouts are generated by committed scripts, never hand-
#           placed; one owner per binary, lock before editing.
# Doctrine: .claude/skills/ue-editor - "the manifest is the source of truth, the editor
#           state is its projection. Regenerate the projection; never let the projection
#           drift ahead of the source."
#
# This half is a DUMB EXECUTOR. Every decision - what to build, where, why, and whether the
# manifest is even legal - is made in arena_plan.py, which is plain CPython and reviewable
# without an editor. If you are debugging geometry, debug it there, not here.
#
# Headless (the crew's default):
#   UnrealEditor-Cmd.exe <repo>\Breachpoint.uproject ^
#       -run=pythonscript -script="<repo>\Tools\blockout\build_arena.py" ^
#       -stdout -unattended -nosplash -nop4
# The PowerShell wrapper Tools/blockout/build-arena.ps1 does exactly this, plus the
# engine-path resolution, the R21 "is an editor already running" guard, and logging.
#
# Exit codes: 0 built · 1 refused (validation errors / lock) · 3 blocked (bad input/env).
# =====================================================================================
"""Execute the validated blockout plan into the BR_Arena01 level."""

import argparse
import datetime
import json
import os
import shlex
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import arena_plan  # noqa: E402  (same directory; see sys.path line above)

try:
    import unreal
except ImportError:  # pragma: no cover - the whole point of the message
    sys.stderr.write(
        "BLOCKED: build_arena.py must run inside Unreal (it imports `unreal`).\n"
        "  Headless: UnrealEditor-Cmd Breachpoint.uproject -run=pythonscript "
        "-script=\"Tools/blockout/build_arena.py\" -stdout -unattended -nosplash\n"
        "  Or use the wrapper: Tools\\blockout\\build-arena.ps1\n"
        "  To check the MANIFEST without an editor, run arena_plan.py instead - it is\n"
        "  plain CPython and needs nothing installed.\n")
    sys.exit(3)


def log(msg):
    unreal.log("[BR-blockout] %s" % msg)


def warn(msg):
    unreal.log_warning("[BR-blockout] %s" % msg)


def err(msg):
    unreal.log_error("[BR-blockout] %s" % msg)


# =====================================================================================
# argument plumbing
# =====================================================================================

def parse_args():
    """Args reach a -run=pythonscript script inconsistently across launch shapes, so we
    accept them from sys.argv AND from BR_BLOCKOUT_ARGS (what the PS wrapper sets)."""
    ap = argparse.ArgumentParser(prog="build_arena.py")
    ap.add_argument("--manifest", default=None)
    ap.add_argument("--profile", default=None)
    ap.add_argument("--strict", action="store_true",
                    help="refuse to build any element whose extents were inferred")
    ap.add_argument("--dry-run", action="store_true",
                    help="validate and report; touch no asset")
    ap.add_argument("--no-lock-check", action="store_true",
                    help="skip the git-lfs lock check on the .umap (recorded in the report)")
    ap.add_argument("--report-dir", default=None)

    argv = [a for a in sys.argv[1:] if not a.startswith("-run=")]
    env_args = os.environ.get("BR_BLOCKOUT_ARGS", "").strip()
    if env_args:
        argv.extend(shlex.split(env_args))
    args, unknown = ap.parse_known_args(argv)
    if unknown:
        log("ignoring unrecognised args (engine flags): %s" % " ".join(unknown))
    return args


def repo_root():
    return os.path.normpath(unreal.Paths.convert_relative_path_to_full(unreal.Paths.project_dir()))


# =====================================================================================
# law 7: one owner per binary - lock before you touch it
# =====================================================================================

def umap_disk_path(package):
    rel = package[len("/Game/"):] if package.startswith("/Game/") else package.lstrip("/")
    return os.path.normpath(os.path.join(
        unreal.Paths.convert_relative_path_to_full(unreal.Paths.project_content_dir()), rel + ".umap"))


def check_lfs_lock(package, root):
    """Returns (ok, detail). A .umap that exists on disk must be locked by THIS user
    before we rewrite it - two writers on one binary is an unresolvable merge (law 7)."""
    path = umap_disk_path(package)
    if not os.path.isfile(path):
        return True, "map does not exist yet (first build) - lock it after the first commit: " \
                     "git lfs lock Content/Maps/BR_Arena01.umap"
    rel = os.path.relpath(path, root).replace("\\", "/")
    try:
        out = subprocess.check_output(["git", "lfs", "locks", "--json"], cwd=root,
                                      stderr=subprocess.STDOUT)
    except (OSError, subprocess.CalledProcessError) as exc:
        return False, "could not query git lfs locks (%s). Install git-lfs or re-run with " \
                      "--no-lock-check and say so in the ticket Log." % exc
    try:
        locks = json.loads(out.decode("utf-8") or "[]")
    except ValueError:
        return False, "git lfs locks returned unparseable output."
    for lk in locks or []:
        if str(lk.get("path", "")).replace("\\", "/") == rel:
            who = (lk.get("owner") or {}).get("name", "?")
            return True, "locked by %s" % who
    return False, "%s exists but is NOT lfs-locked. Run: git lfs lock %s" % (rel, rel)


# =====================================================================================
# editor helpers
# =====================================================================================

def resolve_class(path):
    for loader in (unreal.load_class, unreal.load_object):
        try:
            obj = loader(None, path)
            if obj:
                return obj
        except Exception:
            continue
    return None


def apply_identity(actor, element):
    """Label + tags. Labels ARE callouts (bots' EQS and players' comms both read them),
    and the tag set is the idempotency handle for the next re-run."""
    actor.set_actor_label(element["label"])
    actor.set_editor_property("tags", [unreal.Name(t) for t in element["tags"]])


def vec(triple):
    return unreal.Vector(float(triple[0]), float(triple[1]), float(triple[2]))


def rot(triple):
    # plan stores [pitch, yaw, roll]; unreal.Rotator takes (roll, pitch, yaw)
    return unreal.Rotator(float(triple[2]), float(triple[0]), float(triple[1]))


def clear_generated(actor_ss, tag):
    """Idempotency: destroy everything a previous run of THIS generator made, and report
    anything else that is sitting in the level (which, under law 7, should be nothing)."""
    removed, foreign = 0, []
    ignore = ("WorldSettings", "Brush", "WorldDataLayers", "WorldPartitionMiniMap",
              "LevelInstance", "LevelBounds", "DefaultPhysicsVolume")
    for actor in actor_ss.get_all_level_actors():
        tags = [str(t) for t in actor.get_editor_property("tags")]
        if tag in tags:
            actor_ss.destroy_actor(actor)
            removed += 1
            continue
        cname = actor.get_class().get_name()
        if not any(cname.startswith(p) for p in ignore):
            foreign.append("%s (%s)" % (actor.get_actor_label(), cname))
    return removed, foreign


# =====================================================================================
# element spawners - one per plan `kind`
# =====================================================================================

def spawn_box(actor_ss, element, cube_base_uu):
    mesh = unreal.EditorAssetLibrary.load_asset(element["asset"])
    if mesh is None:
        raise RuntimeError("missing blockout asset %s (element %s)" % (element["asset"], element["label"]))
    actor = actor_ss.spawn_actor_from_object(mesh, vec(element["location_cm"]), rot(element["rotation"]))
    size = element["size_cm"]
    actor.set_actor_scale3d(unreal.Vector(size[0] / cube_base_uu,
                                          size[1] / cube_base_uu,
                                          size[2] / cube_base_uu))
    apply_identity(actor, element)
    return actor


def spawn_from_class(actor_ss, element, class_path):
    cls = resolve_class(class_path)
    if cls is None:
        return None, None
    actor = actor_ss.spawn_actor_from_class(cls, vec(element["location_cm"]), rot(element["rotation"]))
    apply_identity(actor, element)
    return actor, class_path


def build(plan, profile, actor_ss, report):
    cube_base_uu = float(profile["assets"]["cube_base_size_m"]) * arena_plan.M_TO_CM
    built = {}
    for element in plan["elements"]:
        kind = element["kind"]
        try:
            if "asset" in element:
                spawn_box(actor_ss, element, cube_base_uu)

            elif kind == "power_weapon_node":
                actor, used = spawn_from_class(actor_ss, element, element["actor_class"])
                if actor is None:
                    actor, used = spawn_from_class(actor_ss, element, element["fallback_class"])
                    if actor is None:
                        raise RuntimeError("neither %s nor its fallback resolves"
                                           % element["actor_class"])
                    warn("%s is not compiled into this build - placed %s instead, tagged "
                         "BRPowerWeaponNode. Re-run this generator after the class lands (BP09)."
                         % (element["actor_class"], element["fallback_class"]))
                report.setdefault("class_substitutions", {})[element["label"]] = used

            elif kind == "nav_bounds":
                actor, _ = spawn_from_class(actor_ss, element, element["actor_class"])
                if actor is None:
                    raise RuntimeError("cannot resolve %s" % element["actor_class"])
                actor.set_actor_scale3d(vec(element["scale"]))

            elif kind == "light":
                actor, _ = spawn_from_class(actor_ss, element, element["actor_class"])
                if actor is None:
                    raise RuntimeError("cannot resolve %s" % element["actor_class"])
                comp = actor.get_component_by_class(unreal.LightComponentBase)
                if comp:
                    comp.set_editor_property("intensity", float(element["intensity"]))
                    if isinstance(comp, unreal.SkyLightComponent):
                        comp.set_editor_property("mobility", unreal.ComponentMobility.MOVABLE)
                        comp.recapture_sky()

            else:  # spawn, landmark_marker - plain class placements
                actor, _ = spawn_from_class(actor_ss, element, element["actor_class"])
                if actor is None:
                    raise RuntimeError("cannot resolve %s" % element["actor_class"])

            built[kind] = built.get(kind, 0) + 1
        except Exception as exc:
            err("FAILED to build %s (%s): %s" % (element["label"], kind, exc))
            report.setdefault("build_failures", []).append(
                {"label": element["label"], "kind": kind, "error": str(exc)})
    return built


# =====================================================================================
# main
# =====================================================================================

def main():
    args = parse_args()
    root = repo_root()
    stamp = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

    log("=" * 78)
    log("BREACHPOINT arena blockout generator - BP07")
    log("repo: %s" % root)

    try:
        plan, _manifest, profile = arena_plan.load_all(args.manifest, args.profile, strict=args.strict)
    except arena_plan.ManifestError as exc:
        err("BLOCKED: %s" % exc)
        return 3

    package = plan["map_package"]
    tag = plan["generated_tag"]
    report = {
        "schema": "breachpoint.blockout.report/1",
        "when": stamp,
        "map_package": package,
        "plan_digest": plan["digest"],
        "manifest_path": plan["manifest_path"],
        "manifest_sha256": plan["manifest_sha256"],
        "profile_sha256": plan["profile_sha256"],
        "strict": bool(args.strict),
        "dry_run": bool(args.dry_run),
        "findings": plan["findings"],
        "elements": plan["elements"],
    }

    log("manifest sha256: %s" % plan["manifest_sha256"])
    log("plan digest    : %s   <- re-runs are identical iff this is identical" % plan["digest"])
    log("elements       : %d" % plan["counts"]["elements"])
    for fd in plan["findings"]:
        (err if fd["severity"] == arena_plan.ERROR else
         warn if fd["severity"] == arena_plan.WARN else log)("%s: %s" % (fd["code"], fd["message"]))

    # --- refuse loudly on a bad manifest. A silently-built bad arena is worse than none.
    if plan["errors"]:
        err("REFUSING TO BUILD: %d validation error(s) above. The manifest is the source of "
            "truth and it is currently illegal; fix Content/Data/arena_manifest.json (owner: "
            "BP13 / arena-architect) and re-run. Do NOT patch this generator to get past it."
            % plan["errors"])
        write_report(report, args, root, stamp, verdict="refused-validation")
        return 1

    if args.dry_run:
        log("--dry-run: validation passed, no asset touched.")
        write_report(report, args, root, stamp, verdict="dry-run")
        return 0

    # --- law 7: the binary has one owner and must be locked before we rewrite it -------
    if args.no_lock_check:
        warn("--no-lock-check: proceeding WITHOUT verifying the .umap lfs lock. Two writers on "
             "one binary is an unresolvable merge - say in the ticket Log why this was safe.")
        report["lock"] = "skipped"
    else:
        ok, detail = check_lfs_lock(package, root)
        report["lock"] = detail
        if not ok:
            err("REFUSING TO BUILD: %s" % detail)
            write_report(report, args, root, stamp, verdict="refused-lock")
            return 1
        log("lfs lock: %s" % detail)

    level_ss = unreal.get_editor_subsystem(unreal.LevelEditorSubsystem)
    actor_ss = unreal.get_editor_subsystem(unreal.EditorActorSubsystem)

    if unreal.EditorAssetLibrary.does_asset_exist(package):
        log("opening existing level %s" % package)
        if not level_ss.load_level(package):
            err("BLOCKED: could not load %s" % package)
            return 3
        report["level"] = "existing"
    else:
        log("creating new level %s" % package)
        if not level_ss.new_level(package):
            err("BLOCKED: could not create %s" % package)
            return 3
        report["level"] = "created"

    # --- clear-and-rebuild: THE determinism mechanism ---------------------------------
    removed, foreign = clear_generated(actor_ss, tag)
    log("cleared %d actor(s) tagged '%s'" % (removed, tag))
    report["cleared"] = removed
    report["foreign_actors"] = foreign
    if foreign:
        warn("%d actor(s) in this level were NOT generated by this script and were left alone: %s. "
             "Law 7 says a blockout is generated, never hand-placed - either delete them or move "
             "what they represent into arena_manifest.json." % (len(foreign), ", ".join(foreign[:20])))

    built = build(plan, profile, actor_ss, report)
    report["built"] = built
    log("built: %s" % ", ".join("%s=%d" % (k, built[k]) for k in sorted(built)))

    if not level_ss.save_current_level():
        err("BLOCKED: save_current_level() failed for %s" % package)
        write_report(report, args, root, stamp, verdict="save-failed")
        return 3
    log("saved %s" % package)

    write_report(report, args, root, stamp, verdict="built")
    log("DONE. This is a generated artifact, not a verified one: the script exiting 0 means the "
        "actors were placed and the level saved. Reachability, sightlines and the manifest's own "
        "doubts[] are a rung-3 walkthrough (BP07 step 4), not a script exit code.")
    return 0 if not report.get("build_failures") else 1


def write_report(report, args, root, stamp, verdict):
    report["verdict"] = verdict
    out_dir = args.report_dir or os.path.join(root, "Saved", "Blockout")
    try:
        if not os.path.isdir(out_dir):
            os.makedirs(out_dir)
        path = os.path.join(out_dir, "blockout-%s-%s.json" % (stamp, verdict))
        with open(path, "w", encoding="utf-8") as fh:
            json.dump(report, fh, indent=2, sort_keys=True)
        log("report: %s" % path)
    except OSError as exc:
        warn("could not write build report: %s" % exc)


if __name__ == "__main__":
    sys.exit(main())
