"""BR_Spillway - the generator. Design in, placements out. No engine required.

    python3 Tools/blockout/gen_spillway.py            # writes both JSONs
    python3 Tools/blockout/gen_spillway.py --summary  # design report, writes nothing

CLAUDE.md law 7: "Blockouts ... are generated by committed scripts, never hand-placed."
This file IS the level. `Content/Maps/BR_Spillway.umap` is its projection; the landing
mechanism is `Tools/blockout/land_spillway.py`. To change the arena, change this file and
re-run both - never drag a cube in the editor.

LINEAGE
    /Game/Variant_Shooter/Lvl_Shooter was duplicated to /Game/Maps/BR_Spillway so the new
    arena inherits the template's lighting rig (DirectionalLight, SkyLight, SkyAtmosphere,
    VolumetricCloud, ExponentialHeightFog, PostProcessVolume, SM_SkySphere) and its
    World Partition setup. Every piece of PLAYABLE geometry below is built from the
    template's own prototyping kit - /Game/LevelPrototyping/Meshes - with the template's
    own material instances, so the new map reads as the same visual family.

    Measured baseline (read out of the live editor, 31 Aug 2026):
        Lvl_Shooter playable geometry  30.0 x 36.0 x  8.0 m   (~1,080 m2, 97 meshes)
        BR_Spillway  rev A             60.0 x 48.0 x 16.0 m   (~2,880 m2)
        BR_Spillway  rev B (this)      80.0 x 60.0 x 20.0 m   (~4,800 m2, five tiers)

REV B - founder note, 31 Aug 2026: "keep in mind the space you may need to make it a bit
bigger and enough space on areas. like ramps, stairs, underground, etc."
    - envelope 60 x 48 -> 80 x 60 m; footprint 2.67x -> 4.44x the template
    - every main ramp widened 4 m -> 6 m, gallery corridors 4 m -> 6 m, tower 20 -> 24 m
    - a fifth tier ADDED BELOW GROUND at -4 m: THE CULVERT, a chamber under the tower with
      three tunnels off it and four ramps back to daylight. Total vertical range is now
      -4 m to +16 m, and the tower is a shaft you can fight down as well as up.

MESH FACTS (measured via StaticMeshTools.get_bounds, not assumed)
    SM_Cube             100 x 100 x 100 uu, pivot at the MIN CORNER (0,0,0)
    SM_Ramp             100 x 100 x 100 uu, pivot at the MIN CORNER; the surface is HIGH at
                        local y=0 and LOW at local y=100 - it rises along local -Y.
                        run = 100*scale.y, width = 100*scale.x, rise = 100*scale.z.
                        (Probed in-editor with SceneTools.trace_world; see the Log.)
    SM_Cylinder         100 dia x 100 h, pivot at centre-bottom
    SM_ChamferCube      100 cube, pivot at CENTRE

TRAVERSAL BUDGET (Config/DefaultEngine.ini, and why every tier is exactly 4 m apart)
    JumpZVelocity 420 -> apex 90 uu. A player cannot jump onto anything.
    NavLink BN_Climb  JumpHeight 90    -> bots climb 0.9 m, so UP is ramps only.
    NavLink BN_Drop   JumpMaxDepth 1000 -> bots drop at most 10 m in one link.
    Therefore tiers sit at z = -400 / 0 / 400 / 800 / 1200: every inter-tier drop is
    400 uu, comfortably inside the drop cap, and every climb has a ramp.
    All ramps are 2:1 (400 rise over 800 run = 26.6 deg), safely under the 44.765 deg
    walkable limit. The template's own 45 deg ramps are deliberately NOT copied.

AXES: +X east, +Y north, +Z up. Origin is the centre of the arena.
"""

import json
import math
import os
import sys

# ---------------------------------------------------------------------------
# Assets - all inherited from Lvl_Shooter, none authored for this map.
# ---------------------------------------------------------------------------
CUBE = "/Game/LevelPrototyping/Meshes/SM_Cube"
RAMP = "/Game/LevelPrototyping/Meshes/SM_Ramp"
CYL = "/Game/LevelPrototyping/Meshes/SM_Cylinder"
CHAMFER = "/Game/LevelPrototyping/Meshes/SM_ChamferCube"

MAT_DECK = "/Game/LevelPrototyping/Materials/MI_PrototypeGrid_TopDark"   # walking surfaces
MAT_WALL = "/Game/LevelPrototyping/Materials/MI_PrototypeGrid_Gray"      # vertical mass
MAT_TEAM = "/Game/FirstPerson/MI_FirstPersonColorway"                    # accents, ramps

# The arena is placed with material VARIANTS of the meshes above rather than with
# per-actor material overrides. That is not a preference: through the editor's MCP server
# ObjectTools.set_properties cannot write the components of World Partition external
# actors at all - it returns false and changes nothing, for `overrideMaterials`,
# `overlayMaterial`, `minLOD` and `bOverrideMinLOD` alike. So the colour rides on the
# asset. Each variant is a duplicate of the template mesh above with one slot repointed;
# the geometry is identical. Built by Tools/blockout/make_spillway_meshes.py.
VARIANT = {
    (CUBE, MAT_DECK): "/Game/Spillway/Meshes/SM_SPW_Deck",
    (CUBE, MAT_WALL): "/Game/Spillway/Meshes/SM_SPW_Wall",
    (CUBE, MAT_TEAM): "/Game/Spillway/Meshes/SM_SPW_Accent",
    (RAMP, MAT_TEAM): "/Game/Spillway/Meshes/SM_SPW_Ramp",
    (RAMP, MAT_DECK): "/Game/Spillway/Meshes/SM_SPW_Ramp",
    (CYL, MAT_WALL): "/Game/Spillway/Meshes/SM_SPW_Pillar",
    (CYL, MAT_TEAM): "/Game/Spillway/Meshes/SM_SPW_Pillar",
    (CHAMFER, MAT_TEAM): "/Game/Spillway/Meshes/SM_SPW_Crate",
    (CHAMFER, MAT_WALL): "/Game/Spillway/Meshes/SM_SPW_Crate",
}

TAG = "SpillwayGenerated"
MAP_PATH = "/Game/Maps/BR_Spillway"
ARENA_ID = "breachpoint_spillway"

# ---------------------------------------------------------------------------
# The envelope
# ---------------------------------------------------------------------------
HX, HY = 4400.0, 4000.0          # half-extents: 88 m x 80 m (rev D: bigger, squarer)
WALL_T = 100.0
# Perimeter wall: 10 m, chosen against two constraints rather than picked. High enough
# that nobody steps onto it from the tallest roof (the gallery at 8 m - a 2 m lip, and the
# jump apex is 0.9 m), low enough that the crown at 12 m genuinely overlooks the arena.
WALL_H = 1000.0
FLOOR_T = 100.0                  # ground slab thickness (top face at z = 0)
DECK_T = 100.0                   # deck slab thickness (top face at the tier height)

TB = -500.0                      # THE CULVERT - 4 m of headroom, not 3
T0, T1, T2, T3 = 0.0, 400.0, 800.0, 1200.0
TIERS = (TB, T0, T1, T2, T3)
# Crouch cover. Tall enough to break a standing silhouette, low enough to shoot over. The
# first draft used a 4 m parapet on the crown and the screenshot refuted it - standing on
# the power weapon you could not see the arena at all.
COVER_H = 110.0
MAST_TOP = 1600.0                # the arena's high point, on the tower

# Zone bands in Y
LANE_N = -1800.0                 # south lane    y in [-3000, -1400]   16 m deep
GALLERY_S = 1800.0               # north gallery y in [ 1400,  3000]   16 m deep
                                 # mid band      y in [-1400,  1400]   28 m deep

# The tower
TW = 1400.0                      # half-extent -> 28 x 28 m
CORE = 700.0                     # core ROOM half-extent -> 14 x 14 m

# Circulation. REV B widened every main route: a 4 m ramp with two players on it is a
# traffic jam, and 4 m corridors made the gallery a shooting tube rather than a building.
RAMP_RUN = 800.0                 # 2:1 against a 400 rise
RAMP_W = 600.0                   # main routes
RAMP_W_SIDE = 400.0              # side routes only
CORRIDOR_W = 600.0

GAL_X = 3800.0                   # gallery stops short of the walls; the gaps are stairs

_elements = []
_ground_holes = []               # rects the ground slab must NOT cover (culvert shafts)
_dropped = []                    # props the generator refused to place, and why not


# ---------------------------------------------------------------------------
# Primitives. Every helper takes a world-space AABB and emits one actor.
# ---------------------------------------------------------------------------
def _push(rec):
    _elements.append(rec)
    return rec


def box(x0, y0, z0, x1, y1, z1, mat, label, folder):
    """An axis-aligned solid. SM_Cube's pivot is its min corner, so this is exact."""
    assert x1 > x0 and y1 > y0 and z1 > z0, "degenerate box %s" % label
    return _push({
        "kind": "box", "label": label, "folder": folder,
        "mesh": CUBE, "material": mat,
        "loc": [round(x0, 2), round(y0, 2), round(z0, 2)],
        "rot": [0.0, 0.0, 0.0],
        "scale": [round((x1 - x0) / 100.0, 6),
                  round((y1 - y0) / 100.0, 6),
                  round((z1 - z0) / 100.0, 6)],
        "aabb": [x0, y0, z0, x1, y1, z1],
    })


def deck(x0, y0, x1, y1, top, label, folder, mat=MAT_DECK, thick=DECK_T):
    """A walking surface whose TOP face lands exactly on `top`."""
    return box(x0, y0, top - thick, x1, y1, top, mat, label, folder)


def wall(x0, y0, x1, y1, z0, z1, label, folder, mat=MAT_WALL):
    return box(x0, y0, z0, x1, y1, z1, mat, label, folder)


def slab_with_holes(x0, y0, x1, y1, top, holes, label, folder,
                    mat=MAT_DECK, thick=DECK_T):
    """A deck with rectangular voids cut out of it - the shafts down to the culvert.

    Decomposes the rectangle on every hole edge, drops the cells that fall inside a hole,
    and merges what is left into horizontal runs, so the slab stays a handful of actors
    rather than a grid of hundreds.
    """
    xs = sorted({x0, x1} | {v for h in holes for v in (h[0], h[2]) if x0 < v < x1})
    ys = sorted({y0, y1} | {v for h in holes for v in (h[1], h[3]) if y0 < v < y1})
    n = 0
    for j in range(len(ys) - 1):
        run = None
        for i in range(len(xs) - 1):
            cx, cy = (xs[i] + xs[i + 1]) / 2.0, (ys[j] + ys[j + 1]) / 2.0
            void = any(h[0] < cx < h[2] and h[1] < cy < h[3] for h in holes)
            if not void:
                run = xs[i] if run is None else run
            elif run is not None:
                box(run, ys[j], top - thick, xs[i], ys[j + 1], top, mat,
                    "%s_%02d" % (label, n), folder)
                n += 1
                run = None
        if run is not None:
            box(run, ys[j], top - thick, xs[-1], ys[j + 1], top, mat,
                "%s_%02d" % (label, n), folder)
            n += 1
    return n


def ramp(x0, y0, x1, y1, base, rise, up, label, folder, mat=MAT_TEAM):
    """A walkable ramp filling the AABB, rising toward `up` in {'+X','-X','+Y','-Y'}.

    SM_Ramp is high at local y=0 and low at local y=+run, so the yaw and the pivot corner
    are chosen per direction. Derived once, verified by trace_world.
    """
    w_x, w_y = x1 - x0, y1 - y0
    if up == "-Y":                       # high edge at y0
        yaw, loc, scale, run = 0.0, (x0, y0, base), (w_x, w_y, rise), w_y
    elif up == "+Y":                     # high edge at y1
        yaw, loc, scale, run = 180.0, (x1, y1, base), (w_x, w_y, rise), w_y
    elif up == "+X":                     # high edge at x1
        yaw, loc, scale, run = 90.0, (x1, y0, base), (w_y, w_x, rise), w_x
    elif up == "-X":                     # high edge at x0
        yaw, loc, scale, run = -90.0, (x0, y1, base), (w_y, w_x, rise), w_x
    else:
        raise ValueError("up must be +X/-X/+Y/-Y, got %r" % up)

    slope = math.degrees(math.atan2(rise, run))
    assert slope <= 30.0, "%s is %.1f deg - too steep" % (label, slope)
    return _push({
        "kind": "ramp", "label": label, "folder": folder,
        "mesh": RAMP, "material": mat,
        "loc": [round(v, 2) for v in loc],
        "rot": [0.0, yaw, 0.0],
        "scale": [round(scale[0] / 100.0, 6), round(scale[1] / 100.0, 6),
                  round(scale[2] / 100.0, 6)],
        "aabb": [x0, y0, base, x1, y1, base + rise],
        "slope_deg": round(slope, 2), "up": up,
        "width_uu": w_y if up in ("+X", "-X") else w_x,
    })


def pillar(cx, cy, z0, z1, dia, label, folder, mat=MAT_WALL):
    return _push({
        "kind": "pillar", "label": label, "folder": folder,
        "mesh": CYL, "material": mat,
        "loc": [round(cx, 2), round(cy, 2), round(z0, 2)],
        "rot": [0.0, 0.0, 0.0],
        "scale": [round(dia / 100.0, 6), round(dia / 100.0, 6),
                  round((z1 - z0) / 100.0, 6)],
        "aabb": [cx - dia / 2, cy - dia / 2, z0, cx + dia / 2, cy + dia / 2, z1],
    })


def crate(cx, cy, z0, size, label, folder, mat=MAT_TEAM):
    """Chamfered block - reads as a prop, not architecture. Pivot is the centre."""
    return _push({
        "kind": "crate", "label": label, "folder": folder,
        "mesh": CHAMFER, "material": mat,
        "loc": [round(cx, 2), round(cy, 2), round(z0 + size / 2.0, 2)],
        "rot": [0.0, 0.0, 0.0],
        "scale": [round(size / 100.0, 6)] * 3,
        "aabb": [cx - size / 2, cy - size / 2, z0, cx + size / 2, cy + size / 2, z0 + size],
    })


def crate_if_clear(cx, cy, z0, size, label, folder, mat=MAT_TEAM):
    """A crate, but only if nothing is already there.

    Loose props were hand-placed for three revisions and every layout change started a
    round of whack-a-mole with the overlap gate. The generator checks for itself now: a
    crate that would clash, or that would stand on a shaft mouth, is simply not placed,
    and the summary says how many were dropped. Cover density is a nice-to-have; a crate
    fused into a ramp is a defect.
    """
    h = size / 2.0
    box_ = (cx - h, cy - h, z0, cx + h, cy + h, z0 + size)
    for e in _elements:
        ax0, ay0, az0, ax1, ay1, az1 = e["aabb"]
        if (min(box_[3], ax1) - max(box_[0], ax0) > 1.0
                and min(box_[4], ay1) - max(box_[1], ay0) > 1.0
                and min(box_[5], az1) - max(box_[2], az0) > 1.0):
            _dropped.append(label)
            return None
    for _, sx0, sy0, sx1, sy1, _u in SHAFTS:
        if (min(box_[3], sx1) - max(box_[0], sx0) > 1.0
                and min(box_[4], sy1) - max(box_[1], sy0) > 1.0
                and box_[5] > T0 >= box_[2] - 1.0):
            _dropped.append(label)
            return None
    return crate(cx, cy, z0, size, label, folder, mat)


# ---------------------------------------------------------------------------
# 1. THE CULVERT - the tier below ground. Built FIRST because it decides where the
#    holes in the ground slab go.
# ---------------------------------------------------------------------------
#   Floor top -500, ceiling -100: 4 m of headroom. Rev C gave it 3 m and it read as a
#   crawlspace; the founder asked for room in the tight places, so the floor dropped 1 m.
#   The drop from the surface is now 500 uu, still half the 1000 uu bot drop cap.
CULVERT_ROOMS = [
    ("Chamber", -1400.0, -1400.0, 1400.0, 1400.0),      # under the tower, 28 x 28 m
    ("Tunnel_W", -3200.0, -600.0, -1400.0, 600.0),      # 18 x 12 m
    ("Tunnel_E", 1400.0, -600.0, 3200.0, 600.0),
    ("Tunnel_S", -1400.0, -2800.0, -400.0, -1400.0),    # 10 x 14 m
]

# Each shaft is a hole in the ground slab with a ramp in it. The ramp's HIGH edge sits on
# the hole edge, so you step off solid ground straight onto the top of the ramp. 1000 uu
# of run against the 500 uu drop keeps every one of them at the same 26.6 degrees.
SHAFTS = [
    # label            x0       y0       x1       y1    up
    ("Shaft_W", -3000.0, -600.0, -2000.0, 0.0, "-X"),
    ("Shaft_E", 2000.0, 0.0, 3000.0, 600.0, "+X"),
    ("Shaft_S", -1400.0, -2800.0, -800.0, -1800.0, "-Y"),
    ("Shaft_Core", -500.0, -600.0, 100.0, 400.0, "+Y"),   # inside the tower's core room
]

CULVERT_WALLS = [
    (-1400, 1400, 1400, 1500),                                    # chamber N
    (-400, -1500, 1400, -1400),                                   # chamber S (tunnel takes W half)
    (-1500, -1400, -1400, -600), (-1500, 600, -1400, 1400),       # chamber W, split
    (1400, -1400, 1500, -600), (1400, 600, 1500, 1400),           # chamber E, split
    (-3200, 600, -1500, 700), (-3200, -700, -1500, -600),
    (-3300, -600, -3200, 600),                                    # west tunnel
    (1500, 600, 3200, 700), (1500, -700, 3200, -600),
    (3200, -600, 3300, 600),                                      # east tunnel
    (-1500, -2800, -1400, -1500), (-400, -2800, -300, -1500),
    (-1400, -2900, -400, -2800),                                  # south tunnel
]


def build_culvert():
    F = "Spillway/05_Culvert"
    for nm, x0, y0, x1, y1 in CULVERT_ROOMS:
        deck(x0, y0, x1, y1, TB, "SPW_Culvert_%s" % nm, F)
    for i, (x0, y0, x1, y1) in enumerate(CULVERT_WALLS):
        wall(x0, y0, x1, y1, TB, T0 - FLOOR_T, "SPW_Culvert_Wall_%02d" % i, F)
    for cx, cy in ((-900, -900), (900, -900), (-900, 900), (900, 900)):
        pillar(cx, cy, TB, T0 - FLOOR_T, 180, "SPW_Culvert_Pier_%d_%d" % (cx, cy), F)
    for i, (cx, cy) in enumerate(((400, -1100), (-400, 1100), (-1800, 0), (1800, 0))):
        crate_if_clear(cx, cy, TB, 240, "SPW_Culvert_Crate_%d" % i, F)
    for i, (x0, y0, x1, y1) in enumerate(((-1200, -200, -500, -80),
                                          (500, 80, 1200, 200))):
        box(x0, y0, TB, x1, y1, TB + COVER_H, MAT_WALL, "SPW_Culvert_Cover_%d" % i, F)
    for nm, x0, y0, x1, y1, up in SHAFTS:
        _ground_holes.append((x0, y0, x1, y1))
        ramp(x0, y0, x1, y1, TB, -TB, up, "SPW_%s_Ramp" % nm, F)


# ---------------------------------------------------------------------------
# 2. THE ENVELOPE - ground slab (holed for the shafts) and perimeter
# ---------------------------------------------------------------------------
def build_envelope():
    F = "Spillway/00_Envelope"
    slab_with_holes(-HX, -HY, HX, HY, T0, _ground_holes, "SPW_Ground", F, thick=FLOOR_T)
    wall(-HX - WALL_T, -HY - WALL_T, HX + WALL_T, -HY, T0, WALL_H, "SPW_Wall_S", F)
    wall(-HX - WALL_T, HY, HX + WALL_T, HY + WALL_T, T0, WALL_H, "SPW_Wall_N", F)
    wall(-HX - WALL_T, -HY, -HX, HY, T0, WALL_H, "SPW_Wall_W", F)
    wall(HX, -HY, HX + WALL_T, HY, T0, WALL_H, "SPW_Wall_E", F)


# ---------------------------------------------------------------------------
# 3. THE TOWER - the hub. Its core is a ROOM, not a block.
# ---------------------------------------------------------------------------
def build_tower():
    F = "Spillway/10_Tower"

    # The core was a 12 x 12 m solid cube - the worst of the "big square with nothing on
    # it" the founder called out. It is now a room you fight inside, with the shaft to the
    # culvert in its floor, so the tower is entered at five levels instead of four. Its
    # east and west faces stay solid, which is what kills the cross-map sightline; the
    # doorways face north and south, along the axis that was never the problem.
    D = 250.0                       # half-width of each doorway -> 5 m clear
    wall(-CORE, -CORE, -D, -CORE + 100, T0, T1 - DECK_T, "SPW_Core_S_a", F)
    wall(D, -CORE, CORE, -CORE + 100, T0, T1 - DECK_T, "SPW_Core_S_b", F)
    wall(-CORE, CORE - 100, -D, CORE, T0, T1 - DECK_T, "SPW_Core_N_a", F)
    wall(D, CORE - 100, CORE, CORE, T0, T1 - DECK_T, "SPW_Core_N_b", F)
    wall(-CORE, -CORE + 100, -CORE + 100, CORE - 100, T0, T1 - DECK_T, "SPW_Core_W", F)
    wall(CORE - 100, -CORE + 100, CORE, CORE - 100, T0, T1 - DECK_T, "SPW_Core_E", F)

    # Two opposite quadrants stay solid - their top IS the tier-1 deck, so they carry a
    # path rather than being dead mass. The other two are colonnade.
    for sx, sy, nm in ((-1, -1, "SW"), (1, 1, "NE")):
        x0, x1 = sorted((sx * TW, sx * CORE))
        y0, y1 = sorted((sy * TW, sy * CORE))
        box(x0, y0, T0, x1, y1, T1 - DECK_T, MAT_WALL, "SPW_Tower_Corner_%s" % nm, F)
    for cx, cy in ((1050, -1050), (350, -1250), (-350, -1250),
                   (-1050, 1050), (350, 1250), (-350, 1250)):
        pillar(cx, cy, T0, T1 - DECK_T, 170, "SPW_Tower_Col_%d_%d" % (cx, cy), F)

    deck(-TW, -TW, TW, TW, T1, "SPW_Tower_Deck_T1", F)
    box(-CORE, -CORE, T1, CORE, CORE, T2 - DECK_T, MAT_WALL, "SPW_Tower_Core_T1", F)
    box(-TW, -TW, T1, -300, -1000, T2 - DECK_T, MAT_WALL, "SPW_Tower_Mass_S", F)
    box(300, 1000, T1, TW, TW, T2 - DECK_T, MAT_WALL, "SPW_Tower_Mass_N", F)

    ramp(-TW, -700, -TW + RAMP_W, 100, T1, T1, "+Y", "SPW_Tower_Ramp_T1_T2", F)
    deck(-TW, 100, TW, TW, T2, "SPW_Tower_Deck_T2", F)
    ramp(TW - RAMP_W, 0, TW, 800, T2, T1, "-Y", "SPW_Tower_Ramp_T2_T3", F)
    deck(-1200, -1200, 1200, 0, T3, "SPW_Tower_Crown", F)
    for cx in (-1100, -400, 400, 1100):
        pillar(cx, -900, T1, T3 - DECK_T, 150, "SPW_Tower_Pillar_%d" % cx, F)

    P = 40.0
    wall(-1200, -1200, 1200, -1200 + P, T3, T3 + COVER_H, "SPW_Crown_Parapet_S", F, MAT_TEAM)
    wall(-1200, -1200, -1200 + P, 0, T3, T3 + COVER_H, "SPW_Crown_Parapet_W", F, MAT_TEAM)
    wall(1200 - P, -1200, 1200, 0, T3, T3 + COVER_H, "SPW_Crown_Parapet_E", F, MAT_TEAM)
    box(-150, -600, T3, 150, -300, T3 + 40, MAT_TEAM, "SPW_Crown_Plinth", F)
    box(-1000, -1000, T3, -500, -500, MAST_TOP, MAT_WALL, "SPW_Crown_Mast", F)

    ramp(-2200, 400, -TW, 1000, T0, T1, "+X", "SPW_Tower_Ramp_W", F)
    ramp(TW, -1000, 2200, -400, T0, T1, "-X", "SPW_Tower_Ramp_E", F)


# ---------------------------------------------------------------------------
# 4. THE BASES - open pavilions
# ---------------------------------------------------------------------------
def _base(sign, name):
    """Authored in WEST coordinates; sign=-1 is the 180-degree rotation about Z."""
    F = "Spillway/20_Base_%s" % name

    def rect(x0, y0, x1, y1):
        a, b = sorted((sign * x0, sign * x1))
        c, d = sorted((sign * y0, sign * y1))
        return a, c, b, d

    a, c, b, d = rect(-4400, -2000, -3000, 2000)
    deck(a, c, b, d, T1, "SPW_%s_Roof" % name, F)
    a, c, b, d = rect(-4390, -1900, -4300, 1900)
    box(a, c, T0, b, d, T1 - DECK_T, MAT_TEAM, "SPW_%s_Backsplash" % name, F)

    # x = -3100 and not -3050: the shaft mouth reaches x = -3000, and a pillar clipping
    # its lip is a sealed shaft as far as the gate is concerned - correctly so.
    for i, (px, py) in enumerate(((-3100, -1250), (-3100, -400), (-3100, 400),
                                  (-3100, 1250), (-3750, -1950), (-3750, 1950))):
        a, c, _, _ = rect(px, py, px + 1, py + 1)
        pillar(a, c, T0, T1 - DECK_T, 190, "SPW_%s_Pillar_%d" % (name, i), F)

    for tag, y0, y1 in (("A", -2000, -1400), ("B", 1400, 2000)):
        a, c, b, d = rect(-3000, y0, -2200, y1)
        ramp(a, c, b, d, T0, T1, "-X" if sign > 0 else "+X",
             "SPW_%s_Ramp_%s" % (name, tag), F)

    a, c, b, d = rect(-3800, -900, -3700, 900)
    box(a, c, T1, b, d, T1 + COVER_H, MAT_WALL, "SPW_%s_Roof_Cover" % name, F)

    a, c, b, d = rect(-3000, -300, -TW, 300)
    deck(a, c, b, d, T1, "SPW_%s_Bridge" % name, F)


def build_bases():
    _base(1, "West")
    _base(-1, "East")


# ---------------------------------------------------------------------------
# 5. THE SPILLWAY - the south lane
# ---------------------------------------------------------------------------
def build_south_lane():
    F = "Spillway/30_SouthLane"

    # THE BLOCKHOUSE, which replaces rev C's 10 x 8 x 8 m solid centre mass. Same job -
    # it stands in the middle of the lane and breaks the long shot - but you can go
    # through it at ground level and stand on it at tier 1, so it is a position instead
    # of an obstacle. This is the pattern the founder asked for: no big square with no
    # path on it.
    for tag, (x0, y0, x1, y1) in (("S_a", (-800, -3100, -300, -3000)),
                                  ("S_b", (300, -3100, 800, -3000)),
                                  ("N_a", (-800, -2400, -300, -2300)),
                                  ("N_b", (300, -2400, 800, -2300)),
                                  ("W", (-800, -3000, -700, -2400)),
                                  ("E", (700, -3000, 800, -2400))):
        wall(x0, y0, x1, y1, T0, T1 - DECK_T, "SPW_Block_%s" % tag, F)
    deck(-800, -3100, 800, -2300, T1, "SPW_Block_Roof", F)
    ramp(-1600, -3100, -800, -2500, T0, T1, "+X", "SPW_Block_Ramp", F)
    box(-500, -2500, T1, 500, -2400, T1 + COVER_H, MAT_WALL, "SPW_Block_Cover", F)

    # The two side masses are plinths whose tops join the shelf, so they carry the flank
    # route rather than blocking it.
    for sign, nm in ((1, "W"), (-1, "E")):
        a, b = sorted((sign * -3100, sign * -2300))
        deck(a, -3400, b, -2800, T1, "SPW_Lane_Plinth_%s" % nm, F)
        box(a, -3400, T0, b, -2800, T1 - DECK_T, MAT_WALL, "SPW_Lane_Plinth_%s_base" % nm, F)

    deck(-2300, -HY, 2300, -3400, T1, "SPW_Shelf", F)
    ramp(-3100, -HY, -2300, -HY + RAMP_W, T0, T1, "+X", "SPW_Shelf_Ramp_W", F)
    ramp(2300, -HY, 3100, -HY + RAMP_W, T0, T1, "-X", "SPW_Shelf_Ramp_E", F)
    wall(-2300, -3460, 2300, -3400, T1, T1 + COVER_H, "SPW_Shelf_Rail", F, MAT_TEAM)
    for i, x in enumerate((-1400, 0, 1400)):
        box(x - 400, -3800, T1, x + 400, -3700, T1 + COVER_H, MAT_WALL,
            "SPW_Shelf_Cover_%d" % i, F)
    for i, (cx, cy) in enumerate(((-1800, -2600), (1800, -2600), (-3700, -2900),
                                  (3700, -2900), (0, -2000))):
        crate_if_clear(cx, cy, T0, 240, "SPW_Lane_Crate_%d" % i, F)


# ---------------------------------------------------------------------------
# 6. THE GALLERY - a hypostyle hall
# ---------------------------------------------------------------------------
def build_gallery():
    F = "Spillway/40_Gallery"
    deck(-GAL_X, GALLERY_S, GAL_X, HY, T2, "SPW_Gal_Roof", F)
    for i, px in enumerate((-3300, -2200, -1100, 0, 1100, 2200, 3300)):
        for j, py in enumerate((2300, 3400)):
            pillar(px, py, T0, T2 - DECK_T, 190, "SPW_Gal_Col_%d_%d" % (i, j), F)
    for i, (x0, x1, y0) in enumerate(((-2900, -2200, 2800), (-1300, -600, 2800),
                                      (600, 1300, 2800), (2200, 2900, 2800))):
        box(x0, y0, T0, x1, y0 + 100, T0 + COVER_H, MAT_WALL, "SPW_Gal_Fin_%d" % i, F)
    for sign, nm in ((-1, "W"), (1, "E")):
        a, b = sorted((sign * HX, sign * GAL_X))
        ramp(a, GALLERY_S, b, GALLERY_S + 800, T1, T1, "+Y", "SPW_Gal_Stair_%s" % nm, F)
        deck(a, GALLERY_S + 800, b, HY, T2, "SPW_Gal_Stair_Landing_%s" % nm, F)
    for i, x in enumerate((-2700, -1400, 1400, 2700)):
        box(x - 450, 2500, T2, x + 450, 2600, T2 + COVER_H, MAT_WALL,
            "SPW_Gal_Roof_Cover_%d" % i, F)
    for i, x in enumerate((-2000, 0, 2000)):
        crate_if_clear(x, 3400, T2, 240, "SPW_Gal_Roof_Crate_%d" % i, F)
    deck(-300, TW, 300, GALLERY_S, T2, "SPW_Gal_Tower_Link", F)


# ---------------------------------------------------------------------------
# 7. THE YARD - the open ground the whole arena circulates through
# ---------------------------------------------------------------------------
def build_yard():
    """Its job is to be EMPTY. The one structure per side is a PLATFORM - solid to tier 1
    with a ramp onto it - because it has to stand across the ground spawns' east-west line
    and a thing that tall has to be worth climbing."""
    F = "Spillway/50_Yard"
    for sign, nm in ((1, "West"), (-1, "East")):
        def rect(x0, y0, x1, y1):
            a, b = sorted((sign * x0, sign * x1))
            c, d = sorted((sign * y0, sign * y1))
            return a, c, b, d

        a, c, b, d = rect(-2200, -1900, -1400, -1200)
        box(a, c, T0, b, d, T1 - DECK_T, MAT_WALL, "SPW_Yard_%s_Platform_base" % nm, F)
        deck(a, c, b, d, T1, "SPW_Yard_%s_Platform" % nm, F)
        a, c, b, d = rect(-2150, -1850, -2050, -1250)
        box(a, c, T1, b, d, T1 + COVER_H, MAT_WALL, "SPW_Yard_%s_Platform_cover" % nm, F)
        a, c, b, d = rect(-2200, -1200, -1400, -400)
        ramp(a, c, b, d, T0, T1, "-Y" if sign > 0 else "+Y",
             "SPW_Yard_%s_Ramp" % nm, F)

        for i, (x0, y0, x1, y1) in enumerate(((-2600, 1100, -1900, 1200),
                                              (-2600, 200, -2500, 1000))):
            a, c, b, d = rect(x0, y0, x1, y1)
            box(a, c, T0, b, d, T0 + COVER_H, MAT_WALL,
                "SPW_Yard_%s_Cover_%d" % (nm, i), F)
        for i, (cx, cy) in enumerate(((-1800, 1500), (-2400, -300), (-2600, -900))):
            a, c, _, _ = rect(cx, cy, cx + 1, cy + 1)
            crate_if_clear(a, c, T0, 240, "SPW_Yard_%s_Crate_%d" % (nm, i), F)


# ---------------------------------------------------------------------------
# 8. GAMEPLAY MARKERS
# ---------------------------------------------------------------------------
SPAWNS = [
    # Staggered on purpose. Rev C put both teams' spawns at matching Y, which makes a
    # straight east-west line that only a wall can block - and walls are what made the
    # map a maze. No cross-team pair shares a Y here, so every line runs diagonally
    # through the tower instead, and the geometry that stops it is the hub you were
    # going to fight over anyway.
    # id,        x,       y,      z,   yaw,  team,   tier
    ("SP_W1", -4200.0, -1500.0, 20.0, 0.0, "West", "ground"),
    ("SP_W2", -4200.0, 1900.0, 20.0, 0.0, "West", "ground"),
    ("SP_W3", -3150.0, -800.0, 420.0, 0.0, "West", "deck"),
    ("SP_W4", -3150.0, 1900.0, 420.0, 0.0, "West", "deck"),
    ("SP_E1", 4200.0, 1500.0, 20.0, 180.0, "East", "ground"),
    ("SP_E2", 4200.0, -1900.0, 20.0, 180.0, "East", "ground"),
    ("SP_E3", 3150.0, 800.0, 420.0, 180.0, "East", "deck"),
    ("SP_E4", 3150.0, -1900.0, 420.0, 180.0, "East", "deck"),
]

POWER_WEAPON = (0.0, -450.0, 1260.0)      # on the crown plinth, tier 3
NAV_BOUNDS = {"centre": [0.0, 0.0, 600.0], "size": [9200.0, 8400.0, 3200.0]}

MIN_SPAWN_SPACING_M = 8.0
MAX_SIGHTLINE_M = 35.0
MIN_RAMP_W = 400.0


# ---------------------------------------------------------------------------
# Validation - the gates that decide whether this design is buildable at all
# ---------------------------------------------------------------------------
def solids():
    """Every element that blocks a bullet, as an AABB. Ramps are wedges; treating one as a
    full box would claim cover it does not give, so ramps are excluded outright."""
    return [e["aabb"] for e in _elements if e["kind"] != "ramp"]


def seg_hits_box(p, q, b, eye):
    """Slab test of the segment p->q (raised to eye height) against AABB b."""
    x0, y0, z0, x1, y1, z1 = b
    px, py, pz = p[0], p[1], p[2] + eye
    d = (q[0] - px, q[1] - py, (q[2] + eye) - pz)
    lo, hi = 0.0, 1.0
    for pi, di, mn, mx in ((px, d[0], x0, x1), (py, d[1], y0, y1), (pz, d[2], z0, z1)):
        if abs(di) < 1e-9:
            if pi < mn or pi > mx:
                return False
            continue
        t1, t2 = (mn - pi) / di, (mx - pi) / di
        if t1 > t2:
            t1, t2 = t2, t1
        lo, hi = max(lo, t1), min(hi, t2)
        if lo > hi:
            return False
    return True


GRID = 200.0            # flow sampling resolution, uu
STAND_H = 180.0         # a body needs this much clear height to occupy a cell
MIN_OPEN_FRAC = 0.55    # below this the tier is furniture, not an arena
MIN_LARGEST_FRAC = 0.92 # below this the tier is rooms joined by doorways
MAX_DETOUR_P90 = 1.35   # 90th percentile of path length / straight-line distance
MAX_DETOUR_WORST = 2.00 # the single worst corner of the map


def walkable_grid(tier):
    """Cells on `tier` a body could stand in: floor beneath, STAND_H of air above.

    This is the flow model. It is coarse and it ignores ramps, which is deliberate - the
    question it answers is "is this tier one space or a set of rooms", and a ramp that
    rescues connectivity between two otherwise-sealed rooms is exactly the doorway problem
    it exists to detect.
    """
    solids_ = [e["aabb"] for e in _elements if e["kind"] != "ramp"]
    nx = int(2 * HX / GRID)
    ny = int(2 * HY / GRID)
    open_cells = set()
    # JITTER, and it is load-bearing. Slab seams land on multiples of 100 and so do plain
    # cell centres, so an unjittered sample sits exactly on a seam, fails the strict
    # x0 < cx < x1 test on both neighbours, and reports a floor that is right there as a
    # hole. First run of this gate "found" the ground split in half for that reason.
    for i in range(nx):
        cx = -HX + (i + 0.5) * GRID + 13.0
        for j in range(ny):
            cy = -HY + (j + 0.5) * GRID + 7.0
            floor = blocked = False
            for x0, y0, z0, x1, y1, z1 in solids_:
                if not (x0 < cx < x1 and y0 < cy < y1):
                    continue
                if abs(z1 - tier) < 1.0:
                    floor = True
                if z0 < tier + STAND_H - 1.0 and z1 > tier + 1.0:
                    blocked = True
                    break
            if floor and not blocked:
                open_cells.add((i, j))
    return open_cells, nx, ny


def detour_ratios(cells):
    """Path length divided by straight-line distance, from eight seeds to everywhere.

    This is the measure that actually catches a maze, and it exists because the first two
    did not. Rev B was rejected for playing like a maze, yet it scored ONE connected
    region and a closed lap - because a gated cross-wall still technically connects. What
    separates it is how far you have to walk: rev B's worst corner was 2.55x its
    straight-line distance, rev C's is 1.71x. That gap IS the queue-for-the-doorway
    feeling, expressed as a number.
    """
    from collections import deque

    def bfs(src):
        d = {src: 0.0}
        q = deque([src])
        while q:
            c = q.popleft()
            for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1),
                           (1, 1), (1, -1), (-1, 1), (-1, -1)):
                n = (c[0] + dx, c[1] + dy)
                if n in cells and n not in d:
                    d[n] = d[c] + (1.41421 if dx and dy else 1.0)
                    q.append(n)
        return d

    seeds = []
    for wx, wy in ((-3600, -2400), (-3600, 2400), (3600, -2400), (3600, 2400),
                   (0, -2600), (0, 2600), (-3600, 0), (3600, 0)):
        seeds.append(min(cells, key=lambda c: (-HX + (c[0] + .5) * GRID - wx) ** 2
                                              + (-HY + (c[1] + .5) * GRID - wy) ** 2))
    out = []
    for sd in seeds:
        for c, dist in bfs(sd).items():
            straight = math.dist(c, sd)
            if straight >= 6:
                out.append(dist / straight)
    out.sort()
    return out


def components(cells):
    seen, comps = set(), []
    for c in cells:
        if c in seen:
            continue
        stack, comp = [c], []
        seen.add(c)
        while stack:
            i, j = stack.pop()
            comp.append((i, j))
            for n in ((i + 1, j), (i - 1, j), (i, j + 1), (i, j - 1)):
                if n in cells and n not in seen:
                    seen.add(n)
                    stack.append(n)
        comps.append(comp)
    return sorted(comps, key=len, reverse=True)


def circles_the_hub(cells):
    """Can you run a full lap around the tower on this tier without backtracking?

    True when the cells hugging the tower's four sides all sit in ONE component. If the
    lap is broken anywhere, the hub is a wall with routes past it rather than an island
    you can fight around, and flanking stops working.
    """
    def band(x0, y0, x1, y1):
        out = set()
        for i, j in cells:
            cx, cy = -HX + (i + 0.5) * GRID, -HY + (j + 0.5) * GRID
            if x0 <= cx <= x1 and y0 <= cy <= y1:
                out.add((i, j))
        return out

    M = 700.0
    sides = [band(-TW - M, -TW - M, TW + M, -TW),      # south of the tower
             band(-TW - M, TW, TW + M, TW + M),        # north
             band(-TW - M, -TW - M, -TW, TW + M),      # west
             band(TW, -TW - M, TW + M, TW + M)]        # east
    if any(not sd for sd in sides):
        return False, "no standing room on one of the tower's four sides"
    comps = components(cells)
    for comp in comps:
        cs = set(comp)
        if all(sd & cs for sd in sides):
            return True, "lap closes in one component of %d cells" % len(comp)
    return False, "the four sides of the tower are not all in one component"


def validate():
    errors, warnings = [], []
    boxes = solids()
    eye = 170.0

    if len(SPAWNS) != 8:
        errors.append("SPAWN_COUNT: %d spawns, the mode fills 8" % len(SPAWNS))
    for i in range(len(SPAWNS)):
        for j in range(i + 1, len(SPAWNS)):
            a, b = SPAWNS[i], SPAWNS[j]
            dist = math.dist(a[1:4], b[1:4]) / 100.0
            if dist < MIN_SPAWN_SPACING_M:
                errors.append("SPAWN_SPACING: %s-%s only %.1f m apart" % (a[0], b[0], dist))
            if a[5] == b[5] or dist <= MAX_SIGHTLINE_M:
                continue
            if not any(seg_hits_box(a[1:4], b[1:4], bx, eye) for bx in boxes):
                errors.append("SIGHTLINE_OPEN_PAIR: %s sees %s across %.1f m"
                              % (a[0], b[0], dist))
    for s in SPAWNS:
        if not (-HX < s[1] < HX and -HY < s[2] < HY):
            errors.append("SPAWN_OUT_OF_BOUNDS: %s" % s[0])

    px, py, pz = POWER_WEAPON
    if not any(x0 - 60 <= px <= x1 + 60 and y0 - 60 <= py <= y1 + 60
               and abs(z1 - (pz - 20)) < 80
               for (x0, y0, z0, x1, y1, z1) in boxes):
        errors.append("POWER_NODE_UNSUPPORTED: nothing under %s" % (POWER_WEAPON,))

    for e in _elements:
        if e["kind"] != "ramp":
            continue
        lo, hi = e["aabb"][2], e["aabb"][5]
        if lo not in TIERS or hi not in TIERS:
            errors.append("RAMP_OFF_TIER: %s spans %.0f..%.0f" % (e["label"], lo, hi))
        if e["width_uu"] < MIN_RAMP_W:
            errors.append("RAMP_NARROW: %s is %.0f uu wide" % (e["label"], e["width_uu"]))

    # A shaft with something built ON it is sealed - the ramp exists, and you can never
    # reach it. Lane_Mass_C did exactly this to Shaft_S and no other gate saw it, because
    # the mass sits at z>=0 and the ramp at z<0, so they never overlap in 3D.
    for nm, sx0, sy0, sx1, sy1, _ in SHAFTS:
        for e in _elements:
            # Only a solid resting ON the ground seals a shaft. Anything whose underside
            # is above the surface - a bridge, a deck, the tower crown - is headroom you
            # walk under, not a lid, so the test is on z0 and not on plan overlap alone.
            if e["kind"] == "ramp" or e["aabb"][5] <= T0 or e["aabb"][2] > T0 + 50:
                continue
            ex0, ey0, _, ex1, ey1, _ = e["aabb"]
            ov = (min(sx1, ex1) - max(sx0, ex0), min(sy1, ey1) - max(sy0, ey0))
            if ov[0] > 1.0 and ov[1] > 1.0:
                errors.append("SHAFT_SEALED: %s roofs %.0f%% of %s"
                              % (e["label"], 100.0 * ov[0] * ov[1]
                                 / ((sx1 - sx0) * (sy1 - sy0)), nm))

    # Every shaft must contain a ramp, or the culvert is a pit you fall into.
    ramp_starts = {(e["aabb"][0], e["aabb"][1]) for e in _elements if e["kind"] == "ramp"}
    for nm, x0, y0, x1, y1, _ in SHAFTS:
        if (x0, y0) not in ramp_starts:
            errors.append("SHAFT_NO_RAMP: %s" % nm)

    # Anything below ground must sit inside a culvert room, or it is floating in the void.
    for e in _elements:
        if e["aabb"][2] >= T0 - FLOOR_T:
            continue
        cx = (e["aabb"][0] + e["aabb"][3]) / 2.0
        cy = (e["aabb"][1] + e["aabb"][4]) / 2.0
        if not any(x0 - 150 <= cx <= x1 + 150 and y0 - 150 <= cy <= y1 + 150
                   for _, x0, y0, x1, y1 in CULVERT_ROOMS):
            errors.append("BELOW_GROUND_ORPHAN: %s" % e["label"])

    # Crates and pillars were originally left out of this scan and a culvert crate ended
    # up punching through the Shaft_S ramp - visible only as a wrong trace height. Every
    # solid gets checked now, with a smaller threshold so prop-sized clashes still show.
    # --- FLOW ---------------------------------------------------------
    # Added after rev B was rejected for playing like a maze. Rev B's ground tier was
    # three bands joined by three doorways each; these two numbers say so out loud.
    for tier, name in ((T0, "ground"), (T1, "tier1")):
        cells, nx, ny = walkable_grid(tier)
        if not cells:
            continue
        comps = components(cells)
        largest = len(comps[0]) / float(len(cells))
        if name == "ground":
            frac = len(cells) / float(nx * ny)
            if frac < MIN_OPEN_FRAC:
                errors.append("FLOW_CLUTTERED: ground is %.0f%% open, want >=%.0f%%"
                              % (100 * frac, 100 * MIN_OPEN_FRAC))
            ok, why = circles_the_hub(cells)
            if not ok:
                errors.append("FLOW_NO_LAP: cannot circle the tower - %s" % why)
            r = detour_ratios(cells)
            if r:
                p90, worst = r[int(0.9 * len(r))], r[-1]
                if p90 > MAX_DETOUR_P90:
                    errors.append("FLOW_DETOUR: p90 path is %.2fx the straight line, "
                                  "want <=%.2f" % (p90, MAX_DETOUR_P90))
                if worst > MAX_DETOUR_WORST:
                    errors.append("FLOW_DETOUR_WORST: some corner is %.2fx the straight "
                                  "line, want <=%.2f" % (worst, MAX_DETOUR_WORST))
            if largest < MIN_LARGEST_FRAC:
                errors.append("FLOW_FRAGMENTED: ground's largest region is %.0f%% of its "
                              "walkable area across %d pieces"
                              % (100 * largest, len(comps)))
        else:
            # Tier 1 is SUPPOSED to be islands - base roofs, the tower ring, the shelf.
            # Fragmentation is not the defect there; an island with no ramp on it is.
            feet = [e["aabb"] for e in _elements if e["kind"] == "ramp"
                    and (abs(e["aabb"][2] - tier) < 1 or abs(e["aabb"][5] - tier) < 1)]
            for comp in comps:
                if len(comp) < 3:
                    continue
                if not any(any(rx0 - GRID <= -HX + (i + 0.5) * GRID <= rx1 + GRID
                               and ry0 - GRID <= -HY + (j + 0.5) * GRID <= ry1 + GRID
                               for rx0, ry0, _, rx1, ry1, _ in feet)
                           for i, j in comp):
                    cx = sum(-HX + (i + 0.5) * GRID for i, j in comp) / len(comp)
                    cy = sum(-HY + (j + 0.5) * GRID for i, j in comp) / len(comp)
                    errors.append("FLOW_ISLAND_UNREACHABLE: %s region of %d cells near "
                                  "(%.0f, %.0f) has no ramp on it"
                                  % (name, len(comp), cx, cy))

    sol = list(_elements)
    for i in range(len(sol)):
        ax0, ay0, az0, ax1, ay1, az1 = sol[i]["aabb"]
        for j in range(i + 1, len(sol)):
            bx0, by0, bz0, bx1, by1, bz1 = sol[j]["aabb"]
            ov = (min(ax1, bx1) - max(ax0, bx0), min(ay1, by1) - max(ay0, by0),
                  min(az1, bz1) - max(az0, bz0))
            if all(v > 1.0 for v in ov) and ov[0] * ov[1] * ov[2] > 2e6:
                warnings.append("OVERLAP: %s and %s share %.1f m3"
                                % (sol[i]["label"], sol[j]["label"],
                                   ov[0] * ov[1] * ov[2] / 1e6))
    return errors, warnings


# ---------------------------------------------------------------------------
def build():
    _elements[:] = []
    _ground_holes[:] = []
    _dropped[:] = []
    build_culvert()          # first: it decides where the holes go
    build_envelope()
    build_tower()
    build_bases()
    build_south_lane()
    build_gallery()
    build_yard()
    for i, e in enumerate(_elements):
        e["index"] = i
        key = (e["mesh"], e["material"])
        if key not in VARIANT:
            raise SystemExit("no variant for %s on %s" % (e["material"], e["mesh"]))
        e["source_mesh"] = e["mesh"]
        e["mesh"] = VARIANT[key]
    return _elements


def max_z():
    return max(e["aabb"][5] for e in _elements)


def min_z():
    return min(e["aabb"][2] for e in _elements)


def manifest(errors, warnings):
    return {
        "arena_id": ARENA_ID,
        "manifest_version": 2,
        "units": "centimetres (Unreal units); authored in uu, not metres",
        "map": MAP_PATH,
        "generated_by": "Tools/blockout/gen_spillway.py",
        "generated_tag": TAG,
        "lineage": {
            "duplicated_from": "/Game/Variant_Shooter/Lvl_Shooter",
            "meshes_reused": [CUBE, RAMP, CYL, CHAMFER],
            "materials_reused": [MAT_DECK, MAT_WALL, MAT_TEAM],
        },
        "bounds_uu": {"x": [-HX, HX], "y": [-HY, HY], "z": [min_z(), max_z()]},
        "bounds_m": {"x": 2 * HX / 100, "y": 2 * HY / 100,
                     "z": (max_z() - min_z()) / 100},
        "perimeter_wall_m": WALL_H / 100,
        "highest_walkable_m": T3 / 100,
        "lowest_walkable_m": TB / 100,
        "baseline_lvl_shooter_m": {"x": 30.0, "y": 36.0, "z": 8.0},
        "footprint_ratio": round((2 * HX * 2 * HY) / (3000.0 * 3600.0), 3),
        "tiers_uu": list(TIERS),
        "ramp_widths_uu": {"main": RAMP_W, "side": RAMP_W_SIDE},
        "corridor_width_uu": CORRIDOR_W,
        "culvert_rooms": [{"name": r[0], "rect_uu": list(r[1:])} for r in CULVERT_ROOMS],
        "shafts": [{"name": s[0], "rect_uu": list(s[1:5]), "up": s[5]} for s in SHAFTS],
        "spawn_points": [{"id": s[0], "loc": [s[1], s[2], s[3]], "yaw": s[4],
                          "team": s[5], "tier": s[6]} for s in SPAWNS],
        "power_weapon_node": list(POWER_WEAPON),
        "nav_bounds": NAV_BOUNDS,
        "element_count": len(_elements),
        "errors": errors,
        "warnings": warnings,
    }


def summary(errors, warnings):
    by_folder = {}
    for e in _elements:
        by_folder.setdefault(e["folder"], []).append(e)
    print("BR_SPILLWAY  %.0f x %.0f m,  z %.0f..%.0f m   %d elements"
          % (2 * HX / 100, 2 * HY / 100, min_z() / 100, max_z() / 100, len(_elements)))
    print("  footprint  %.2fx Lvl_Shooter (30.0 x 36.0 m = 1,080 m2)"
          % ((2 * HX * 2 * HY) / (3000.0 * 3600.0)))
    print("  tiers      %s uu" % [int(t) for t in TIERS])
    for f in sorted(by_folder):
        kinds = {}
        for e in by_folder[f]:
            kinds[e["kind"]] = kinds.get(e["kind"], 0) + 1
        print("  %-26s %3d  %s" % (f, len(by_folder[f]),
                                   " ".join("%s:%d" % kv for kv in sorted(kinds.items()))))
    ramps = [e for e in _elements if e["kind"] == "ramp"]
    print("  ramps      %d, steepest %.1f deg, widths %s uu"
          % (len(ramps), max(e["slope_deg"] for e in ramps),
             sorted({int(e["width_uu"]) for e in ramps})))
    if _dropped:
        print("  props dropped for clashing: %d  %s"
              % (len(_dropped), ", ".join(_dropped[:6])))
    print("  errors     %d" % len(errors))
    for e in errors:
        print("     ! %s" % e)
    print("  warnings   %d" % len(warnings))
    for w in warnings[:14]:
        print("     - %s" % w)
    if len(warnings) > 14:
        print("     - ... %d more" % (len(warnings) - 14))


def main():
    build()
    errors, warnings = validate()
    summary(errors, warnings)
    if "--summary" in sys.argv:
        return 0 if not errors else 1

    root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    data = os.path.join(root, "Content", "Data")
    with open(os.path.join(data, "spillway_manifest.json"), "w", encoding="utf-8") as f:
        json.dump(manifest(errors, warnings), f, indent=1)
    with open(os.path.join(data, "spillway_placements.json"), "w", encoding="utf-8") as f:
        json.dump({"tag": TAG, "map": MAP_PATH, "elements": _elements}, f, indent=1)
    print("\nwrote Content/Data/spillway_manifest.json")
    print("wrote Content/Data/spillway_placements.json")
    return 0 if not errors else 1


if __name__ == "__main__":
    raise SystemExit(main())
