"""BN31 — author the FIFTEEN blockout kit assets as real UE static meshes.

RUN IT (live editor — see RISKS below for why not the commandlet):

    UnrealEditor Breachpoint.uproject \
        -ExecutePythonScript="Tools/blockout/make_kit_assets.py"

Reads  Content/Data/blockout_kit_assets.json  (the 15 specs, generated by
       Tools/blockout/gen_kit_catalog.py --spec)
Writes /Game/Blockout/Meshes/SM_BLK_*        (one static mesh per kit asset)
       /Game/Blockout/M_Blockout_Grey        (one flat grey material)

And, with no editor at all:

    python3 Tools/blockout/make_kit_assets.py --selftest

which checks the geometry the pure-Python way — exact size, pivot rule, and
outward winding — and exits non-zero if any of the fifteen is wrong.

WHY assets and not scaled engine cubes: the founder's directive - "he needs
to create those separate first and then use it throughout the level itself."
The level builder then places INSTANCES of these, so one edit to an asset
repropagates everywhere.

=========================== THE MESH-CREATION API ===========================
The old WATCH-LIST is CLOSED. There IS a first-party path and it is used
below; the fallback (engine BasicShapes scaled by the builder) is NOT taken.
Every call is a BlueprintCallable UFUNCTION in UE 5.8 engine source, quoted
here so the next reader does not have to re-discover it:

  Engine/Classes/Engine/StaticMesh.h:1814  UFUNCTION(BlueprintCallable)
    static UStaticMeshDescription* CreateStaticMeshDescription(UObject* Outer = nullptr)
      -> unreal.StaticMesh.create_static_mesh_description()
  Engine/Classes/Engine/StaticMesh.h:1818  UFUNCTION(BlueprintCallable)
    void BuildFromStaticMeshDescriptions(const TArray<UStaticMeshDescription*>&,
                                         bool bBuildSimpleCollision = false,
                                         bool bFastBuild = true)
      -> mesh.build_from_static_mesh_descriptions([md], False, False)
  Runtime/MeshDescription/Public/MeshDescriptionBase.h:122/146/218/242
    CreateVertex / CreateVertexInstance / CreatePolygon / CreatePolygonGroup
  MeshDescriptionBase.h:314  SetVertexPosition(FVertexID, const FVector&)
  Runtime/StaticMeshDescription/Public/StaticMeshDescription.h:49
    SetVertexInstanceUV(FVertexInstanceID, FVector2D, int32 UVIndex = 0)
  Developer/AssetTools/Public/IAssetTools.h:349  UFUNCTION(BlueprintCallable)
    UObject* CreateAsset(FString AssetName, FString PackagePath, UClass*,
                         UFactory*, FName CallingContext, bool bOverwriteExisting)
    - Factory may be null: AssetTools.cpp:1789 `else if (AssetClass)
      { NewObj = NewObject<UObject>(Pkg, ClassToUse, ...); }`
  Editor/StaticMeshEditor/Public/StaticMeshEditorSubsystem.h:241/290/332
    AddSimpleCollisionsWithNotification / SetConvexDecompositionCollisions... /
    RemoveCollisionsWithNotification
  StaticMesh.h:2222/2367  AddMaterial(UMaterialInterface*) / SetMaterial(int32, ...)

bFastBuild is passed FALSE on purpose. The fast path (StaticMesh.cpp:8928-30)
sets bDoFastBuild on the asset and skips the editor build; it is meant for
runtime-procedural meshes, not for something we SAVE. The cost of False is
that the built-in simple-collision box (StaticMesh.cpp:9055, inside the
`if (Params.bFastBuild)` branch at 8989) never runs, so collision is added
explicitly afterwards.

WINDING — the defect this file shipped with. UE's outward-facing polygon is
CLOCKWISE seen from outside: StaticMeshOperations.cpp:108 computes the
triangle normal as CrossProduct(P2-P0, P1-P0) ("left-handed coordinate
system, but a counter-clockwise winding order"), and Epic's own reference
cube (StaticMeshDescription.cpp:138, MakePolygon(1,0,3,2) for +Z) winds that
way. The generators below wind the other way, so every face is emitted
REVERSED (`idx[::-1]` in _emit). Verified by --selftest, which computes the
signed volume and fails if the normals point inward.

UNITS — the other defect. The spec is METRES, UE is CENTIMETRES. Positions
are multiplied by M_TO_UU exactly once, in _emit.

MOBILITY — "Static" is a component property (USceneComponent::Mobility), not
a static-mesh-asset property. It CANNOT be set here; the level builder sets
it on each StaticMeshComponent it places. Recorded, not silently dropped.

RISKS for the run:
  * needs a LIVE editor. unreal.get_editor_subsystem goes through GEditor
    (PyEditor.cpp:195) and MaterialEditingLibrary/AssetTools want the editor
    modules loaded. Asset creation itself needs no editor WORLD - nothing
    here spawns an actor - so the `-run=pythonscript` commandlet may well
    work, but it is not what this was written against.
  * CreatePolygon's two TArray& parameters are non-const, so UHT flags them
    CPF_OutParm|CPF_ReferenceParm and PyUtil.cpp:590 counts them as INPUTS
    as well as outputs. That should make the Python call take three
    arguments; _create_polygon falls back to two if this build disagrees.
============================================================================
"""

import json
import math
import sys

try:
    import unreal
except ImportError:                # --selftest runs outside the editor
    unreal = None

SPEC = "Content/Data/blockout_kit_assets.json"
PKG = "/Game/Blockout/Meshes"
MAT_PATH = "/Game/Blockout/M_Blockout_Grey"
MAT_SLOT = "Blockout"
M_TO_UU = 100.0                    # spec metres -> UE centimetres, ONCE
GREY = (0.34, 0.34, 0.36, 1.0)     # flat blockout grey


def load_spec(path=None):
    if path is None:
        path = unreal.Paths.project_dir() + SPEC
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


# --- geometry: every kit shape as (verts, quads) in METRES, pivot at the
# --- footprint centre, base at z=0 (plates centre in Z; see the spec note)
def box_geo(l, w, h, z0=0.0):
    x, y = l / 2.0, w / 2.0
    v = [(-x, -y, z0), (x, -y, z0), (x, y, z0), (-x, y, z0),
         (-x, -y, z0 + h), (x, -y, z0 + h), (x, y, z0 + h), (-x, y, z0 + h)]
    q = [(0, 3, 2, 1), (4, 5, 6, 7), (0, 1, 5, 4),
         (1, 2, 6, 5), (2, 3, 7, 6), (3, 0, 4, 7)]
    return v, q


def octagon_geo(dia, h):
    r = dia / 2.0
    ring = [(r * math.cos(math.pi / 8 + i * math.pi / 4),
             r * math.sin(math.pi / 8 + i * math.pi / 4)) for i in range(8)]
    v = [(x, y, 0.0) for x, y in ring] + [(x, y, h) for x, y in ring]
    q = [(i, (i + 1) % 8, (i + 1) % 8 + 8, i + 8) for i in range(8)]
    q += [(0, 7, 6, 5), (0, 5, 4, 3), (0, 3, 2, 1)]          # bottom fan
    q += [(8, 9, 10, 11), (8, 11, 12, 13), (8, 13, 14, 15)]  # top fan
    return v, q


def wedge_geo(run, width, rise):
    x, y = run / 2.0, width / 2.0
    v = [(-x, -y, 0.0), (x, -y, 0.0), (x, y, 0.0), (-x, y, 0.0),
         (x, -y, rise), (x, y, rise)]
    q = [(0, 3, 2, 1), (0, 1, 4, 4), (3, 5, 2, 2),
         (1, 2, 5, 4), (0, 4, 5, 3)]
    return v, q


def stair_geo(run, width, rise, steps):
    v, q = [], []
    tread, riser = run / steps, rise / steps
    for i in range(steps):
        sv, sq = box_geo(tread, width, riser * (steps - i))
        off = -run / 2.0 + tread * (i + 0.5)
        base = len(v)
        v += [(px + off, py, pz) for px, py, pz in sv]
        q += [tuple(idx + base for idx in face) for face in sq]
    return v, q


def geo_for(a):
    s, sz = a["shape"], a["size_m"]
    if s == "box":
        return box_geo(sz[0], sz[1], sz[2],
                       -sz[2] / 2.0 if a["id"] == "BLK_Floor_400" else 0.0)
    if s == "box45":
        return box_geo(sz[0], sz[1], sz[2])       # builder yaws it 45 deg
    if s == "octagon":
        return octagon_geo(sz[0], sz[1])
    if s == "wedge":
        return wedge_geo(sz[0], sz[1], sz[2])
    if s == "stair":
        return stair_geo(sz[0], sz[1], sz[2], int(sz[3]))
    if s == "doorway":
        l, w, h, ow, oh = sz
        jamb = (l - ow) / 2.0
        v, q = [], []
        for off, wid, hh, z0 in ((-(l - jamb) / 2.0, jamb, h, 0.0),
                                 ((l - jamb) / 2.0, jamb, h, 0.0),
                                 (0.0, ow, h - oh, oh)):
            sv, sq = box_geo(wid, w, hh, z0)
            base = len(v)
            v += [(px + off, py, pz) for px, py, pz in sv]
            q += [tuple(i + base for i in f) for f in sq]
        return v, q
    if s == "rail":
        l, w, h = sz
        v, q = [], []
        for off in (-l / 2.0 + 0.05, 0.0, l / 2.0 - 0.05):
            sv, sq = box_geo(0.1, w, h - 0.08)
            base = len(v)
            v += [(px + off, py, pz) for px, py, pz in sv]
            q += [tuple(i + base for i in f) for f in sq]
        sv, sq = box_geo(l, w, 0.08, h - 0.08)
        base = len(v)
        v += sv
        q += [tuple(i + base for i in f) for f in sq]
        return v, q
    raise ValueError("unknown shape %s" % s)


# ---------------------------------------------------------------- geometry
# --- helpers shared by the emitter and the offline self-test

def clean_face(face):
    """Drop repeated indices (wedge_geo writes triangles as degenerate quads)
    and REVERSE, because the generators wind CCW-outward and UE wants CW."""
    out = []
    for i in face:
        if not out or out[-1] != i:
            out.append(i)
    if len(out) > 1 and out[0] == out[-1]:
        out.pop()
    return out[::-1]


def tris(verts, quads):
    """(a, b, c) position triples, already reversed to UE winding."""
    for face in quads:
        idx = clean_face(face)
        for k in range(1, len(idx) - 1):
            yield verts[idx[0]], verts[idx[k]], verts[idx[k + 1]]


def tri_normal(a, b, c):
    """UE's own formula: CrossProduct(P2 - P0, P1 - P0). Positive-length
    result points OUT of the solid when the winding is right."""
    d2 = (c[0] - a[0], c[1] - a[1], c[2] - a[2])
    d1 = (b[0] - a[0], b[1] - a[1], b[2] - a[2])
    return (d2[1] * d1[2] - d2[2] * d1[1],
            d2[2] * d1[0] - d2[0] * d1[2],
            d2[0] * d1[1] - d2[1] * d1[0])


def face_uv(p, n):
    """1 UV unit = 1 metre, projected on the face's dominant axis. Blockout
    grey needs no UVs, but the mesh build wants a non-degenerate UV0 for
    tangents and lightmap seeding, and a grid texture later gets it free."""
    ax = max(range(3), key=lambda i: abs(n[i]))
    u, v = ((1, 2), (0, 2), (0, 1))[ax]
    return p[u], p[v]


def bbox(verts):
    lo = tuple(min(v[i] for v in verts) for i in range(3))
    hi = tuple(max(v[i] for v in verts) for i in range(3))
    return lo, hi


def signed_volume(verts, quads):
    """Divergence theorem. > 0 exactly when the normals face outward."""
    total = 0.0
    for a, b, c in tris(verts, quads):
        n = tri_normal(a, b, c)
        total += (a[0] * n[0] + a[1] * n[1] + a[2] * n[2]) / 6.0
    return total


# ------------------------------------------------------------ asset authoring
# Simple collision per shape. The ticket says "box; convex for the Ramp
# wedge". Box is right for the shapes that ARE boxes. It is wrong for the
# rest: one box over the stair is not walkable, over the doorway it seals the
# opening, over an octagon it fattens the corners. Those get a convex
# decomposition - still SIMPLE collision, which is what the rule protects.
# hull count / max hull verts / hull precision (editor "Auto Convex" defaults).
CONVEX = {"wedge": 1, "octagon": 1, "doorway": 4, "rail": 6, "stair": 12}


def grey_material():
    if unreal.EditorAssetLibrary.does_asset_exist(MAT_PATH):
        return unreal.EditorAssetLibrary.load_asset(MAT_PATH)
    folder, name = MAT_PATH.rsplit("/", 1)
    mat = unreal.AssetToolsHelpers.get_asset_tools().create_asset(
        name, folder, unreal.Material, unreal.MaterialFactoryNew())
    col = unreal.MaterialEditingLibrary.create_material_expression(
        mat, unreal.MaterialExpressionConstant3Vector, -320, 0)
    col.set_editor_property("constant", unreal.LinearColor(*GREY))
    unreal.MaterialEditingLibrary.connect_material_property(
        col, "", unreal.MaterialProperty.MP_BASE_COLOR)
    unreal.MaterialEditingLibrary.recompile_material(mat)
    unreal.EditorAssetLibrary.save_loaded_asset(mat, False)
    print("created %s" % MAT_PATH)
    return mat


def static_mesh(path):
    """Load if it exists, else create. Never CreateUniqueAssetName - a re-run
    must overwrite SM_BLK_Wall_400, not add SM_BLK_Wall_400_1."""
    if unreal.EditorAssetLibrary.does_asset_exist(path):
        return unreal.EditorAssetLibrary.load_asset(path)
    folder, name = path.rsplit("/", 1)
    return unreal.AssetToolsHelpers.get_asset_tools().create_asset(
        name, folder, unreal.StaticMesh, None)


def _create_polygon(md, pg, vis):
    # See the RISKS note: CreatePolygon's TArray& params are non-const, so
    # they should be inputs as well as outputs. Both shapes are accepted.
    try:
        md.create_polygon(pg, vis, [])
    except TypeError:
        md.create_polygon(pg, vis)


def emit(md, verts_m, quads):
    """Fill a StaticMeshDescription. One fresh vertex per face corner: no two
    faces share a vertex, so nothing can smooth-shade across an edge and no
    edge-hardness attribute (not exposed to Python) is needed."""
    pg = md.create_polygon_group()
    md.set_polygon_group_material_slot_name(pg, MAT_SLOT)
    for face in quads:
        idx = clean_face(face)
        if len(idx) < 3:
            continue
        pts = [verts_m[i] for i in idx]
        n = tri_normal(pts[0], pts[1], pts[2])
        vis = []
        for p in pts:
            vid = md.create_vertex()
            md.set_vertex_position(vid, unreal.Vector(p[0] * M_TO_UU,
                                                      p[1] * M_TO_UU,
                                                      p[2] * M_TO_UU))
            vi = md.create_vertex_instance(vid)
            u, v = face_uv(p, n)
            md.set_vertex_instance_uv(vi, unreal.Vector2D(u, v), 0)
            vis.append(vi)
        _create_polygon(md, pg, vis)
    return pg


def make_asset(a, mat, sms):
    path = a["asset_path"]
    expect = "%s/SM_%s" % (PKG, a["id"])
    if path != expect:
        raise ValueError("spec path %s != %s" % (path, expect))

    verts, quads = geo_for(a)
    if signed_volume(verts, quads) <= 0.0:
        raise ValueError("inward winding - geometry bug, refusing to author")

    mesh = static_mesh(path)
    md = unreal.StaticMesh.create_static_mesh_description()
    emit(md, verts, quads)
    # fast_build=False: real editor build (normals, tangents, DDC). Its cost
    # is that build_simple_collision is skipped, so we add collision below.
    mesh.build_from_static_mesh_descriptions([md], False, False)

    if mesh.get_material(0) is None:
        mesh.add_material(mat)
    else:
        mesh.set_material(0, mat)

    if sms is not None:
        sms.remove_collisions(mesh)          # idempotent: never accumulate
        hulls = CONVEX.get(a["shape"])
        if hulls:
            sms.set_convex_decomposition_collisions(mesh, hulls, 16, 100000)
        else:
            sms.add_simple_collisions(mesh, unreal.ScriptCollisionShapeType.BOX)

    unreal.EditorAssetLibrary.save_loaded_asset(mesh, False)
    return mesh


def audit(a, mesh, sms):
    """Read the LIVE asset back and diff it against the spec. Printing that
    the script ran proves nothing; this is the proof."""
    verts, _ = geo_for(a)
    lo, hi = bbox(verts)
    want = [(hi[i] - lo[i]) * M_TO_UU for i in range(3)]
    want_z0 = lo[2] * M_TO_UU

    box = mesh.get_bounding_box()
    got = [box.max.x - box.min.x, box.max.y - box.min.y, box.max.z - box.min.z]
    got_z0 = box.min.z

    simple = sms.get_simple_collision_count(mesh) if sms else -1
    convex = sms.get_convex_collision_count(mesh) if sms else -1
    m0 = mesh.get_material(0)
    rows = [
        ("size_uu", "%.2f x %.2f x %.2f" % tuple(want),
         "%.2f x %.2f x %.2f" % tuple(got),
         all(abs(want[i] - got[i]) < 0.05 for i in range(3))),
        ("base_z_uu", "%.2f" % want_z0, "%.2f" % got_z0,
         abs(want_z0 - got_z0) < 0.05),
        ("collision", "convex" if a["shape"] in CONVEX else "box",
         "convex x%d" % convex if convex > 0 else "box x%d" % simple,
         (convex > 0) if a["shape"] in CONVEX else (simple > 0)),
        ("material", MAT_PATH,
         m0.get_path_name().split(".")[0] if m0 else "<none>",
         bool(m0) and m0.get_path_name().split(".")[0] == MAT_PATH),
    ]
    ok = all(r[3] for r in rows)
    print("  %-22s %s" % (a["id"], "OK" if ok else "DIFF"))
    for field, w, g, good in rows:
        if not good:
            print("      %-10s want %-28s got %s" % (field, w, g))
    return ok


def main():
    spec = load_spec()
    print("BN31: authoring %d kit assets into %s" % (len(spec["assets"]), PKG))
    sms = unreal.get_editor_subsystem(unreal.StaticMeshEditorSubsystem)
    if sms is None:
        print("WARNING: no StaticMeshEditorSubsystem (no live editor?) - "
              "meshes will be built WITHOUT collision")
    mat = grey_material()

    made, failed = [], []
    for a in spec["assets"]:
        try:
            made.append((a, make_asset(a, mat, sms)))
        except Exception as e:                # noqa: BLE001 - reported below
            failed.append((a["id"], "%s: %s" % (type(e).__name__, e)))

    print("made %d, failed %d" % (len(made), len(failed)))
    for i, why in failed:
        print("  FAILED %-22s %s" % (i, why))

    print("--- AUDIT (read back from the live assets) ---")
    bad = [a["id"] for a, mesh in made if not audit(a, mesh, sms)]
    print("audit: %d/%d clean" % (len(made) - len(bad), len(made)))
    if failed or bad:
        print("STOP: BN33 must not build the level on a dirty kit.")
        return 1
    print("mobility Static is a COMPONENT property - the level builder sets "
          "it per placement; it cannot live on the asset.")
    return 0


# ------------------------------------------------------------------ selftest
def selftest(spec_path):
    """No editor needed. Proves the numbers the editor cannot be asked about
    here: exact size, pivot rule, and outward winding."""
    spec = load_spec(spec_path)
    bad = 0
    for a in spec["assets"]:
        verts, quads = geo_for(a)
        lo, hi = bbox(verts)
        size = [hi[i] - lo[i] for i in range(3)]
        sz = a["size_m"]
        errs = []
        if a["shape"] == "octagon":
            # size_m is [dia, height] and "dia" is the CIRCUMSCRIBED diameter -
            # the same convention gen_kit_catalog.octagon() drew the catalog
            # with. Across the flats an octagon is narrower (0.9239 x dia);
            # that is geometry, not rounding, so check the circumradius.
            dia = 2.0 * max(math.hypot(v[0], v[1]) for v in verts)
            if abs(dia - sz[0]) > 1e-9:
                errs.append("dia %.6f != spec %.6f" % (dia, sz[0]))
            want = [size[0], size[1], sz[1]]
        else:
            want = sz[:3]
        want_z0 = -sz[2] / 2.0 if a["id"] == "BLK_Floor_400" else 0.0
        vol = signed_volume(verts, quads)
        for i, axis in enumerate("LWH"):
            if abs(size[i] - want[i]) > 1e-9:
                errs.append("%s %.6f != spec %.6f" % (axis, size[i], want[i]))
        if abs(lo[2] - want_z0) > 1e-9:
            errs.append("base z %.6f != %.6f" % (lo[2], want_z0))
        if vol <= 0.0:
            errs.append("signed volume %.4f <= 0 (normals point INWARD)" % vol)
        print("%-22s %6.2f x %5.2f x %5.2f  z0 %+6.3f  vol %8.3f  %s"
              % (a["id"], size[0], size[1], size[2], lo[2], vol,
                 "ok" if not errs else "FAIL"))
        for e in errs:
            print("    %s" % e)
        bad += bool(errs)
    print("selftest: %d/%d ok" % (len(spec["assets"]) - bad, len(spec["assets"])))
    return 1 if bad else 0


if __name__ == "__main__":
    if "--selftest" in sys.argv:
        i = sys.argv.index("--selftest")
        path = sys.argv[i + 1] if len(sys.argv) > i + 1 else SPEC
        sys.exit(selftest(path))
    sys.exit(main())
