"""BN31 — author the FIFTEEN blockout kit assets as real UE static meshes.

RUN IT — either channel works; the script uses no editor-UI subsystem:

    # live editor console
    py Tools/blockout/make_kit_assets.py

    # headless, and this is how the landed run was made
    UnrealEditor-Cmd Breachpoint.uproject -run=pythonscript \
        -script="<abs>/Tools/blockout/make_kit_assets.py" -unattended -nosplash

    # one asset at a time while iterating
    ... -script="...make_kit_assets.py -only BLK_Ramp_800"

Reads  Content/Data/blockout_kit_assets.json  (the 15 specs, generated by
       Tools/blockout/gen_kit_catalog.py --spec)
Writes Intermediate/BlockoutKit/SM_*.obj      (intermediate, gitignored)
       /Game/Blockout/Meshes/SM_BLK_*         (one static mesh per kit asset)
       /Game/Blockout/M_Blockout_Grey         (one flat grey material)

And, with no editor at all:

    python3 Tools/blockout/make_kit_assets.py --selftest

which checks the geometry the pure-Python way — exact size, pivot rule, and
outward winding — and exits non-zero if any of the fifteen is wrong.

WHY assets and not scaled engine cubes: the founder's directive - "he needs
to create those separate first and then use it throughout the level itself."
The level builder then places INSTANCES of these, so one edit to an asset
repropagates everywhere.

=========================== THE MESH-CREATION API ===========================
PATH (a), MeshDescription-in-Python, IS DEAD. Do not try it again. The UE 5.8
binding is:

    create_polygon(polygon_group_id)
        -> (PolygonID, vertex_instance_i_ds=Array[VertexInstanceID],
                       new_edge_i_ds=Array[EdgeID])

- the vertex-instance array is an OUT parameter only, so there is no way to
hand it the corners of a polygon. Passing them positionally or by keyword is
`TypeError: create_polygon() takes at most 1 argument`. Creating the empty
polygon first and then calling set_polygon_vertex_instances CRASHES the
editor outright (Array.h:1339 range check, then SIGSEGV). Measured, twice.

PATH (b), used here: write an OBJ per asset and import it. Every fact below
was read off the live 5.8 binding or engine source, not assumed.

  UnrealEd/Classes/AssetImportTask.h -> unreal.AssetImportTask, properties
    filename / destination_path / destination_name / automated /
    replace_existing / save / options / factory / imported_object_paths.
    NOTE the engine's own doc on destination_name: "if you are using
    interchange the name must be set in a pipeline and this field will be
    IGNORED". OBJ import IS interchange, so the asset is named after the OBJ
    `g` group instead. Both are set to SM_<id> and the audit asserts the
    resulting package path, so it cannot silently drift.
  IAssetTools -> at.import_asset_tasks(import_tasks) -> None. Results come
    back on the task: task.imported_object_paths / task.get_objects().

  Interchange/Runtime/.../Mesh/InterchangeOBJTranslator.cpp
    :186  PositionToUEBasis(v) = (v.X, -v.Y, v.Z)
          The importer does NOT rotate Y-up to Z-up. It NEGATES Y - a mirror,
          not a rotation - and applies it to positions AND normals. There is
          no winding reversal anywhere in the file (grep Reverse: nothing), so
          a mirror leaves every face inside-out. Measured on a 100x200x300
          probe box: in Y[0,200] came back Y[-200,0], signed volume -6e6.
          => THE FIX: negate Y when WRITING the obj (_obj_v below). Negating
          twice is the identity, so positions and winding both survive.
    :227  ensure(UVs.IsValidIndex(VertexData.UVIndex)) - a face with no `vt`
          trips a handled ensure and spams the log. We always write UVs.
    :406  `vn` is honoured per vertex-instance, and edge hardness is derived
          from adjacent faces disagreeing on the normal - so one flat `vn`
          per face is what makes a blockout read as faceted. Omit them and
          the importer smooths the whole box into a blob (measured).
    :1323 the mesh node's display label IS the `g` group name; that is what
          the collision-by-name matcher and the asset name key off.

  Interchange/.../Pipelines/InterchangeGenericMeshPipeline.h:101-117
    bCollision = true, bImportCollisionAccordingToMeshName = true and
    bOneConvexHullPerUCX = true are all ON by default, so a group named
    UBX_<meshname>_## / UCX_<meshname>_## becomes simple collision on
    <meshname>. That is why this script needs no StaticMeshEditorSubsystem -
    which is a good thing, because get_editor_subsystem returns None for it
    in a commandlet (measured; the other editor subsystems are fine).
    Collision here is therefore EXACT and deterministic: the boxes the
    generators already produce, not whatever V-HACD decides today.

UNITS - the spec is METRES, UE is CENTIMETRES. Positions are multiplied by
M_TO_UU exactly once, in _obj_v.

WINDING - UE's outward-facing polygon is CLOCKWISE seen from outside:
StaticMeshOperations.cpp:108 computes the triangle normal as
CrossProduct(P2-P0, P1-P0), and Epic's reference cube
(StaticMeshDescription.cpp:138, MakePolygon(1,0,3,2) for +Z) winds that way.
The generators below wind the other way, so every face is emitted REVERSED
(`idx[::-1]` in clean_face). --selftest proves it by signed volume.

MOBILITY - "Static" is a component property (USceneComponent::Mobility), not
a static-mesh-asset property. It CANNOT be set here; the level builder sets
it on each StaticMeshComponent it places. Recorded, not silently dropped.
============================================================================
"""

import json
import math
import os
import sys

try:
    import unreal
except ImportError:                # --selftest runs outside the editor
    unreal = None

SPEC = "Content/Data/blockout_kit_assets.json"
PKG = "/Game/Blockout/Meshes"
MAT_PATH = "/Game/Blockout/M_Blockout_Grey"
M_TO_UU = 100.0                    # spec metres -> UE centimetres, ONCE
GREY = (0.34, 0.34, 0.36, 1.0)     # flat blockout grey

# Simple collision per shape, one primitive per convex PART of the shape.
# The ticket says "box; convex for the Ramp wedge". A box is right for the
# shapes that ARE boxes - and the stair, doorway and rail are each a handful
# of boxes, so they get one box per part rather than one wrong box over the
# whole thing (which would seal the doorway and un-walk the stair). Only the
# genuinely non-box parts - the wedge and the octagons - need a hull.
CONVEX = {"wedge", "octagon"}


def load_spec(path=None):
    if path is None:
        path = unreal.Paths.project_dir() + SPEC
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


# --- geometry -------------------------------------------------------------
# Every kit shape is a LIST OF CONVEX PARTS, each (verts, quads) in METRES,
# pivot at the footprint centre, base at z=0 (plates centre in Z; spec note).
# The render mesh is the parts merged; the collision is one primitive per
# part. One generator, both jobs.

def box_geo(l, w, h, z0=0.0):
    x, y = l / 2.0, w / 2.0
    v = [(-x, -y, z0), (x, -y, z0), (x, y, z0), (-x, y, z0),
         (-x, -y, z0 + h), (x, -y, z0 + h), (x, y, z0 + h), (-x, y, z0 + h)]
    q = [(0, 3, 2, 1), (4, 5, 6, 7), (0, 1, 5, 4),
         (1, 2, 6, 5), (2, 3, 7, 6), (3, 0, 4, 7)]
    return v, q


def octagon_geo(dia, h):
    r = dia / 2.0
    ring = [(r * math.cos(math.pi / 8 + i * math.pi / 4),
             r * math.sin(math.pi / 8 + i * math.pi / 4)) for i in range(8)]
    v = [(x, y, 0.0) for x, y in ring] + [(x, y, h) for x, y in ring]
    q = [(i, (i + 1) % 8, (i + 1) % 8 + 8, i + 8) for i in range(8)]
    q += [(0, 7, 6, 5), (0, 5, 4, 3), (0, 3, 2, 1)]          # bottom fan
    q += [(8, 9, 10, 11), (8, 11, 12, 13), (8, 13, 14, 15)]  # top fan
    return v, q


def wedge_geo(run, width, rise):
    x, y = run / 2.0, width / 2.0
    v = [(-x, -y, 0.0), (x, -y, 0.0), (x, y, 0.0), (-x, y, 0.0),
         (x, -y, rise), (x, y, rise)]
    q = [(0, 3, 2, 1), (0, 1, 4, 4), (3, 5, 2, 2),
         (1, 2, 5, 4), (0, 4, 5, 3)]
    return v, q


def offset(part, dx):
    v, q = part
    return [(px + dx, py, pz) for px, py, pz in v], q


def merge(parts):
    v, q = [], []
    for pv, pq in parts:
        base = len(v)
        v += pv
        q += [tuple(i + base for i in f) for f in pq]
    return v, q


def parts_for(a):
    """The shape as its convex parts."""
    s, sz = a["shape"], a["size_m"]
    if s == "box":
        return [box_geo(sz[0], sz[1], sz[2],
                        -sz[2] / 2.0 if a["id"] == "BLK_Floor_400" else 0.0)]
    if s == "box45":
        return [box_geo(sz[0], sz[1], sz[2])]     # builder yaws it 45 deg
    if s == "octagon":
        return [octagon_geo(sz[0], sz[1])]
    if s == "wedge":
        return [wedge_geo(sz[0], sz[1], sz[2])]
    if s == "stair":
        run, width, rise, steps = sz[0], sz[1], sz[2], int(sz[3])
        tread, riser = run / steps, rise / steps
        return [offset(box_geo(tread, width, riser * (steps - i)),
                       -run / 2.0 + tread * (i + 0.5)) for i in range(steps)]
    if s == "doorway":
        l, w, h, ow, oh = sz
        jamb = (l - ow) / 2.0
        return [offset(box_geo(jamb, w, h), -(l - jamb) / 2.0),
                offset(box_geo(jamb, w, h), (l - jamb) / 2.0),
                box_geo(ow, w, h - oh, oh)]
    if s == "rail":
        l, w, h = sz
        return [offset(box_geo(0.1, w, h - 0.08), dx)
                for dx in (-l / 2.0 + 0.05, 0.0, l / 2.0 - 0.05)] + \
               [box_geo(l, w, 0.08, h - 0.08)]
    raise ValueError("unknown shape %s" % s)


def geo_for(a):
    return merge(parts_for(a))


# --- geometry helpers shared by the emitter and the offline self-test -----

def clean_face(face):
    """Drop repeated indices (wedge_geo writes triangles as degenerate quads)
    and REVERSE, because the generators wind CCW-outward and UE wants CW."""
    out = []
    for i in face:
        if not out or out[-1] != i:
            out.append(i)
    if len(out) > 1 and out[0] == out[-1]:
        out.pop()
    return out[::-1]


def tris(verts, quads):
    """(a, b, c) position triples, already reversed to UE winding."""
    for face in quads:
        idx = clean_face(face)
        for k in range(1, len(idx) - 1):
            yield verts[idx[0]], verts[idx[k]], verts[idx[k + 1]]


def tri_normal(a, b, c):
    """UE's own formula: CrossProduct(P2 - P0, P1 - P0). Positive-length
    result points OUT of the solid when the winding is right."""
    d2 = (c[0] - a[0], c[1] - a[1], c[2] - a[2])
    d1 = (b[0] - a[0], b[1] - a[1], b[2] - a[2])
    return (d2[1] * d1[2] - d2[2] * d1[1],
            d2[2] * d1[0] - d2[0] * d1[2],
            d2[0] * d1[1] - d2[1] * d1[0])


def face_uv(p, n):
    """1 UV unit = 1 metre, projected on the face's dominant axis. Blockout
    grey needs no UVs, but the OBJ translator ensures on a face without them
    (InterchangeOBJTranslator.cpp:227) and tangents want a non-degenerate
    UV0, so they are always written."""
    ax = max(range(3), key=lambda i: abs(n[i]))
    u, v = ((1, 2), (0, 2), (0, 1))[ax]
    return p[u], p[v]


def bbox(verts):
    lo = tuple(min(v[i] for v in verts) for i in range(3))
    hi = tuple(max(v[i] for v in verts) for i in range(3))
    return lo, hi


def signed_volume(verts, quads):
    """Divergence theorem. > 0 exactly when the normals face outward."""
    total = 0.0
    for a, b, c in tris(verts, quads):
        n = tri_normal(a, b, c)
        total += (a[0] * n[0] + a[1] * n[1] + a[2] * n[2]) / 6.0
    return total


# --- OBJ emission ---------------------------------------------------------
# Y is negated on write, and ONLY here, to cancel the importer's
# PositionToUEBasis mirror. See the header block.

def _obj_v(p):
    return "v %.6f %.6f %.6f" % (p[0] * M_TO_UU, -p[1] * M_TO_UU,
                                 p[2] * M_TO_UU)


def _obj_vn(n):
    ln = math.sqrt(n[0] * n[0] + n[1] * n[1] + n[2] * n[2]) or 1.0
    return "vn %.6f %.6f %.6f" % (n[0] / ln, -n[1] / ln, n[2] / ln)


def obj_text(name, parts, prefix):
    """One OBJ: `g <name>` is the render mesh (all parts merged), then one
    `g UBX_/UCX_<name>_##` per convex part, which the interchange pipeline
    turns into simple collision and does NOT import as its own asset."""
    lines = ["# BN31 blockout kit - generated by Tools/blockout/make_kit_assets.py",
             "# units: centimetres. Y is pre-negated to cancel "
             "InterchangeOBJTranslator PositionToUEBasis."]
    counts = [0, 0, 0]                       # v, vt, vn written so far

    def group(gname, verts, quads):
        lines.append("g %s" % gname)
        vb = counts[0]
        for p in verts:
            lines.append(_obj_v(p))
        counts[0] += len(verts)
        for face in quads:
            idx = clean_face(face)
            if len(idx) < 3:
                continue
            pts = [verts[i] for i in idx]
            n = tri_normal(pts[0], pts[1], pts[2])
            lines.append(_obj_vn(n))
            counts[2] += 1
            corner = []
            for i, p in zip(idx, pts):
                u, v = face_uv(p, n)
                lines.append("vt %.6f %.6f" % (u, v))
                counts[1] += 1
                corner.append("%d/%d/%d" % (vb + i + 1, counts[1], counts[2]))
            lines.append("f %s" % " ".join(corner))

    group(name, *merge(parts))
    for i, (pv, pq) in enumerate(parts):
        group("%s_%s_%02d" % (prefix, name, i), pv, pq)
    return "\n".join(lines) + "\n"


def write_obj(a, name):
    prefix = "UCX" if a["shape"] in CONVEX else "UBX"
    d = os.path.join(unreal.Paths.convert_relative_path_to_full(
        unreal.Paths.project_intermediate_dir()), "BlockoutKit")
    os.makedirs(d, exist_ok=True)
    path = os.path.join(d, name + ".obj")
    with open(path, "w", encoding="utf-8") as f:
        f.write(obj_text(name, parts_for(a), prefix))
    return path


# --- asset authoring ------------------------------------------------------

def grey_material():
    if unreal.EditorAssetLibrary.does_asset_exist(MAT_PATH):
        return unreal.EditorAssetLibrary.load_asset(MAT_PATH)
    folder, name = MAT_PATH.rsplit("/", 1)
    mat = unreal.AssetToolsHelpers.get_asset_tools().create_asset(
        name, folder, unreal.Material, unreal.MaterialFactoryNew())
    col = unreal.MaterialEditingLibrary.create_material_expression(
        mat, unreal.MaterialExpressionConstant3Vector, -320, 0)
    col.set_editor_property("constant", unreal.LinearColor(*GREY))
    unreal.MaterialEditingLibrary.connect_material_property(
        col, "", unreal.MaterialProperty.MP_BASE_COLOR)
    unreal.MaterialEditingLibrary.recompile_material(mat)
    unreal.EditorAssetLibrary.save_loaded_asset(mat, False)
    print("created %s" % MAT_PATH)
    return mat


def make_asset(a, mat):
    path = a["asset_path"]
    name = path.rsplit("/", 1)[1]
    if path != "%s/SM_%s" % (PKG, a["id"]):
        raise ValueError("spec path %s != %s/SM_%s" % (path, PKG, a["id"]))

    verts, quads = geo_for(a)
    if signed_volume(verts, quads) <= 0.0:
        raise ValueError("inward winding - geometry bug, refusing to author")

    obj = write_obj(a, name)

    task = unreal.AssetImportTask()
    task.filename = obj
    task.destination_path = PKG
    task.destination_name = name     # ignored by interchange; the `g` name wins
    task.automated = True
    task.replace_existing = True     # idempotent: overwrite, never SM_..._1
    task.replace_existing_settings = True
    task.save = True
    unreal.AssetToolsHelpers.get_asset_tools().import_asset_tasks([task])

    made = list(task.imported_object_paths)
    if path + "." + name not in made:
        raise ValueError("import produced %r, wanted %s" % (made, path))
    mesh = unreal.EditorAssetLibrary.load_asset(path)

    slots = mesh.get_editor_property("static_materials")
    for i in range(max(1, len(slots))):
        mesh.set_material(i, mat)
    unreal.EditorAssetLibrary.save_loaded_asset(mesh, False)
    return mesh


def collision_counts(mesh):
    """(box, convex, other) simple-collision primitive counts, read off the
    live BodySetup. StaticMeshEditorSubsystem would be the obvious API and
    is None in a commandlet, so go to the data instead."""
    bs = mesh.get_editor_property("body_setup")
    if bs is None:
        return 0, 0, 0
    g = bs.get_editor_property("agg_geom")
    n = lambda f: len(g.get_editor_property(f))
    return n("box_elems"), n("convex_elems"), n("sphere_elems") + n("sphyl_elems")


def audit(a, mesh):
    """Read the LIVE asset back and diff it against the spec. Printing that
    the script ran proves nothing; this is the proof."""
    verts, _ = geo_for(a)
    lo, hi = bbox(verts)
    want = [(hi[i] - lo[i]) * M_TO_UU for i in range(3)]
    want_lo = [lo[i] * M_TO_UU for i in range(3)]

    box = mesh.get_bounding_box()
    got = [box.max.x - box.min.x, box.max.y - box.min.y, box.max.z - box.min.z]
    got_lo = [box.min.x, box.min.y, box.min.z]

    nbox, nconv, nother = collision_counts(mesh)
    want_prim = len(parts_for(a))
    want_kind = "convex" if a["shape"] in CONVEX else "box"
    got_kind = "convex" if nconv else ("box" if nbox else "NONE")
    got_n = nconv if nconv else nbox

    m0 = mesh.get_material(0)
    got_mat = m0.get_path_name().split(".")[0] if m0 else "<none>"

    # signed volume of the LIVE asset: catches the Y-mirror inverting winding
    vol = live_volume(mesh)
    want_vol = signed_volume(verts, _) * (M_TO_UU ** 3)

    rows = [
        ("size_uu", "%.2f x %.2f x %.2f" % tuple(want),
         "%.2f x %.2f x %.2f" % tuple(got),
         all(abs(want[i] - got[i]) < 0.05 for i in range(3))),
        ("min_uu", "%.2f, %.2f, %.2f" % tuple(want_lo),
         "%.2f, %.2f, %.2f" % tuple(got_lo),
         all(abs(want_lo[i] - got_lo[i]) < 0.05 for i in range(3))),
        ("collision", "%s x%d" % (want_kind, want_prim),
         "%s x%d%s" % (got_kind, got_n, " +%d other" % nother if nother else ""),
         got_kind == want_kind and got_n == want_prim and not nother),
        ("material", MAT_PATH, got_mat, got_mat == MAT_PATH),
        ("winding", "vol %+.3e" % want_vol,
         "vol %+.3e" % vol if vol is not None else "unreadable",
         vol is not None and vol > 0.0
         and abs(vol - want_vol) <= abs(want_vol) * 0.02),
    ]
    ok = all(r[3] for r in rows)
    print("  %-22s %s" % (a["id"], "OK" if ok else "DIFF"))
    for field, w, g, good in rows:
        print("      %-9s %-4s want %-26s got %s"
              % (field, "ok" if good else "DIFF", w, g))
    return ok


def live_volume(mesh):
    """Signed volume computed from the built render data. > 0 means the
    triangles really do face outward IN THE ASSET, not just in the OBJ."""
    try:
        v, t = unreal.ProceduralMeshLibrary.get_section_from_static_mesh(
            mesh, 0, 0)[:2]
    except Exception:                         # noqa: BLE001 - reported as DIFF
        return None
    total = 0.0
    for k in range(0, len(t), 3):
        a, b, c = v[t[k]], v[t[k + 1]], v[t[k + 2]]
        n = tri_normal((a.x, a.y, a.z), (b.x, b.y, b.z), (c.x, c.y, c.z))
        total += (a.x * n[0] + a.y * n[1] + a.z * n[2]) / 6.0
    return total


def main(only=None):
    spec = load_spec()
    assets = [a for a in spec["assets"] if only is None or a["id"] == only]
    print("BN31: authoring %d kit assets into %s" % (len(assets), PKG))
    mat = grey_material()

    made, failed = [], []
    for a in assets:
        try:
            made.append((a, make_asset(a, mat)))
        except Exception as e:                # noqa: BLE001 - reported below
            failed.append((a["id"], "%s: %s" % (type(e).__name__, e)))

    print("made %d, failed %d" % (len(made), len(failed)))
    for i, why in failed:
        print("  FAILED %-22s %s" % (i, why))

    print("--- AUDIT (read back from the live assets) ---")
    bad = [a["id"] for a, mesh in made if not audit(a, mesh)]
    print("audit: %d/%d clean" % (len(made) - len(bad), len(made)))
    if failed or bad:
        print("STOP: BN33 must not build the level on a dirty kit.")
        return 1
    print("mobility Static is a COMPONENT property - the level builder sets "
          "it per placement; it cannot live on the asset.")
    return 0


# --- selftest -------------------------------------------------------------
def selftest(spec_path):
    """No editor needed. Proves the numbers the editor cannot be asked about
    here: exact size, pivot rule, and outward winding."""
    spec = load_spec(spec_path)
    bad = 0
    for a in spec["assets"]:
        verts, quads = geo_for(a)
        lo, hi = bbox(verts)
        size = [hi[i] - lo[i] for i in range(3)]
        sz = a["size_m"]
        errs = []
        if a["shape"] == "octagon":
            # size_m is [dia, height] and "dia" is the CIRCUMSCRIBED diameter -
            # the same convention gen_kit_catalog.octagon() drew the catalog
            # with. Across the flats an octagon is narrower (0.9239 x dia);
            # that is geometry, not rounding, so check the circumradius.
            dia = 2.0 * max(math.hypot(v[0], v[1]) for v in verts)
            if abs(dia - sz[0]) > 1e-9:
                errs.append("dia %.6f != spec %.6f" % (dia, sz[0]))
            want = [size[0], size[1], sz[1]]
        else:
            want = sz[:3]
        want_z0 = -sz[2] / 2.0 if a["id"] == "BLK_Floor_400" else 0.0
        vol = signed_volume(verts, quads)
        for i, axis in enumerate("LWH"):
            if abs(size[i] - want[i]) > 1e-9:
                errs.append("%s %.6f != spec %.6f" % (axis, size[i], want[i]))
        if abs(lo[2] - want_z0) > 1e-9:
            errs.append("base z %.6f != %.6f" % (lo[2], want_z0))
        if vol <= 0.0:
            errs.append("signed volume %.4f <= 0 (normals point INWARD)" % vol)
        print("%-22s %6.2f x %5.2f x %5.2f  z0 %+6.3f  vol %8.3f  %s"
              % (a["id"], size[0], size[1], size[2], lo[2], vol,
                 "ok" if not errs else "FAIL"))
        for e in errs:
            print("    %s" % e)
        bad += bool(errs)
    print("selftest: %d/%d ok" % (len(spec["assets"]) - bad, len(spec["assets"])))
    return 1 if bad else 0


if __name__ == "__main__":
    if "--selftest" in sys.argv:
        i = sys.argv.index("--selftest")
        path = sys.argv[i + 1] if len(sys.argv) > i + 1 else SPEC
        sys.exit(selftest(path))
    only = sys.argv[sys.argv.index("-only") + 1] if "-only" in sys.argv else None
    sys.exit(main(only))
