"""BN31 — author the FIFTEEN blockout kit assets as real UE static meshes.

STATUS: WRITTEN, NOT RUN (no editor in the cloud). The terminal runs this.

    UnrealEditor-Cmd Breachpoint.uproject -run=pythonscript \
        -script="Tools/blockout/make_kit_assets.py" -stdout -unattended -nosplash

Reads  Content/Data/blockout_kit_assets.json  (the 15 specs, generated by
       Tools/blockout/gen_kit_catalog.py --spec)
Writes /Game/Blockout/Meshes/SM_BLK_*        (one static mesh per kit asset)
       /Game/Blockout/M_Blockout_Grey        (one flat grey material)

WHY assets and not scaled engine cubes: the founder's directive - "he needs
to create those separate first and then use it throughout the level itself."
The level builder then places INSTANCES of these, so one edit to an asset
repropagates everywhere.

=============================== WATCH-LIST ===============================
Mesh authoring from Python is the one part of this script with NO compiled
precedent in this repo. Do NOT assume the calls below are right - verify
first, then fix this file and commit the correction:

  1. In the MCP session:  list_toolsets -> describe_toolset(
     "editor_toolset.toolsets.static_mesh.StaticMeshTools") and
     describe_toolset("...asset.AssetTools") and read the real schemas.
  2. If a first-party mesh-creation tool exists there, PREFER IT over the
     Python path below and rewrite this script around it.
  3. If neither path works, FALL BACK (documented, acceptable): keep
     /Engine/BasicShapes/Cube + Cylinder and set each kit asset's identity
     by NAME + scale in the builder. Say so in the ticket - a fallback that
     is written down is fine; a silent one is not.

Everything else here (paths, sizes, pivots, collision, mobility) is spec,
not guesswork: it comes from Content/Data/blockout_kit_assets.json.
==========================================================================
"""

import json
import math

import unreal

SPEC = "Content/Data/blockout_kit_assets.json"
PKG = "/Game/Blockout/Meshes"


def load_spec():
    with open(unreal.Paths.project_dir() + SPEC, "r", encoding="utf-8") as f:
        return json.load(f)


# --- geometry: every kit shape as (verts, quads) in METRES, pivot at the
# --- footprint centre, base at z=0 (plates centre in Z; see the spec note)
def box_geo(l, w, h, z0=0.0):
    x, y = l / 2.0, w / 2.0
    v = [(-x, -y, z0), (x, -y, z0), (x, y, z0), (-x, y, z0),
         (-x, -y, z0 + h), (x, -y, z0 + h), (x, y, z0 + h), (-x, y, z0 + h)]
    q = [(0, 3, 2, 1), (4, 5, 6, 7), (0, 1, 5, 4),
         (1, 2, 6, 5), (2, 3, 7, 6), (3, 0, 4, 7)]
    return v, q


def octagon_geo(dia, h):
    r = dia / 2.0
    ring = [(r * math.cos(math.pi / 8 + i * math.pi / 4),
             r * math.sin(math.pi / 8 + i * math.pi / 4)) for i in range(8)]
    v = [(x, y, 0.0) for x, y in ring] + [(x, y, h) for x, y in ring]
    q = [(i, (i + 1) % 8, (i + 1) % 8 + 8, i + 8) for i in range(8)]
    q += [(0, 7, 6, 5), (0, 5, 4, 3), (0, 3, 2, 1)]          # bottom fan
    q += [(8, 9, 10, 11), (8, 11, 12, 13), (8, 13, 14, 15)]  # top fan
    return v, q


def wedge_geo(run, width, rise):
    x, y = run / 2.0, width / 2.0
    v = [(-x, -y, 0.0), (x, -y, 0.0), (x, y, 0.0), (-x, y, 0.0),
         (x, -y, rise), (x, y, rise)]
    q = [(0, 3, 2, 1), (0, 1, 4, 4), (3, 5, 2, 2),
         (1, 2, 5, 4), (0, 4, 5, 3)]
    return v, q


def stair_geo(run, width, rise, steps):
    v, q = [], []
    tread, riser = run / steps, rise / steps
    for i in range(steps):
        sv, sq = box_geo(tread, width, riser * (steps - i))
        off = -run / 2.0 + tread * (i + 0.5)
        base = len(v)
        v += [(px + off, py, pz) for px, py, pz in sv]
        q += [tuple(idx + base for idx in face) for face in sq]
    return v, q


def geo_for(a):
    s, sz = a["shape"], a["size_m"]
    if s == "box":
        return box_geo(sz[0], sz[1], sz[2],
                       -sz[2] / 2.0 if a["id"] == "BLK_Floor_400" else 0.0)
    if s == "box45":
        return box_geo(sz[0], sz[1], sz[2])       # builder yaws it 45 deg
    if s == "octagon":
        return octagon_geo(sz[0], sz[1])
    if s == "wedge":
        return wedge_geo(sz[0], sz[1], sz[2])
    if s == "stair":
        return stair_geo(sz[0], sz[1], sz[2], int(sz[3]))
    if s == "doorway":
        l, w, h, ow, oh = sz
        jamb = (l - ow) / 2.0
        v, q = [], []
        for off, wid, hh, z0 in ((-(l - jamb) / 2.0, jamb, h, 0.0),
                                 ((l - jamb) / 2.0, jamb, h, 0.0),
                                 (0.0, ow, h - oh, oh)):
            sv, sq = box_geo(wid, w, hh, z0)
            base = len(v)
            v += [(px + off, py, pz) for px, py, pz in sv]
            q += [tuple(i + base for i in f) for f in sq]
        return v, q
    if s == "rail":
        l, w, h = sz
        v, q = [], []
        for off in (-l / 2.0 + 0.05, 0.0, l / 2.0 - 0.05):
            sv, sq = box_geo(0.1, w, h - 0.08)
            base = len(v)
            v += [(px + off, py, pz) for px, py, pz in sv]
            q += [tuple(i + base for i in f) for f in sq]
        sv, sq = box_geo(l, w, 0.08, h - 0.08)
        base = len(v)
        v += sv
        q += [tuple(i + base for i in f) for f in sq]
        return v, q
    raise ValueError("unknown shape %s" % s)


def main():
    spec = load_spec()
    print("authoring %d kit assets into %s" % (len(spec["assets"]), PKG))
    made, failed = [], []
    for a in spec["assets"]:
        try:
            verts, quads = geo_for(a)
            # ---- WATCH-LIST: verify this API path before trusting it ----
            md = unreal.MeshDescription()
            smd = unreal.StaticMeshDescription(md) if False else None
            raise NotImplementedError(
                "mesh authoring API unverified - see the WATCH-LIST at the "
                "top of this file: discover the real call with "
                "describe_toolset(StaticMeshTools), fix this script, commit")
        except Exception as e:                    # noqa: BLE001 - reported
            failed.append((a["id"], str(e).splitlines()[0]))
            continue
    print("made %d, failed %d" % (len(made), len(failed)))
    for i, why in failed:
        print("  FAILED %-20s %s" % (i, why))
    if failed:
        print("STOP: fix the watch-list before building the level. The "
              "fallback (engine BasicShapes by name+scale) is allowed but "
              "must be RECORDED in TICKET_BN31.")


if __name__ == "__main__":
    main()
