"""BN32 — build the METRICS GYM: the measuring rig for the BREACHPOINT pawn.

    UnrealEditor-Cmd Breachpoint.uproject -run=pythonscript \
        -script="Tools/blockout/make_metrics_gym.py" \
        -stdout -unattended -nosplash

Law 7: the rig is GENERATED BY A COMMITTED SCRIPT, never hand-placed. This
script owns exactly one map, /Game/Maps/BR_MetricsGym (created if absent). It
never touches BR_Aquarius, BR_Arena01 or anything under /Game/Blockout.

WHAT IT BUILDS (four lanes, all traversed in +X, on one floor slab):

  y=0   STEPS      ledges 0.20 .. 2.00 m, each on flat ground so it is
                   approached fresh from z=0 (a continuous stair would let you
                   walk 45 cm at a time to 2 m and prove nothing).
  y=8   GAPS       0.50 .. 4.00 m between 0.40 m pads (0.40 < MaxStepHeight 45,
                   so you can walk onto the first pad).
  y=16  CLEARANCE  gates 0.80 .. 2.40 m, INCLUDING 1.44 and 1.92 — the whole
                   point of the lane. A NavMeshBoundsVolume covers the gym, so
                   Recast (AgentHeight 144) floors the 1.44 and 1.60 and 1.80
                   gates that the 1.92 m body cannot enter. Run a bot down this
                   lane and the nav-vs-body discrepancy is visible, not argued.
  y=24  RAMPS      20/25/30/35/40/45 deg, constant 2.00 m rise. Measured
                   WalkableFloorAngle is 44.765, so 45 must reject the pawn and
                   40 must not — that pair is the test.

Every element carries a TextRenderActor label so the height/gap/angle is
readable IN GAME from the player camera, not just in the outliner.

METRES ARE THE UNIT OF THIS FILE. plan() is pure Python and returns metres;
main() multiplies by M_TO_UU at the ONE boundary where actors are spawned.

IDEMPOTENT: every spawned actor is tagged BN32_MetricsGym and the script
destroys previously-tagged actors before building. A re-run is a clean rebuild.

Run this file OUTSIDE the editor (`python3 Tools/blockout/make_metrics_gym.py`)
and it executes a self-check of the geometry plan instead of building anything.
"""

import math

try:
    import unreal
except ImportError:                     # running as plain python: self-check only
    unreal = None

MAP_PATH = "/Game/Maps/BR_MetricsGym"
TAG = "BN32_MetricsGym"
M_TO_UU = 100.0                         # metres -> UE cm, converted ONCE (in main)
CUBE = "/Engine/BasicShapes/Cube"       # 100 uu cube: scale in metres IS the size

# --- measured sheet (BLOCKOUT-KIT.md 1.1, 30 Aug 2026) — printed on the labels
STEP_HEIGHT_M = 0.45                    # MaxStepHeight 45
JUMP_APEX_M = 0.90                      # JumpZ 420, GravityScale 1
FLAT_REACH_M = 5.14                     # 600 cm/s x 0.857 s air time
NAV_AGENT_H_M = 1.44                    # RecastNavMesh AgentHeight 144
BODY_H_M = 1.92                         # capsule hh 96
WALK_SLOPE_DEG = 44.765                 # WalkableFloorAngle

# --- rig knobs
LANE_Y = {"Steps": 0.0, "Gaps": 8.0, "Clearance": 16.0, "Ramps": 24.0}
LEDGES_M = [round(0.2 * i, 2) for i in range(1, 11)]          # 0.20 .. 2.00
GAPS_M = [round(0.5 * i, 2) for i in range(1, 9)]             # 0.50 .. 4.00
CLEARANCES_M = sorted({0.8, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0, 2.2, 2.4,
                       NAV_AGENT_H_M, BODY_H_M})
RAMP_DEGS = [20, 25, 30, 35, 40, 45]
RAMP_RISE_M = 2.0                       # constant rise; run falls out of the angle
RAMP_WIDTH_M = 3.0
RAMP_THICK_M = 0.30
LANE_WIDTH_M = 3.0
LABEL_Z_M = 2.60                        # above a 1.60 m eye line, still readable
LABEL_SIZE_UU = 40.0
LABEL_YAW = 180.0                       # calibration knob: text faces -X, i.e. back
                                        # at a player walking +X. Flip to 0 if the
                                        # build reads them mirrored.


def _box(label, folder, center, size, pitch=0.0):
    return {"kind": "box", "label": label, "folder": folder,
            "center": center, "size": size, "pitch": pitch}


def _text(label, folder, at, text):
    return {"kind": "text", "label": label, "folder": folder,
            "at": at, "text": text}


def _verdict(h):
    """What the measured sheet PREDICTS for a ledge of height h — printed on the
    label so PIE either confirms the sheet or contradicts it out loud."""
    if h <= STEP_HEIGHT_M:
        return "walk-on (step %.2f)" % STEP_HEIGHT_M
    if h <= JUMP_APEX_M:
        return "jump (apex %.2f)" % JUMP_APEX_M
    return "BLOCKED - no clamber"


def plan():
    """The whole rig in METRES. Pure python: no editor, no unreal module."""
    out = []

    # --- lane 1: ledges, each approached from flat ground
    y = LANE_Y["Steps"]
    x = 2.0
    for h in LEDGES_M:
        out.append(_box("Ledge_%03dcm" % round(h * 100), "MetricsGym/Steps",
                        (x + 1.0, y, h / 2.0), (2.0, LANE_WIDTH_M, h)))
        out.append(_text("L_Ledge_%03dcm" % round(h * 100), "MetricsGym/Labels",
                         (x, y, h + 0.6),
                         "LEDGE %.2f m\n%s" % (h, _verdict(h))))
        x += 5.0                        # 3 m of run-up before the next ledge
    out.append(_text("L_Lane_Steps", "MetricsGym/Labels", (0.0, y, LABEL_Z_M),
                     "STEPS  0.20-2.00 m\nstep %.2f / apex %.2f"
                     % (STEP_HEIGHT_M, JUMP_APEX_M)))

    # --- lane 2: gaps between low pads, ascending so you fail at your limit
    y = LANE_Y["Gaps"]
    x = 2.0
    pad_h = 0.40                        # < MaxStepHeight: walkable from the floor
    for g in GAPS_M:
        out.append(_box("GapPad_%03dcm" % round(g * 100), "MetricsGym/Gaps",
                        (x + 2.0, y, pad_h / 2.0),
                        (4.0, LANE_WIDTH_M, pad_h)))
        out.append(_text("L_Gap_%03dcm" % round(g * 100), "MetricsGym/Labels",
                         (x + 4.0, y, pad_h + 0.8), "GAP %.2f m ->" % g))
        x += 4.0 + g
    out.append(_box("GapPad_End", "MetricsGym/Gaps",
                    (x + 2.0, y, pad_h / 2.0), (4.0, LANE_WIDTH_M, pad_h)))
    out.append(_text("L_Lane_Gaps", "MetricsGym/Labels", (0.0, y, LABEL_Z_M),
                     "GAPS  0.50-4.00 m\npredicted flat reach %.2f m" % FLAT_REACH_M))

    # --- lane 3: clearance gates. THE lane: 1.44 (nav agent) vs 1.92 (body).
    y = LANE_Y["Clearance"]
    x = 4.0
    for h in CLEARANCES_M:
        cm = round(h * 100)
        note = ""
        if abs(h - NAV_AGENT_H_M) < 1e-6:
            note = "\nNAV AGENT HEIGHT - bot fits, BODY %.2f DOES NOT" % BODY_H_M
        elif abs(h - BODY_H_M) < 1e-6:
            note = "\nBODY HEIGHT - the first gate the pawn clears"
        elif NAV_AGENT_H_M < h < BODY_H_M:
            note = "\nNAV LIES HERE (1.44-1.92 band)"
        half = LANE_WIDTH_M / 2.0
        for side, sy in (("L", y - half - 0.15), ("R", y + half + 0.15)):
            out.append(_box("Gate_%03dcm_Post%s" % (cm, side),
                            "MetricsGym/Clearance",
                            (x, sy, (h + 0.3) / 2.0), (0.4, 0.3, h + 0.3)))
        out.append(_box("Gate_%03dcm_Lintel" % cm, "MetricsGym/Clearance",
                        (x, y, h + 0.15), (0.4, LANE_WIDTH_M + 0.6, 0.3)))
        out.append(_text("L_Gate_%03dcm" % cm, "MetricsGym/Labels",
                         (x, y, h + 0.6), "CLEAR %.2f m%s" % (h, note)))
        x += 4.0
    out.append(_text("L_Lane_Clearance", "MetricsGym/Labels",
                     (0.0, y, LABEL_Z_M),
                     "CLEARANCE  0.80-2.40 m\nnav agent %.2f vs body %.2f"
                     % (NAV_AGENT_H_M, BODY_H_M)))

    # --- lane 4: ramps, constant rise, angle read off the label
    y = LANE_Y["Ramps"]
    x = 2.0
    for deg in RAMP_DEGS:
        a = math.radians(deg)
        run = RAMP_RISE_M / math.tan(a)
        length = RAMP_RISE_M / math.sin(a)       # slab length along the slope
        # drop the slab half a thickness along its own normal so the TOP face,
        # not the centreline, runs from (x, 0) to (x + run, rise)
        cx = x + run / 2.0 + math.sin(a) * RAMP_THICK_M / 2.0
        cz = RAMP_RISE_M / 2.0 - math.cos(a) * RAMP_THICK_M / 2.0
        out.append(_box("Ramp_%02ddeg" % deg, "MetricsGym/Ramps",
                        (cx, y, cz), (length, RAMP_WIDTH_M, RAMP_THICK_M),
                        pitch=float(deg)))
        verdict = "WALKABLE" if deg < WALK_SLOPE_DEG else "SLIDES - over limit"
        out.append(_text("L_Ramp_%02ddeg" % deg, "MetricsGym/Labels",
                         (x, y, 0.8), "RAMP %d deg\n%s" % (deg, verdict)))
        x += run + 4.0
    out.append(_text("L_Lane_Ramps", "MetricsGym/Labels", (0.0, y, LABEL_Z_M),
                     "RAMPS 20-45 deg (rise %.2f m)\nwalkable limit %.3f deg"
                     % (RAMP_RISE_M, WALK_SLOPE_DEG)))

    # --- floor under everything, sized to the widest lane that got built
    x_max = max(b["center"][0] + b["size"][0] / 2.0
                for b in out if b["kind"] == "box")
    y_lo, y_hi = min(LANE_Y.values()) - 6.0, max(LANE_Y.values()) + 6.0
    out.insert(0, _box("Gym_Floor", "MetricsGym/Floor",
                       ((x_max + 4.0) / 2.0 - 2.0, (y_lo + y_hi) / 2.0, -0.25),
                       (x_max + 8.0, y_hi - y_lo, 0.5)))
    return out


def _selfcheck():
    p = plan()
    boxes = [a for a in p if a["kind"] == "box"]
    texts = [a for a in p if a["kind"] == "text"]
    labels = [a["label"] for a in p]
    assert len(labels) == len(set(labels)), "duplicate actor labels"
    # the two marks the ticket singles out must exist as their own gates
    assert "Gate_144cm_Lintel" in labels and "Gate_192cm_Lintel" in labels
    # ledges: every requested height present, top face AT that height
    for h in LEDGES_M:
        b = next(b for b in boxes if b["label"] == "Ledge_%03dcm" % round(h * 100))
        assert abs((b["center"][2] + b["size"][2] / 2.0) - h) < 1e-9
    # gates: lintel underside AT the clearance
    for h in CLEARANCES_M:
        b = next(b for b in boxes
                 if b["label"] == "Gate_%03dcm_Lintel" % round(h * 100))
        assert abs((b["center"][2] - b["size"][2] / 2.0) - h) < 1e-9
    # ramps: top face starts on the floor and rises exactly RAMP_RISE_M
    for deg in RAMP_DEGS:
        a = math.radians(deg)
        b = next(b for b in boxes if b["label"] == "Ramp_%02ddeg" % deg)
        half = b["size"][0] / 2.0
        n = (-math.sin(a), math.cos(a))          # slab normal, XZ
        top_dz = n[1] * b["size"][2] / 2.0
        z_lo = b["center"][2] - math.sin(a) * half + top_dz
        z_hi = b["center"][2] + math.sin(a) * half + top_dz
        assert abs(z_lo) < 1e-9, (deg, z_lo)
        assert abs(z_hi - RAMP_RISE_M) < 1e-9, (deg, z_hi)
    # gaps: the void between consecutive pads is the gap it is labelled with
    pads = [b for b in boxes if b["label"].startswith("GapPad_")]
    for g, (lo, hi) in zip(GAPS_M, zip(pads, pads[1:])):
        void = ((hi["center"][0] - hi["size"][0] / 2.0)
                - (lo["center"][0] + lo["size"][0] / 2.0))
        assert abs(void - g) < 1e-9, (g, void)
    print("selfcheck OK: %d boxes, %d labels, %d actors total"
          % (len(boxes), len(texts), len(p)))



def ensure_lighting(actor_ss, tag_fn, FOLDER="MetricsGym/Lights"):
    """A map made by new_level() has NO lights - every screenshot comes out black.

    Found 30 Aug 2026: BR_MetricsGym's first capture was unreadable and an actor
    audit showed no DirectionalLight and no SkyLight in the level at all. Both
    are tagged like everything else, so a re-run replaces them rather than
    stacking a new sun on every build.
    """
    sun = actor_ss.spawn_actor_from_class(
        unreal.DirectionalLight, unreal.Vector(0, 0, 1000),
        unreal.Rotator(0.0, -46.0, 30.0))
    sun.set_actor_label("Light_Sun")
    tag_fn(sun)
    sun.set_folder_path(unreal.Name(FOLDER))
    sky = actor_ss.spawn_actor_from_class(
        unreal.SkyLight, unreal.Vector(0, 0, 1000), unreal.Rotator(0, 0, 0))
    sky.set_actor_label("Light_Sky")
    tag_fn(sky)
    sky.set_folder_path(unreal.Name(FOLDER))
    return 2


def main():
    actor_ss = unreal.get_editor_subsystem(unreal.EditorActorSubsystem)
    level_ss = unreal.get_editor_subsystem(unreal.LevelEditorSubsystem)

    if not unreal.EditorAssetLibrary.does_asset_exist(MAP_PATH):
        level_ss.new_level(MAP_PATH)
    else:
        level_ss.load_level(MAP_PATH)

    stale = [a for a in actor_ss.get_all_level_actors()
             if a.actor_has_tag(unreal.Name(TAG))]
    for a in stale:
        actor_ss.destroy_actor(a)
    print("cleared %d previously generated actors" % len(stale))

    def finish(a, spec):
        if a is None:                   # commandlet with no editor world (see BN21)
            raise RuntimeError(
                "spawn returned None for %s. -run=pythonscript could not give this "
                "script an editor world; re-run inside a live editor (Unreal MCP / "
                "Output Log python) - the script is the same either way."
                % spec["label"])
        # UPROPERTY arrays through the Python proxy: read, modify, write back
        t = list(a.get_editor_property("tags"))
        t.append(unreal.Name(TAG))
        a.set_editor_property("tags", t)
        a.set_actor_label(spec["label"])
        a.set_folder_path(unreal.Name(spec["folder"]))

    cube = unreal.EditorAssetLibrary.load_asset(CUBE)
    boxes = texts = 0
    for spec in plan():
        if spec["kind"] == "box":
            loc = unreal.Vector(*[v * M_TO_UU for v in spec["center"]])
            # research-confirmed argument order: Rotator(roll, pitch, yaw)
            rot = unreal.Rotator(0.0, spec["pitch"], 0.0)
            a = actor_ss.spawn_actor_from_object(cube, loc, rot)
            finish(a, spec)
            a.set_actor_scale3d(unreal.Vector(*spec["size"]))
            try:
                a.static_mesh_component.set_mobility(unreal.ComponentMobility.STATIC)
            except AttributeError:
                pass
            boxes += 1
        else:
            loc = unreal.Vector(*[v * M_TO_UU for v in spec["at"]])
            rot = unreal.Rotator(0.0, 0.0, LABEL_YAW)
            a = actor_ss.spawn_actor_from_class(unreal.TextRenderActor, loc, rot)
            finish(a, spec)
            trc = a.text_render
            trc.set_text(spec["text"])
            trc.set_world_size(LABEL_SIZE_UU)
            trc.set_horizontal_alignment(unreal.HorizTextAligment.EHTA_CENTER)
            texts += 1
    print("placed %d boxes and %d in-game labels" % (boxes, texts))

    start = actor_ss.spawn_actor_from_class(
        unreal.PlayerStart,
        unreal.Vector(-4.0 * M_TO_UU, LANE_Y["Steps"] * M_TO_UU, 1.0 * M_TO_UU),
        unreal.Rotator(0.0, 0.0, 0.0))
    finish(start, {"label": "MetricsGym_Start", "folder": "MetricsGym/Spawns"})

    # nav over the whole gym: with AgentHeight 144 against a 1.92 m body, Recast
    # will floor the sub-body gates. That generated navmesh IS the evidence.
    xs = [b["center"][0] for b in plan() if b["kind"] == "box"]
    floor = plan()[0]
    nav = actor_ss.spawn_actor_from_class(
        unreal.NavMeshBoundsVolume,
        unreal.Vector(floor["center"][0] * M_TO_UU,
                      floor["center"][1] * M_TO_UU, 3.0 * M_TO_UU),
        unreal.Rotator(0.0, 0.0, 0.0))
    nav.set_actor_scale3d(unreal.Vector(floor["size"][0], floor["size"][1], 8.0))
    finish(nav, {"label": "Nav_MetricsGym", "folder": "MetricsGym/Nav"})
    print("nav bounds over x span %.1f..%.1f m" % (min(xs), max(xs)))

    def _tag_only(a):
        t = list(a.get_editor_property("tags"))
        t.append(unreal.Name(TAG))
        a.set_editor_property("tags", t)

    lights = ensure_lighting(actor_ss, _tag_only)
    print("placed %d lights (a new_level map ships with none)" % lights)

    level_ss.save_current_level()
    print("saved %s" % MAP_PATH)


if __name__ == "__main__":
    if unreal is None:
        _selfcheck()
    else:
        main()
