#!/usr/bin/env python3
# =====================================================================================
# BREACHPOINT - build_input.py :: execute the input plan into /Game/Input
#
# Serves:   TICKET BP01 step 3b. Runs INSIDE Unreal (it imports `unreal`).
# Law:      CLAUDE.md law 7 - input assets are generated by committed scripts, never
#           hand-placed; one owner per binary, lock before editing.
# Doctrine: .claude/skills/ue-editor - "the profile is the source of truth, the editor
#           state is its projection. Regenerate the projection; never let the projection
#           drift ahead of the source."
#
# This half is a DUMB EXECUTOR plus the asserts that only a LIVE asset can answer. Every
# decision - which actions exist, which tags, which value types, which triggers are legal,
# which keys - is made in input_plan.py, which is plain CPython and reviewable with no
# editor. What lives here and cannot live there:
#
#   * reading what is ALREADY on disk (the drift audit - the trigger contract's teeth);
#   * FKey validity, gameplay-tag registration, and the real UBRInputConfig::IsDataValid;
#   * writing .uasset bytes.
#
# Headless (the crew's default):
#   UnrealEditor-Cmd.exe <repo>\Breachpoint.uproject ^
#       -run=pythonscript -script="<repo>\Tools\gen_input\build_input.py" ^
#       -stdout -unattended -nosplash -nop4 -NoLiveCoding
# The PowerShell wrapper Tools/gen_input/build-input.ps1 does exactly this, plus engine
# resolution, the R21 "is an editor already running" guard, the plugin check and logging.
#
# Exit codes: 0 built/in-sync · 1 refused or contract violation · 3 blocked (bad input/env).
# =====================================================================================
"""Execute the validated input plan: IA_* actions, DA_InputConfig, IMC_Default bindings."""

import argparse
import datetime
import json
import os
import shlex
import subprocess
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import input_plan  # noqa: E402  (same directory; see sys.path line above)

try:
    import unreal
except ImportError:  # pragma: no cover - the whole point of the message
    sys.stderr.write(
        "BLOCKED: build_input.py must run inside Unreal (it imports `unreal`).\n"
        "  Headless: UnrealEditor-Cmd Breachpoint.uproject -run=pythonscript "
        "-script=\"Tools/gen_input/build_input.py\" -stdout -unattended -nosplash\n"
        "  Or use the wrapper: Tools\\gen_input\\build-input.ps1\n"
        "  To check the PROFILE without an editor, run input_plan.py instead - it is plain\n"
        "  CPython and needs nothing installed.\n")
    sys.exit(3)


def log(msg):
    unreal.log("[BR-geninput] %s" % msg)


def warn(msg):
    unreal.log_warning("[BR-geninput] %s" % msg)


def err(msg):
    unreal.log_error("[BR-geninput] %s" % msg)


class Refused(Exception):
    """A condition that must stop the run. The message is printed verbatim, and every one
    of them is written to be read by someone who was not here when it fired."""


# =====================================================================================
# argument plumbing
# =====================================================================================

def parse_args():
    """Args reach a -run=pythonscript script inconsistently across launch shapes, so we
    accept them from sys.argv AND from BR_GENINPUT_ARGS (what the PS wrapper sets)."""
    ap = argparse.ArgumentParser(prog="build_input.py")
    ap.add_argument("--profile", default=None)
    ap.add_argument("--dry-run", action="store_true",
                    help="audit the live assets and report; write nothing")
    ap.add_argument("--allow-drift", action="store_true",
                    help="repair a hand-edited asset without failing the run (say why in the "
                         "ticket Log)")
    ap.add_argument("--no-lock-check", action="store_true",
                    help="skip the git-lfs lock check on pre-existing .uassets (recorded)")
    ap.add_argument("--report-dir", default=None)

    argv = [a for a in sys.argv[1:] if not a.startswith("-run=")]
    env_args = os.environ.get("BR_GENINPUT_ARGS", "").strip()
    if env_args:
        argv.extend(shlex.split(env_args))
    args, unknown = ap.parse_known_args(argv)
    if unknown:
        log("ignoring unrecognised args (engine flags): %s" % " ".join(unknown))
    return args


def repo_root():
    return os.path.normpath(unreal.Paths.convert_relative_path_to_full(unreal.Paths.project_dir()))


def content_dir():
    return unreal.Paths.convert_relative_path_to_full(unreal.Paths.project_content_dir())


def uasset_disk_path(package):
    rel = package[len("/Game/"):] if package.startswith("/Game/") else package.lstrip("/")
    return os.path.normpath(os.path.join(content_dir(), rel + ".uasset"))


# =====================================================================================
# law 7: one owner per binary - lock before you touch it
# =====================================================================================

class LockGate(object):
    """Law 7, applied to the assets this run ACTUALLY rewrites - and only those.

    A .uasset that does not exist yet has no second writer to collide with, so it is not
    lock-gated. Neither is a pre-existing asset the run leaves alone: IA_Move, IA_Look and
    IA_Jump are usually already in sync, and demanding a lock on three files nobody is going
    to touch would make the honest path (re-run and confirm) the annoying one. IMC_Default is
    the case that matters - a template binary this packet EXTENDS, where two writers is an
    unresolvable merge - and it is gated the moment the run decides to write it.
    """

    def __init__(self, root, enabled):
        self.root = root
        self.enabled = enabled
        self.locked = {}
        self.query_error = None
        self.gated = []
        if not enabled:
            return
        try:
            out = subprocess.check_output(["git", "lfs", "locks", "--json"], cwd=root,
                                          stderr=subprocess.STDOUT)
            for lk in (json.loads(out.decode("utf-8") or "[]") or []):
                self.locked[str(lk.get("path", "")).replace("\\", "/")] = \
                    (lk.get("owner") or {}).get("name", "?")
        except (OSError, subprocess.CalledProcessError, ValueError) as exc:
            self.query_error = str(exc)

    def rel(self, package):
        return os.path.relpath(uasset_disk_path(package), self.root).replace("\\", "/")

    def require(self, package, existed_before):
        """Raise Refused unless `package` may be written now."""
        if not self.enabled or not existed_before:
            return
        rel = self.rel(package)
        if self.query_error is not None:
            raise Refused(
                "about to rewrite the pre-existing binary %s, but git lfs locks could not be "
                "queried (%s). Install git-lfs, or re-run with --no-lock-check and say why in "
                "the ticket Log." % (rel, self.query_error))
        if rel not in self.locked:
            raise Refused(
                "about to rewrite the pre-existing binary %s, which is NOT lfs-locked. One owner "
                "per binary per ticket (law 7). Run:  git lfs lock %s" % (rel, rel))
        self.gated.append("%s locked by %s" % (rel, self.locked[rel]))

    def summary(self):
        if not self.enabled:
            return "skipped (--no-lock-check)"
        if not self.gated:
            return "no pre-existing binary was rewritten by this run"
        return "; ".join(self.gated)


# =====================================================================================
# reflection helpers - every one of these is defensive on purpose
#
# The Python binding NAMES (enum entries, factory classes, soft-pointer conversion) are the
# part of this script that could not be proven without running an editor, and this packet
# was forbidden from launching one. So each helper tries the documented spelling first,
# falls back through the plausible alternatives, and FAILS LOUDLY with what it actually saw
# rather than writing a half-configured asset. A wrong guess must stop the run, not land.
# =====================================================================================

def _first_attr(names, what):
    for n in names:
        obj = getattr(unreal, n, None)
        if obj is not None:
            return obj, n
    raise Refused("this engine's Python bindings expose none of %s (%s). The binding name "
                  "changed or the module is not loaded." % (", ".join(names), what))


VALUE_TYPE_PY = {
    "Boolean": ("BOOLEAN",),
    "Axis1D": ("AXIS1_D", "AXIS1D"),
    "Axis2D": ("AXIS2_D", "AXIS2D"),
    "Axis3D": ("AXIS3_D", "AXIS3D"),
}


def value_type_enum(name):
    enum = getattr(unreal, "InputActionValueType", None)
    if enum is None:
        raise Refused("unreal.InputActionValueType is missing - is the EnhancedInput plugin "
                      "loaded in this editor?")
    for candidate in VALUE_TYPE_PY.get(name, ()):
        val = getattr(enum, candidate, None)
        if val is not None:
            return val
    raise Refused("cannot map value type '%s' onto unreal.InputActionValueType (tried %s). "
                  "Available: %s" % (name, ", ".join(VALUE_TYPE_PY.get(name, ())),
                                     ", ".join(sorted(d for d in dir(enum) if d.isupper()))))


def value_type_name(enum_value):
    """Live enum value -> our short name, for reports and comparisons."""
    for short in VALUE_TYPE_PY:
        try:
            if enum_value == value_type_enum(short):
                return short
        except Refused:
            continue
    return str(enum_value)


def trigger_class(short_name):
    cls = getattr(unreal, "InputTrigger" + short_name, None)
    if cls is None:
        raise Refused("unreal.InputTrigger%s does not exist in this build." % short_name)
    return cls


def trigger_short_name(obj):
    """Live trigger instance -> short name ('Down'), or a class name we do not recognise.

    A name outside input_plan.KNOWN_TRIGGERS (a Blueprint trigger, say) is deliberately NOT
    assumed harmless: the caller treats it as a contract violation on an ability action,
    because 'we cannot tell what this does' is not the same as 'this is fine'.
    """
    if obj is None:
        return "<null>"
    try:
        name = str(obj.get_class().get_name())
    except Exception:
        return str(type(obj))
    if name.startswith("InputTrigger") and len(name) > len("InputTrigger"):
        return name[len("InputTrigger"):]
    return name


def live_triggers(action):
    try:
        return [trigger_short_name(t) for t in (action.get_editor_property("triggers") or [])]
    except Exception as exc:
        raise Refused("cannot read the Triggers array on %s: %s" % (action.get_name(), exc))


def make_tag(tag_string):
    """FGameplayTag from a string, ASSERTED.

    FGameplayTag::TagName is VisibleAnywhere, i.e. CPF_EditConst, and Python's
    set_editor_property refuses EditConst properties - so the tag is built through the
    engine's own text import (FGameplayTag::ImportTextItem), which resolves the name against
    the tags manager. A tag that is NOT registered comes back as None, and that failure is
    exactly the signal we want: it means this editor build does not carry
    Core/BRGameplayTags.h's native tags, and every row we were about to write would have
    been silently tagless.
    """
    tag = unreal.GameplayTag()
    imported = False
    try:
        imported = bool(tag.import_text(tag_string))
    except Exception as exc:
        raise Refused("GameplayTag.import_text('%s') raised: %s" % (tag_string, exc))

    got = ""
    try:
        got = str(tag.get_editor_property("tag_name"))
    except Exception:
        got = ""

    if got != tag_string:
        raise Refused(
            "gameplay tag '%s' did not resolve (import returned %s, tag_name read back as "
            "'%s'). Either the tag is not declared in Source/Breachpoint/Core/BRGameplayTags.h, "
            "or this editor is running a module build that predates it. Writing rows with an "
            "empty tag would produce a config that compiles, validates as broken, and dies as a "
            "dead key in a match - so this run stops here."
            % (tag_string, imported, got))
    return tag


def make_key(key_name):
    """FKey from a name, ASSERTED against the engine's own key registry."""
    key = None
    for build in (lambda: unreal.Key(key_name),
                  lambda: unreal.Key(key_name=unreal.Name(key_name))):
        try:
            key = build()
            break
        except Exception:
            continue
    if key is None:
        key = unreal.Key()
        try:
            key.set_editor_property("key_name", unreal.Name(key_name))
        except Exception as exc:
            raise Refused("cannot construct an FKey for '%s': %s" % (key_name, exc))

    try:
        if not unreal.KismetInputLibrary.key_is_valid(key):
            raise Refused("'%s' is not a key this engine knows. Check the spelling against "
                          "EKeys in InputCoreTypes.cpp (e.g. 'LeftShift', 'LeftMouseButton', "
                          "'MouseScrollDown'). A bogus key serialises happily and is simply "
                          "never pressable." % key_name)
    except Refused:
        raise
    except Exception as exc:
        warn("could not run KismetInputLibrary.key_is_valid on '%s' (%s); the key's validity "
             "is UNVERIFIED for this run." % (key_name, exc))
    return key


def key_name_of(key):
    try:
        return str(key.get_editor_property("key_name"))
    except Exception:
        return str(key)


def asset_object_path(obj):
    if obj is None:
        return ""
    try:
        return str(obj.get_path_name())
    except Exception:
        return str(obj)


def soft_ref_path(value):
    """Whatever Python hands back for a TSoftObjectPtr -> a comparable path string."""
    if value is None:
        return ""
    if isinstance(value, str):
        return value
    for getter in ("get_path_name",):
        fn = getattr(value, getter, None)
        if callable(fn):
            try:
                return str(fn())
            except Exception:
                pass
    for prop in ("asset_path_name", "asset_path", "path"):
        try:
            return str(value.get_editor_property(prop))
        except Exception:
            continue
    return str(value)


def same_asset(a, b):
    """Path comparison that survives the several shapes UE prints object paths in."""
    def norm(s):
        s = str(s).strip().strip("'\"")
        if "'" in s:                      # Class'/Game/Foo.Foo'
            s = s.split("'")[-2] if s.count("'") >= 2 else s
        if " " in s:                      # Class /Game/Foo.Foo
            s = s.split(" ")[-1]
        return s.rstrip("'").lower()
    na, nb = norm(a), norm(b)
    return bool(na) and na == nb


# =====================================================================================
# asset creation / loading
# =====================================================================================

def split_package(package):
    head, _, name = package.rpartition("/")
    return head, name


def load_or_create(package, asset_class, factory, report):
    """Load the asset if it exists, else create it. NEVER recreates an existing asset:
    an existing IA_ keeps every property this generator does not manage (description,
    consume-input flags, player-mappable settings, the template's own authoring)."""
    if unreal.EditorAssetLibrary.does_asset_exist(package):
        asset = unreal.EditorAssetLibrary.load_asset(package)
        if asset is None:
            raise Refused("%s exists but failed to load." % package)
        return asset, False
    path, name = split_package(package)
    asset = unreal.AssetToolsHelpers.get_asset_tools().create_asset(name, path, asset_class, factory)
    if asset is None:
        raise Refused("could not create %s (factory %s)." % (package, factory.get_name()))
    report.setdefault("created", []).append(package)
    return asset, True


def save(asset, package, existed_before, lock, report):
    lock.require(package, existed_before)
    if not unreal.EditorAssetLibrary.save_loaded_asset(asset, False):
        raise Refused("save_loaded_asset failed for %s" % package)
    report.setdefault("saved", []).append(package)


# =====================================================================================
# the three build phases
# =====================================================================================

def build_actions(plan, args, lock, findings, report):
    """Create/update the eleven IA_ assets. Returns {package: asset}.

    THE DRIFT AUDIT LIVES HERE. Before writing anything, every asset already on disk is
    read and compared to the plan, and a difference is REPORTED by name - not silently
    overwritten. That is what makes the trigger contract an assertion instead of a
    convention: a Pressed trigger added by hand in the editor survives exactly until the
    next run of this script, which names it, repairs it, and (without --allow-drift) fails
    the run so nobody mistakes the repair for a clean pass.
    """
    factory = None
    factory_cls, _n = _first_attr(["InputAction_Factory", "InputActionFactory"],
                                  "the UInputAction asset factory")
    factory = factory_cls()

    assets = {}
    for a in plan["actions"]:
        pkg = a["package"]
        want_vt = a["value_type"]
        want_trig = list(a["triggers"])

        asset, created = load_or_create(pkg, unreal.InputAction, factory, report)
        assets[pkg] = asset
        existed_before = not created

        if created:
            log("created %s" % pkg)
            have_vt, have_trig = None, None
        else:
            have_vt = value_type_name(asset.get_editor_property("value_type"))
            have_trig = live_triggers(asset)

            # ---- drift audit on a pre-existing asset --------------------------------
            if have_vt != want_vt:
                findings.append(("error", "DRIFT_VALUE_TYPE",
                                 "%s is %s on disk; the profile says %s. Someone changed it "
                                 "outside this generator (or the profile changed). Repairing."
                                 % (a["name"], have_vt, want_vt)))
            if tuple(have_trig) != tuple(want_trig):
                sev, code = "warn", "DRIFT_TRIGGERS"
                detail = ""
                if a["list"] == "ability":
                    banned = [t for t in have_trig if t == input_plan.CONTRACT_BANNED_TRIGGER]
                    unknown = [t for t in have_trig if t not in input_plan.KNOWN_TRIGGERS]
                    illegal = [t for t in have_trig
                               if t not in input_plan.CONTRACT_ABILITY_TRIGGERS_ALLOWED
                               and t not in banned and t not in unknown]
                    if banned or unknown or illegal:
                        sev, code = "error", "CONTRACT_VIOLATION_ON_DISK"
                        detail = (" THIS IS A TRIGGER-CONTRACT VIOLATION on an ability action: "
                                  "%s. A Pressed (or unprovable) trigger delivers Completed while "
                                  "the key is still held, so WaitInputRelease and every WhileHeld "
                                  "ability (sprint, held fire) break in a way that looks like an "
                                  "ability bug. See UBRInputConfig::AbilityInputActions."
                                  % ", ".join(banned + unknown + illegal))
                findings.append((sev, code,
                                 "%s carries triggers [%s] on disk; the profile says [%s].%s "
                                 "Repairing."
                                 % (a["name"], ", ".join(have_trig) or "(empty)",
                                    ", ".join(want_trig) or "(empty)", detail)))

        # ---- apply, but only when something actually differs ------------------------
        dirty = False
        if created or have_vt != want_vt:
            asset.set_editor_property("value_type", value_type_enum(want_vt))
            dirty = True
        if created or tuple(have_trig or []) != tuple(want_trig):
            asset.set_editor_property(
                "triggers", [unreal.new_object(trigger_class(t), outer=asset) for t in want_trig])
            dirty = True

        # Post-set read-back: prove the property took, in this process, before saving.
        got_vt = value_type_name(asset.get_editor_property("value_type"))
        got_trig = live_triggers(asset)
        if got_vt != want_vt or tuple(got_trig) != tuple(want_trig):
            raise Refused("%s did not accept its settings: value_type=%s (want %s), "
                          "triggers=[%s] (want [%s])."
                          % (a["name"], got_vt, want_vt, ", ".join(got_trig),
                             ", ".join(want_trig)))

        if dirty and not args.dry_run:
            save(asset, pkg, existed_before, lock, report)
        elif not dirty:
            report.setdefault("in_sync", []).append(pkg)
    return assets


def build_config(plan, assets, args, lock, findings, report):
    """Author DA_InputConfig's two lists. Rows are built through the engine's own struct
    text import, which is the one path that sets BOTH a soft object reference and an
    EditConst FGameplayTag without guessing at Python type conversions."""
    cfg = plan["config"]
    pkg = cfg["package"]

    struct_type = getattr(unreal, "BRInputAction", None)
    config_class = getattr(unreal, "BRInputConfig", None)
    if config_class is None or struct_type is None:
        raise Refused(
            "unreal.BRInputConfig / unreal.BRInputAction are not present in this editor. The "
            "Breachpoint module either is not compiled into this build or predates "
            "Source/Breachpoint/Input/BRInputConfig.h. Build BreachpointEditor (rung 1) first - "
            "this script cannot author an instance of a class the editor does not have.")

    factory_cls, _n = _first_attr(["DataAssetFactory"], "the UDataAsset factory")
    factory = factory_cls()
    try:
        factory.set_editor_property("data_asset_class", config_class)
    except Exception:
        pass  # FactoryCreateNew falls back to the class passed to create_asset

    asset, created = load_or_create(pkg, config_class, factory, report)
    if created:
        log("created %s" % pkg)

    def make_rows(rows):
        out = []
        for r in rows:
            tag = make_tag(r["input_tag"])          # asserts registration
            action = assets.get(r["input_action"].rsplit(".", 1)[0])
            row = struct_type()
            text = '(InputAction="%s",InputTag=(TagName="%s"))' % (r["input_action"], r["input_tag"])
            ok = False
            try:
                ok = bool(row.import_text(text))
            except Exception as exc:
                warn("row import_text failed for %s (%s); falling back to property sets."
                     % (r["input_tag"], exc))
            if not ok or not _row_is(row, r):
                # Fallback: set the two properties directly. InputAction is EditDefaultsOnly
                # (settable); InputTag takes the already-resolved FGameplayTag value.
                set_ok = False
                for value in (action, unreal.SoftObjectPath(r["input_action"]), r["input_action"]):
                    if value is None:
                        continue
                    try:
                        row.set_editor_property("input_action", value)
                        set_ok = True
                        break
                    except Exception:
                        continue
                try:
                    row.set_editor_property("input_tag", tag)
                except Exception as exc:
                    raise Refused("cannot set InputTag on a row: %s" % exc)
                if not set_ok or not _row_is(row, r):
                    raise Refused(
                        "could not author the row for %s. import_text('%s') returned %s and the "
                        "property fallback did not stick; the row reads back as %s. This is the "
                        "one conversion this script could not prove without an editor - report "
                        "the read-back above in the ticket Log so the next run can be fixed in "
                        "one line." % (r["input_tag"], text, ok, _row_debug(row)))
            out.append(row)
        return out

    native = make_rows(cfg["native_input_actions"])
    ability = make_rows(cfg["ability_input_actions"])

    have_native = _rows_summary(asset.get_editor_property("native_input_actions"))
    have_ability = _rows_summary(asset.get_editor_property("ability_input_actions"))
    want_native = [(r["input_action"], r["input_tag"]) for r in cfg["native_input_actions"]]
    want_ability = [(r["input_action"], r["input_tag"]) for r in cfg["ability_input_actions"]]

    dirty = created or not _same_rows(have_native, want_native) or not _same_rows(have_ability, want_ability)
    if not created and dirty:
        findings.append(("warn", "DRIFT_CONFIG_ROWS",
                         "DA_InputConfig's rows differ from the profile. On disk: native=%s "
                         "ability=%s. Rewriting both lists from the profile."
                         % (have_native, have_ability)))

    if dirty:
        asset.set_editor_property("native_input_actions", native)
        asset.set_editor_property("ability_input_actions", ability)
        if not args.dry_run:
            save(asset, pkg, not created, lock, report)
    else:
        report.setdefault("in_sync", []).append(pkg)
    return asset


def _row_is(row, want):
    try:
        tag = str(row.get_editor_property("input_tag").get_editor_property("tag_name"))
    except Exception:
        tag = ""
    action = soft_ref_path(row.get_editor_property("input_action"))
    return tag == want["input_tag"] and same_asset(action, want["input_action"])


def _row_debug(row):
    try:
        return row.export_text()
    except Exception:
        return "<row export_text unavailable>"


def _rows_summary(rows):
    out = []
    for row in (rows or []):
        try:
            tag = str(row.get_editor_property("input_tag").get_editor_property("tag_name"))
        except Exception:
            tag = ""
        out.append((soft_ref_path(row.get_editor_property("input_action")), tag))
    return out


def _same_rows(have, want):
    if len(have) != len(want):
        return False
    for (ha, ht), (wa, wt) in zip(have, want):
        if ht != wt or not same_asset(ha, wa):
            return False
    return True


def build_mapping_context(plan, assets, args, lock, findings, report):
    """EXTEND IMC_Default - never replace it.

    Two rules, both load-bearing:
      1. only actions the profile marks generator_owns_mappings are touched. The template's
         Move/Look/Jump mappings (with their negate/swizzle modifiers and pad bindings) are
         never read for equality and never written.
      2. for an owned action, the update is unmap-all-then-map: a per-action clear-and-
         rebuild, which is the same idempotency shape as BP07's clear-by-tag. Nothing is
         appended, so a re-run cannot accumulate duplicates, and dropping a key from the
         profile actually drops it from the asset.
    And it only writes at all when the live mappings already differ from the plan.
    """
    mc = plan["mapping_context"]
    pkg = mc["package"]
    if not unreal.EditorAssetLibrary.does_asset_exist(pkg):
        raise Refused(
            "%s does not exist. This generator EXTENDS the template's mapping context; it will "
            "not conjure one, because the template's Move/Look/Jump mappings (and their "
            "modifiers) are authoring nobody has re-derived. Restore the asset, or make its "
            "creation an explicit ticket decision." % pkg)

    imc = unreal.EditorAssetLibrary.load_asset(pkg)
    if imc is None:
        raise Refused("%s exists but failed to load." % pkg)

    live = _imc_mappings(imc)
    live_pairs = [(asset_object_path(m.get_editor_property("action")),
                   key_name_of(m.get_editor_property("key"))) for m in live]

    owned = set(mc["managed_actions"])
    owned_paths = set()
    for p in owned:
        a = assets.get(p)
        if a is not None:
            owned_paths.add(asset_object_path(a))

    want_pairs = []
    for m in mc["mappings"]:
        a = assets.get(m["action_package"])
        if a is None:
            raise Refused("mapping names %s, which was never created." % m["action_package"])
        want_pairs.append((asset_object_path(a), m["key"], m["name"], m["action_package"]))

    # ---- collision audit against the mappings we do NOT own -------------------------
    foreign = {}
    for path, key in live_pairs:
        if path in owned_paths:
            continue
        foreign.setdefault(key, []).append(path)
    for path, key, name, _pkg in want_pairs:
        if key in foreign:
            findings.append(("error", "KEY_COLLISION_LIVE",
                             "key '%s' (wanted for %s) is ALREADY mapped in %s to %s, which this "
                             "generator does not own. Both actions would fire on one press. "
                             "Rebind in input_profile.json, or hand the other mapping to this "
                             "generator." % (key, name, pkg, ", ".join(foreign[key]))))

    have_owned = sorted((p, k) for p, k in live_pairs if p in owned_paths)
    want_owned = sorted((p, k) for p, k, _n, _pkg in want_pairs)
    if have_owned == want_owned:
        report.setdefault("in_sync", []).append(pkg)
        log("%s already carries all %d generated mapping(s); nothing written."
            % (pkg, len(want_owned)))
        return imc

    if have_owned:
        findings.append(("warn", "DRIFT_IMC_MAPPINGS",
                         "%s's generator-owned mappings differ from the profile. On disk: %s. "
                         "Rebuilding those actions' mappings; every other mapping in the asset is "
                         "left untouched." % (pkg, have_owned)))

    if args.dry_run:
        log("--dry-run: would set %d mapping(s) on %s" % (len(want_pairs), pkg))
        return imc

    for p in sorted(owned):
        a = assets.get(p)
        if a is not None:
            imc.unmap_all_keys_from_action(a)
    for _path, key, name, action_pkg in want_pairs:
        imc.map_key(assets[action_pkg], make_key(key))
        log("mapped %s <- %s" % (name, key))

    try:
        imc.modify()
    except Exception:
        pass
    save(imc, pkg, True, lock, report)
    return imc


def _imc_mappings(imc):
    """UE 5.7+ moved the live list into DefaultKeyMappings; `Mappings` is deprecated."""
    try:
        data = imc.get_editor_property("default_key_mappings")
        return list(data.get_editor_property("mappings") or [])
    except Exception:
        pass
    try:
        return list(imc.get_editor_property("mappings") or [])
    except Exception as exc:
        raise Refused("cannot read the mapping list off %s: %s" % (imc.get_name(), exc))


# =====================================================================================
# post-write verification - the pass that decides the exit code
# =====================================================================================

def verify(plan, assets, config_asset, imc, run_start, findings, report, check_mappings=True):
    """Re-read everything and assert it, THEN hand the config to the engine's own validator.

    Honesty note, stated because it is easy to over-claim: these objects are the in-memory
    ones the run just saved, so this proves 'what we saved is what the plan says', not 'the
    bytes on disk parse'. The disk half is covered narrowly and concretely by the mtime
    check - the same 'artifact is newer than the run that claims it' rule this project
    adopted for build claims after a stale binary was once reported as a pass.
    """
    ok = True

    for a in plan["actions"]:
        asset = assets[a["package"]]
        vt = value_type_name(asset.get_editor_property("value_type"))
        trig = live_triggers(asset)
        if vt != a["value_type"]:
            findings.append(("error", "VERIFY_VALUE_TYPE",
                             "%s reads back as %s, expected %s." % (a["name"], vt, a["value_type"])))
            ok = False
        if tuple(trig) != tuple(a["triggers"]):
            findings.append(("error", "VERIFY_TRIGGERS",
                             "%s reads back with triggers [%s], expected [%s]."
                             % (a["name"], ", ".join(trig), ", ".join(a["triggers"]))))
            ok = False
        # The contract, asserted one final time on the ability list, independently of the
        # diff above: this is the check that must never be able to pass by accident.
        if a["list"] == "ability":
            bad = [t for t in trig if t not in input_plan.CONTRACT_ABILITY_TRIGGERS_ALLOWED]
            if bad:
                findings.append(("error", "VERIFY_TRIGGER_CONTRACT",
                                 "%s ends this run carrying trigger(s) %s. The ability trigger "
                                 "contract allows the empty set or Down only. The assets this run "
                                 "wrote are NOT trustworthy." % (a["name"], ", ".join(bad))))
                ok = False

    for list_prop, rows in (("native_input_actions", plan["config"]["native_input_actions"]),
                            ("ability_input_actions", plan["config"]["ability_input_actions"])):
        have = _rows_summary(config_asset.get_editor_property(list_prop))
        want = [(r["input_action"], r["input_tag"]) for r in rows]
        if not _same_rows(have, want):
            findings.append(("error", "VERIFY_CONFIG_ROWS",
                             "DA_InputConfig.%s reads back as %s, expected %s."
                             % (list_prop, have, want)))
            ok = False

    # --dry-run never applied the mappings, so asserting them there would manufacture a
    # failure out of a mode that is working correctly.
    if check_mappings:
        live_pairs = set()
        for m in _imc_mappings(imc):
            live_pairs.add((asset_object_path(m.get_editor_property("action")),
                            key_name_of(m.get_editor_property("key"))))
        for m in plan["mapping_context"]["mappings"]:
            pair = (asset_object_path(assets[m["action_package"]]), m["key"])
            if pair not in live_pairs:
                findings.append(("error", "VERIFY_MAPPING_MISSING",
                                 "%s <- %s is not in the mapping context after the run."
                                 % (m["name"], m["key"])))
                ok = False

    # ---- mtime proof for everything this run claims to have written -----------------
    for pkg in report.get("saved", []):
        path = uasset_disk_path(pkg)
        if not os.path.isfile(path):
            findings.append(("error", "VERIFY_NO_FILE",
                             "%s was reported saved but no .uasset exists at %s." % (pkg, path)))
            ok = False
            continue
        mtime = os.path.getmtime(path)
        report.setdefault("written_mtimes", {})[pkg] = \
            datetime.datetime.fromtimestamp(mtime).strftime("%Y-%m-%d %H:%M:%S")
        if mtime < run_start:
            findings.append(("error", "VERIFY_STALE_FILE",
                             "%s is older than this run started. The save did not reach disk; "
                             "the file you are looking at is somebody else's." % pkg))
            ok = False

    # ---- the acceptance gate: UBRInputConfig::IsDataValid, run for real --------------
    result = run_data_validation(config_asset, findings, report)
    if result is False:
        ok = False
    return ok


def run_data_validation(config_asset, findings, report):
    """Run the editor's real validators over DA_InputConfig.

    UBRInputConfig::IsDataValid is the acceptance test this packet was given: it rejects a
    row with no asset, no tag, a tag outside InputTag.*, a duplicate, or a tag in both
    lists. input_plan.py mirrors those rules statically; this is the authoritative run.
    Returns True (valid), False (invalid), or None (could not run - reported, not hidden).
    """
    subsystem_cls = getattr(unreal, "EditorValidatorSubsystem", None)
    if subsystem_cls is None:
        findings.append(("warn", "VALIDATION_UNAVAILABLE",
                         "unreal.EditorValidatorSubsystem is absent (the DataValidation plugin is "
                         "not enabled), so UBRInputConfig::IsDataValid did NOT run. Only "
                         "input_plan.py's static mirror of it did. Enable the plugin to make the "
                         "acceptance gate real."))
        report["data_validation"] = "unavailable"
        return None

    subsystem = unreal.get_editor_subsystem(subsystem_cls)
    usecase = getattr(getattr(unreal, "DataValidationUsecase", None), "SCRIPT", None)
    try:
        out = subsystem.is_object_valid(config_asset, [], [], usecase)
    except Exception:
        try:
            out = subsystem.is_object_valid(config_asset, usecase)
        except Exception as exc:
            findings.append(("warn", "VALIDATION_CALL_FAILED",
                             "could not call EditorValidatorSubsystem.is_object_valid (%s). "
                             "UBRInputConfig::IsDataValid did NOT run." % exc))
            report["data_validation"] = "call-failed"
            return None

    result, errors, warnings = _unpack_validation(out)
    report["data_validation"] = {
        "result": str(result),
        "errors": [str(e) for e in (errors or [])],
        "warnings": [str(w) for w in (warnings or [])],
    }
    for e in (errors or []):
        findings.append(("error", "ISDATAVALID", str(e)))
    for w in (warnings or []):
        findings.append(("warn", "ISDATAVALID", str(w)))

    invalid = getattr(getattr(unreal, "DataValidationResult", None), "INVALID", None)
    if invalid is not None and result == invalid:
        return False
    if errors:
        return False
    log("UBRInputConfig::IsDataValid ran and returned %s with 0 errors." % result)
    return True


def _unpack_validation(out):
    if isinstance(out, tuple):
        if len(out) == 3:
            return out[0], out[1], out[2]
        if len(out) == 2:
            return out[0], out[1], []
        if len(out) == 1:
            return out[0], [], []
    return out, [], []


# =====================================================================================
# main
# =====================================================================================

def main():
    args = parse_args()
    run_start = time.time()
    root = repo_root()
    stamp = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

    log("=" * 78)
    log("BREACHPOINT input asset generator - BP01 step 3b")
    log("repo: %s" % root)
    log("started: %s (mtime proof baseline)" % datetime.datetime.fromtimestamp(run_start))

    try:
        plan, _profile = input_plan.load_all(args.profile)
    except input_plan.ProfileError as exc:
        err("BLOCKED: %s" % exc)
        return 3

    findings = [(f["severity"], f["code"], f["message"]) for f in plan["findings"]]
    report = {
        "schema": "breachpoint.input.report/1",
        "when": stamp,
        "plan_digest": plan["digest"],
        "profile_path": plan["profile_path"],
        "profile_sha256": plan["profile_sha256"],
        "dry_run": bool(args.dry_run),
        "allow_drift": bool(args.allow_drift),
        "plan": plan,
    }

    log("profile sha256 : %s" % plan["profile_sha256"])
    log("plan digest    : %s   <- re-runs agree iff this agrees" % plan["digest"])
    log("actions        : %d  config rows: %d native / %d ability  mappings: %d"
        % (plan["counts"]["actions"], plan["counts"]["native_rows"],
           plan["counts"]["ability_rows"], plan["counts"]["mappings"]))

    if plan["errors"]:
        for f in plan["findings"]:
            (err if f["severity"] == "error" else warn)("%s: %s" % (f["code"], f["message"]))
        err("REFUSING TO BUILD: %d profile validation error(s) above. Fix "
            "Tools/gen_input/input_profile.json and re-run. Do NOT patch the contract "
            "constants in input_plan.py to get past this." % plan["errors"])
        write_report(report, args, root, stamp, findings, "refused-validation")
        return 1

    # ---- law 7: gate every pre-existing binary at the moment we decide to write it ---
    if args.no_lock_check:
        warn("--no-lock-check: proceeding WITHOUT verifying lfs locks. Two writers on one "
             "binary is an unresolvable merge - say in the ticket Log why this was safe.")
    lock = LockGate(root, enabled=not args.no_lock_check and not args.dry_run)

    try:
        assets = build_actions(plan, args, lock, findings, report)
        config_asset = build_config(plan, assets, args, lock, findings, report)
        imc = build_mapping_context(plan, assets, args, lock, findings, report)
        verified = verify(plan, assets, config_asset, imc, run_start, findings, report,
                          check_mappings=not args.dry_run)
    except Refused as exc:
        err("REFUSED: %s" % exc)
        report["lock"] = lock.summary()
        write_report(report, args, root, stamp, findings, "refused")
        return 1
    except Exception as exc:  # noqa: BLE001 - a half-written asset must not be reported clean
        err("FAILED: %s" % exc)
        import traceback
        err(traceback.format_exc())
        report["lock"] = lock.summary()
        write_report(report, args, root, stamp, findings, "failed")
        return 1
    report["lock"] = lock.summary()

    for sev, code, msg in findings:
        (err if sev == "error" else warn if sev == "warn" else log)("%s: %s" % (code, msg))

    errors = [f for f in findings if f[0] == "error"]
    drift = [f for f in errors if f[1].startswith(("DRIFT_", "CONTRACT_VIOLATION_ON_DISK"))]
    hard = [f for f in errors if f not in drift]

    log("created : %s" % (", ".join(report.get("created", [])) or "none"))
    log("saved   : %s" % (", ".join(report.get("saved", [])) or "none"))
    log("in sync : %s" % (", ".join(report.get("in_sync", [])) or "none"))

    if args.dry_run:
        log("--dry-run: nothing was written.")
        write_report(report, args, root, stamp, findings, "dry-run")
        return 1 if errors else 0

    if hard or not verified:
        err("FAIL: the generated input assets did not pass their own verification. Do not "
            "commit them.")
        write_report(report, args, root, stamp, findings, "verify-failed")
        return 1

    if drift and not args.allow_drift:
        err("FAIL (repaired, but failing on purpose): %d asset(s) on disk did not match the "
            "profile and were repaired - see the DRIFT_/CONTRACT_ lines above. Law 7 says these "
            "assets are generated, never hand-placed, so a difference means somebody edited a "
            "generated asset in the editor. The repair is done; this exit code exists so the "
            "edit is SEEN. Re-run to get a clean pass, or pass --allow-drift and justify it in "
            "the ticket Log." % len(drift))
        write_report(report, args, root, stamp, findings, "drift")
        return 1

    write_report(report, args, root, stamp, findings, "built")
    log("DONE. Rung honesty: exit 0 means the assets were written and re-read as the profile "
        "describes them, and UBRInputConfig::IsDataValid accepted the config. It does NOT mean a "
        "key does anything - that needs a pawn, a mapping context added at runtime, and a PIE "
        "smoke (BP01 step 5, owner: verifier), and multiplayer claims come in threes.")
    return 0


def write_report(report, args, root, stamp, findings, verdict):
    report["verdict"] = verdict
    report["findings"] = [{"severity": s, "code": c, "message": m} for s, c, m in findings]
    out_dir = args.report_dir or os.path.join(root, "Saved", "InputGen")
    try:
        if not os.path.isdir(out_dir):
            os.makedirs(out_dir)
        path = os.path.join(out_dir, "input-%s-%s.json" % (stamp, verdict))
        with open(path, "w", encoding="utf-8") as fh:
            json.dump(report, fh, indent=2, sort_keys=True, default=str)
        log("report: %s" % path)
    except OSError as exc:
        warn("could not write the run report: %s" % exc)


if __name__ == "__main__":
    sys.exit(main())
