#!/usr/bin/env python3
# =====================================================================================
# BREACHPOINT - input_plan.py :: input_profile.json -> validated, deterministic ASSET PLAN
#
# Serves:   TICKET BP01 step 3b (generate IA_*, DA_InputConfig, IMC_Default bindings).
# Law:      CLAUDE.md law 7 - "input assets are generated by committed scripts, never
#           hand-placed." The profile is the source of truth; Content/Input is its projection.
# Contract: docs/contracts/data-and-assets.md (soft asset refs; one owner per binary).
# Acceptance: Source/Breachpoint/Input/BRInputConfig.h - the AbilityInputActions TRIGGER
#           CONTRACT, and UBRInputConfig::IsDataValid, which this file mirrors statically.
#
# THIS FILE IMPORTS NOTHING FROM UNREAL. Plain CPython 3.9+, stdlib only, so the whole plan
# can be validated and reviewed WITHOUT an editor (which matters: a human holds the project
# lock most of the time):
#
#     python Tools/gen_input/input_plan.py --verbose
#
# build_input.py (which does import unreal) imports this module and executes the plan it
# returns. Same split as Tools/blockout: every decision is made here, in reviewable text; the
# editor half is a dumb executor plus the asserts that only live assets can answer.
#
# Exit codes match the ladder convention (Tools/_BRLadderCommon.ps1):
#   0 PASS  plan is valid    1 FAIL  validation errors    3 BLOCKED  cannot read input
# =====================================================================================
"""Validate input_profile.json and derive the deterministic input-asset plan."""

import argparse
import hashlib
import json
import os
import re
import sys

# -------------------------------------------------------------------------------------
# THE CONTRACT. These are acceptance law - BP01 step 3, ARCHITECTURE 3.2, and the trigger
# contract documented on UBRInputConfig::AbilityInputActions. They are constants HERE and
# are deliberately NOT readable from input_profile.json: the profile chooses among legal
# values, it cannot legalise an illegal one. (Same rule as arena_plan.KICKOFF_*.)
# -------------------------------------------------------------------------------------

CONTRACT_NATIVE_TAGS = (
    "InputTag.Move",
    "InputTag.Look",
    "InputTag.Jump",
    "InputTag.Crouch",
)

CONTRACT_ABILITY_TAGS = (
    "InputTag.Sprint",
    "InputTag.Fire",
    "InputTag.Reload",
    "InputTag.Swap",
    "InputTag.Grenade",
    "InputTag.Melee",
    "InputTag.Grapple",
)

CONTRACT_ACTION_COUNT = len(CONTRACT_NATIVE_TAGS) + len(CONTRACT_ABILITY_TAGS)  # 11
CONTRACT_TAG_ROOT = "InputTag"

# Move and Look are the only 2D actions. Everything else is a digital press.
CONTRACT_AXIS2D_TAGS = ("InputTag.Move", "InputTag.Look")

# ---- THE TRIGGER CONTRACT -----------------------------------------------------------
# An ability action must use the DEFAULT (empty) trigger set or an explicit Down trigger.
# A *Pressed* trigger ends the action one frame after the press and delivers Completed
# WHILE THE KEY IS STILL HELD - a release that never happened. That silently breaks
# WaitInputRelease, every WhileHeld ability (sprint, held fire) and every toggle.
# UBRInputComponent::BindAbilityActions binds Triggered/Completed; this is the asset-side
# half of the same contract.
CONTRACT_ABILITY_TRIGGERS_ALLOWED = frozenset(("Down",))  # plus the empty set
CONTRACT_BANNED_TRIGGER = "Pressed"

# Trigger short names this toolchain understands (UInputTrigger<Name> in InputTriggers.h).
# Anything outside this set cannot be proven contract-legal, so it is refused rather than
# assumed innocent.
KNOWN_TRIGGERS = frozenset((
    "Down", "Pressed", "Released", "Hold", "HoldAndRelease",
    "Tap", "RepeatedTap", "Pulse", "ChordAction", "ChordBlocker",
))

VALUE_TYPES = ("Boolean", "Axis1D", "Axis2D", "Axis3D")

# FKey names are C identifiers plus a few engine spellings (Gamepad_..., Mouse2D, etc.).
KEY_NAME_RE = re.compile(r"^[A-Za-z][A-Za-z0-9_]*$")
ASSET_NAME_RE = re.compile(r"^IA_[A-Za-z][A-Za-z0-9_]*$")
PACKAGE_RE = re.compile(r"^/Game/[A-Za-z0-9_/]+$")

ERROR = "error"
WARN = "warn"
INFO = "info"


# =====================================================================================
# findings
# =====================================================================================

class Finding(object):
    """One validator result. `code` is stable so a triager can grep for it."""

    def __init__(self, severity, code, message):
        self.severity = severity
        self.code = code
        self.message = message

    def as_dict(self):
        return {"severity": self.severity, "code": self.code, "message": self.message}

    def __str__(self):
        return "%-5s %-26s %s" % (self.severity.upper(), self.code, self.message)


class ProfileError(Exception):
    """Raised when the profile cannot be read/parsed at all (BLOCKED, not FAIL)."""


# =====================================================================================
# helpers
# =====================================================================================

def object_path(package):
    """/Game/Input/Actions/IA_Fire -> /Game/Input/Actions/IA_Fire.IA_Fire

    The full object path is what a soft object reference stores, and what the executor
    compares against when deciding whether DA_InputConfig already says the right thing.
    """
    return "%s.%s" % (package, package.rsplit("/", 1)[-1])


def normalise_triggers(raw):
    """Profile trigger list -> a tuple of short names, order preserved, stripped."""
    return tuple(str(t).strip() for t in (raw or []) if str(t).strip())


# =====================================================================================
# validation - every check the ticket and BRInputConfig.h name
# =====================================================================================

def validate(profile, actions):
    """Returns a list of Finding. ERROR blocks the build; WARN is recorded and printed.

    Nothing stops at the first problem: a builder gets the whole list in one run.
    Checks 6-10 are a static mirror of UBRInputConfig::IsDataValid, so an illegal config
    is caught with no editor at all. The editor-side run of the REAL IsDataValid is still
    the acceptance gate (build_input.py step 9) - this is the cheap early copy, not a
    replacement, and the two are expected to agree.
    """
    f = []
    by_name = {}
    tags_by_list = {"native": [], "ability": []}

    # ---- 1. structure: names, packages, lists ---------------------------------------
    for i, a in enumerate(actions):
        name = a.get("name")
        if not name:
            f.append(Finding(ERROR, "ACTION_NO_NAME", "actions[%d] has no name." % i))
            continue
        if not ASSET_NAME_RE.match(name):
            f.append(Finding(ERROR, "ACTION_NAME_SHAPE",
                             "action '%s' is not an IA_* asset name." % name))
        if name in by_name:
            f.append(Finding(ERROR, "ACTION_DUPLICATE",
                             "action '%s' is declared twice (actions[%d] and [%d])."
                             % (name, by_name[name], i)))
        by_name[name] = i

        lst = a.get("list")
        if lst not in ("native", "ability"):
            f.append(Finding(ERROR, "ACTION_LIST",
                             "action '%s' list is '%s'; must be 'native' or 'ability'."
                             % (name, lst)))
        else:
            tags_by_list[lst].append((a.get("tag"), name))

    # ---- 2. the eleven, exactly ------------------------------------------------------
    if len(actions) != CONTRACT_ACTION_COUNT:
        f.append(Finding(ERROR, "ACTION_COUNT",
                         "profile declares %d actions; BP01 step 3 requires exactly %d "
                         "(4 native + 7 ability)." % (len(actions), CONTRACT_ACTION_COUNT)))

    for list_name, required in (("native", CONTRACT_NATIVE_TAGS),
                                ("ability", CONTRACT_ABILITY_TAGS)):
        have = [t for t, _n in tags_by_list[list_name] if t]
        missing = [t for t in required if t not in have]
        extra = [t for t in have if t not in required]
        if missing:
            f.append(Finding(ERROR, "TAG_MISSING",
                             "%s list is missing %s. The contract list is fixed in "
                             "input_plan.py, not in the profile." % (list_name, ", ".join(missing))))
        if extra:
            f.append(Finding(ERROR, "TAG_UNEXPECTED",
                             "%s list carries %s, which is not in the contract list for that "
                             "list. A new input verb is an ARCHITECTURE 3.2 change plus a tag in "
                             "BRGameplayTags.h, not a profile edit." % (list_name, ", ".join(extra))))

    # ---- 3-5. per-action: tag family, value type, TRIGGER CONTRACT -------------------
    for a in actions:
        name = a.get("name") or "?"
        tag = a.get("tag")
        lst = a.get("list")

        # (mirrors IsDataValid: "no tag" and "tag outside InputTag.*")
        if not tag:
            f.append(Finding(ERROR, "ROW_NO_TAG",
                             "action '%s' carries no InputTag. A row without a tag can never be "
                             "bound." % name))
        elif not (tag == CONTRACT_TAG_ROOT or tag.startswith(CONTRACT_TAG_ROOT + ".")):
            f.append(Finding(ERROR, "ROW_TAG_FAMILY",
                             "action '%s' carries '%s', which is not an %s.* tag."
                             % (name, tag, CONTRACT_TAG_ROOT)))

        vt = a.get("value_type")
        if vt not in VALUE_TYPES:
            f.append(Finding(ERROR, "VALUE_TYPE_UNKNOWN",
                             "action '%s' value_type '%s' is not one of %s."
                             % (name, vt, ", ".join(VALUE_TYPES))))
        else:
            expected = "Axis2D" if tag in CONTRACT_AXIS2D_TAGS else "Boolean"
            if vt != expected:
                f.append(Finding(ERROR, "VALUE_TYPE_CONTRACT",
                                 "action '%s' (%s) is %s; the contract says %s. Only Move and Look "
                                 "are Axis2D; every other action is Digital (bool)."
                                 % (name, tag, vt, expected)))

        triggers = normalise_triggers(a.get("triggers"))
        unknown = [t for t in triggers if t not in KNOWN_TRIGGERS]
        if unknown:
            f.append(Finding(ERROR, "TRIGGER_UNKNOWN",
                             "action '%s' names trigger(s) %s that this generator does not know. "
                             "Known: %s. An unknown trigger cannot be proven contract-legal, so it "
                             "is refused rather than assumed harmless."
                             % (name, ", ".join(unknown), ", ".join(sorted(KNOWN_TRIGGERS)))))

        if lst == "ability":
            if CONTRACT_BANNED_TRIGGER in triggers:
                f.append(Finding(ERROR, "TRIGGER_PRESSED_BANNED", _pressed_message(name)))
            illegal = [t for t in triggers
                       if t != CONTRACT_BANNED_TRIGGER and t not in CONTRACT_ABILITY_TRIGGERS_ALLOWED]
            if illegal:
                f.append(Finding(ERROR, "TRIGGER_NOT_ALLOWED",
                                 "ability action '%s' names trigger(s) %s. The contract allows the "
                                 "DEFAULT (empty) trigger set or an explicit Down trigger, and "
                                 "nothing else: Triggered must fire while the key is held and "
                                 "Completed must mean a real release "
                                 "(UBRInputConfig::AbilityInputActions)."
                                 % (name, ", ".join(illegal))))
        else:
            if CONTRACT_BANNED_TRIGGER in triggers:
                f.append(Finding(WARN, "TRIGGER_PRESSED_NATIVE",
                                 "native action '%s' uses a Pressed trigger. The contract's subject "
                                 "is the ability list, so this is not a hard error - but Pressed "
                                 "misreports release here too, and Crouch/Jump are press/release "
                                 "pairs. Almost certainly a mistake." % name))

    # ---- 6-8. IsDataValid mirror: duplicates within a list and across lists ----------
    seen_anywhere = {}
    for list_name in ("native", "ability"):
        seen_here = {}
        for tag, name in tags_by_list[list_name]:
            if not tag:
                continue
            if tag in seen_here:
                f.append(Finding(ERROR, "TAG_DUPLICATE_IN_LIST",
                                 "%s list carries '%s' more than once ('%s' and '%s'); the second "
                                 "row is unreachable by lookup."
                                 % (list_name, tag, seen_here[tag], name)))
            seen_here[tag] = name
            # Only a tag seen in the OTHER list is a cross-list violation; a repeat within
            # this list is already reported above, and reporting it twice under two names
            # would send a triager looking for a second, non-existent defect.
            if tag in seen_anywhere and seen_anywhere[tag][0] != list_name:
                f.append(Finding(ERROR, "TAG_DUPLICATE_ACROSS_LISTS",
                                 "'%s' appears in both the native and ability lists ('%s' and '%s'). "
                                 "A tag is either a pawn verb or an ability verb, never both."
                                 % (tag, seen_anywhere[tag][1], name)))
            seen_anywhere.setdefault(tag, (list_name, name))

    # ---- 9. key bindings --------------------------------------------------------------
    key_owner = {}
    for a in actions:
        name = a.get("name") or "?"
        keys = a.get("keys") or []
        owns = bool(a.get("generator_owns_mappings"))

        if not owns:
            if keys:
                f.append(Finding(WARN, "KEYS_NOT_APPLIED",
                                 "action '%s' lists keys %s but generator_owns_mappings is false, so "
                                 "they are NEVER applied. Either set the flag or drop the keys - a "
                                 "binding that exists only in a data file is a lie."
                                 % (name, ", ".join(keys))))
            continue

        if not keys:
            f.append(Finding(ERROR, "KEYS_MISSING",
                             "action '%s' is generator-owned but names no key. It would be an "
                             "asset nobody can press." % name))

        for k in keys:
            if not KEY_NAME_RE.match(str(k)):
                f.append(Finding(ERROR, "KEY_NAME_SHAPE",
                                 "action '%s' key '%s' is not a plausible FKey name. (Whether the "
                                 "engine actually knows the key is checked editor-side by "
                                 "KismetInputLibrary.key_is_valid - this is only the shape check.)"
                                 % (name, k)))
            if k in key_owner and key_owner[k] != name:
                f.append(Finding(ERROR, "KEY_COLLISION",
                                 "key '%s' is mapped to both '%s' and '%s'. Both actions would fire "
                                 "on one press." % (k, key_owner[k], name)))
            key_owner[k] = name

    # ---- 10. packages -----------------------------------------------------------------
    for key in ("actions_package_path", "input_config_package", "mapping_context_package"):
        val = profile.get(key)
        if not val or not PACKAGE_RE.match(str(val)):
            f.append(Finding(ERROR, "PACKAGE_PATH",
                             "%s is '%s'; expected a /Game/... package path." % (key, val)))
        elif not str(val).startswith("/Game/Input"):
            f.append(Finding(ERROR, "PACKAGE_OUT_OF_OWNER_PATH",
                             "%s is '%s', outside /Game/Input. This packet owns Content/Input/ and "
                             "nothing else; writing elsewhere is a law-5 violation the hook would "
                             "not even see (it does not watch the editor)." % (key, val)))

    cls = profile.get("input_config_class")
    if cls != "/Script/Breachpoint.BRInputConfig":
        f.append(Finding(ERROR, "CONFIG_CLASS",
                         "input_config_class is '%s'; DA_InputConfig must be a UBRInputConfig "
                         "instance (/Script/Breachpoint.BRInputConfig)." % cls))

    return f


def _pressed_message(name):
    return (
        "ability action '%s' names a Pressed trigger. THIS IS THE ONE THING THIS GENERATOR "
        "EXISTS TO PREVENT: a Pressed trigger ends the action one frame after the press and "
        "delivers Completed WHILE THE KEY IS STILL HELD - a release that never happened. It "
        "silently breaks WaitInputRelease, every WhileHeld ability (sprint, held fire) and "
        "every toggle, and it breaks them in a way that looks like an ability bug rather than "
        "an asset bug. Use the default (empty) trigger set or an explicit Down trigger. This "
        "rule is a constant in input_plan.py precisely so no profile edit can turn it off."
        % name)


# =====================================================================================
# plan construction
# =====================================================================================

def build_plan(profile):
    """Validate, then derive the ordered plan. Returns a plan dict.

    Determinism contract (see README):
      * actions are emitted in profile array order (json.load preserves document order);
      * the two config lists are emitted in the contract tag order (CONTRACT_*_TAGS), not
        in profile order, so re-ordering the profile cannot re-order the asset;
      * IMC mappings are emitted in action order then key order;
      * every path is derived from the action name - no counters, timestamps, uuids or
        randomness anywhere in the toolchain;
      * plan["digest"] is sha256 over the canonical plan body. Two runs agree iff the
        digests agree.
    """
    actions_root = profile.get("actions_package_path", "")
    raw_actions = profile.get("actions") or []
    findings = validate(profile, raw_actions)

    actions = []
    for a in raw_actions:
        name = a.get("name") or "?"
        package = "%s/%s" % (actions_root, name)
        actions.append({
            "name": name,
            "package": package,
            "object_path": object_path(package),
            "list": a.get("list"),
            "tag": a.get("tag"),
            "value_type": a.get("value_type"),
            "triggers": list(normalise_triggers(a.get("triggers"))),
            "owns_mappings": bool(a.get("generator_owns_mappings")),
            "keys": list(a.get("keys") or []),
            "description": a.get("description", ""),
        })

    by_tag = {}
    for a in actions:
        if a["tag"]:
            by_tag.setdefault(a["tag"], a)

    def rows_for(tag_order, list_name):
        rows = []
        for tag in tag_order:
            a = by_tag.get(tag)
            if a is None or a["list"] != list_name:
                continue  # already an ERROR from validate(); the plan simply omits it
            rows.append({"input_action": a["object_path"], "input_tag": tag, "name": a["name"]})
        return rows

    mappings = []
    for a in actions:
        if not a["owns_mappings"]:
            continue
        for k in a["keys"]:
            mappings.append({"action_package": a["package"], "name": a["name"], "key": k})

    plan = {
        "schema": "breachpoint.input.plan/1",
        "profile_id": profile.get("profile_id"),
        "actions_package_path": actions_root,
        "actions": actions,
        "config": {
            "package": profile.get("input_config_package"),
            "class": profile.get("input_config_class"),
            "native_input_actions": rows_for(CONTRACT_NATIVE_TAGS, "native"),
            "ability_input_actions": rows_for(CONTRACT_ABILITY_TAGS, "ability"),
        },
        "mapping_context": {
            "package": profile.get("mapping_context_package"),
            "managed_actions": [a["package"] for a in actions if a["owns_mappings"]],
            "mappings": mappings,
        },
        "unmanaged_actions": profile.get("unmanaged_actions") or [],
        "findings": [x.as_dict() for x in findings],
        "counts": {
            "actions": len(actions),
            "native_rows": 0,
            "ability_rows": 0,
            "mappings": len(mappings),
            "managed_actions": len([a for a in actions if a["owns_mappings"]]),
        },
        "errors": len([x for x in findings if x.severity == ERROR]),
        "warnings": len([x for x in findings if x.severity == WARN]),
    }
    plan["counts"]["native_rows"] = len(plan["config"]["native_input_actions"])
    plan["counts"]["ability_rows"] = len(plan["config"]["ability_input_actions"])
    plan["digest"] = plan_digest(plan)
    return plan


def plan_digest(plan):
    """sha256 over the parts a re-run must reproduce exactly - the determinism handle.

    Covers the action set, the two config lists and the IMC mappings. It deliberately does
    NOT cover findings text (advisory) or the .uasset bytes: Unreal reserialises package
    metadata and object GUIDs on every save, so binary equality is not a property this
    toolchain claims. See README, 'What determinism means here'.
    """
    body = {
        "actions": plan["actions"],
        "config": plan["config"],
        "mapping_context": plan["mapping_context"],
    }
    payload = json.dumps(body, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def digest_file(path):
    with open(path, "rb") as fh:
        return hashlib.sha256(fh.read()).hexdigest()


# =====================================================================================
# io / cli
# =====================================================================================

def load_json(path, what):
    if not os.path.isfile(path):
        raise ProfileError("%s not found: %s" % (what, path))
    try:
        with open(path, "r", encoding="utf-8") as fh:
            return json.load(fh)  # document order preserved (py3.7+)
    except ValueError as exc:
        raise ProfileError("%s is not valid JSON (%s): %s" % (what, exc, path))


def repo_root():
    return os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def default_profile():
    return os.path.join(os.path.dirname(os.path.abspath(__file__)), "input_profile.json")


def load_all(profile_path=None):
    """The entry point build_input.py uses. Returns (plan, profile)."""
    ppath = os.path.abspath(profile_path or default_profile())
    profile = load_json(ppath, "input profile")
    plan = build_plan(profile)
    plan["profile_path"] = ppath
    plan["profile_sha256"] = digest_file(ppath)
    return plan, profile


def print_report(plan, verbose=False):
    out = sys.stdout
    out.write("=" * 86 + "\n")
    out.write("BREACHPOINT input asset plan :: %s\n" % plan.get("profile_id"))
    out.write("=" * 86 + "\n")
    out.write("profile       : %s\n" % plan.get("profile_path"))
    out.write("profile sha   : %s\n" % plan.get("profile_sha256"))
    out.write("plan digest   : %s\n" % plan["digest"])
    c = plan["counts"]
    out.write("actions       : %d (%d native rows, %d ability rows)\n"
              % (c["actions"], c["native_rows"], c["ability_rows"]))
    out.write("IMC mappings  : %d over %d generator-owned action(s); every other action's "
              "mappings are left untouched\n" % (c["mappings"], c["managed_actions"]))
    out.write("\n---- findings (%d error, %d warn) ----\n" % (plan["errors"], plan["warnings"]))
    order = {ERROR: 0, WARN: 1, INFO: 2}
    if not plan["findings"]:
        out.write("  (none)\n")
    for fd in sorted(plan["findings"], key=lambda d: order.get(d["severity"], 3)):
        out.write("  %-5s %-26s %s\n" % (fd["severity"].upper(), fd["code"], fd["message"]))

    if verbose:
        out.write("\n---- actions (creation order) ----\n")
        for a in plan["actions"]:
            trig = ", ".join(a["triggers"]) if a["triggers"] else "(default/empty)"
            keys = ", ".join(a["keys"]) if a["keys"] else "-"
            out.write("  %-12s %-8s %-16s %-9s triggers=%-18s keys=%s%s\n"
                      % (a["name"], a["list"], a["tag"], a["value_type"], trig, keys,
                         "" if a["owns_mappings"] else "  (mappings NOT generator-owned)"))
        out.write("\n---- DA_InputConfig rows ----\n")
        for list_name in ("native_input_actions", "ability_input_actions"):
            out.write("  %s:\n" % list_name)
            for r in plan["config"][list_name]:
                out.write("    %-18s -> %s\n" % (r["input_tag"], r["input_action"]))
        out.write("\n---- IMC_Default additions (existing mappings are never removed) ----\n")
        for m in plan["mapping_context"]["mappings"]:
            out.write("    %-14s <- %s\n" % (m["name"], m["key"]))

    out.write("\n")
    if plan["errors"]:
        out.write("VERDICT: FAIL - %d validation error(s). No asset will be written.\n"
                  "         Fix Tools/gen_input/input_profile.json, never the contract constants.\n"
                  % plan["errors"])
    else:
        out.write("VERDICT: PASS - the profile is buildable. This is a STATIC (rung 1) check of a\n"
                  "         JSON file. It says nothing about what is on disk in Content/Input:\n"
                  "         the live assets are audited by build_input.py, under the editor.\n")


def main(argv=None):
    ap = argparse.ArgumentParser(
        description="Validate input_profile.json and print/emit the input-asset plan. "
                    "Plain CPython - no editor, no unreal module, safe while someone else "
                    "holds the project lock.")
    ap.add_argument("--profile", default=None, help="path to input_profile.json")
    ap.add_argument("--json", default=None, help="write the full plan JSON to this path")
    ap.add_argument("--verbose", action="store_true", help="list every action, row and mapping")
    args = ap.parse_args(argv)

    try:
        plan, _profile = load_all(args.profile)
    except ProfileError as exc:
        sys.stderr.write("BLOCKED: %s\n" % exc)
        return 3

    print_report(plan, verbose=args.verbose)
    if args.json:
        with open(args.json, "w", encoding="utf-8") as fh:
            json.dump(plan, fh, indent=2, sort_keys=True)
        sys.stdout.write("plan written: %s\n" % os.path.abspath(args.json))
    return 1 if plan["errors"] else 0


if __name__ == "__main__":
    sys.exit(main())
